cmd/kn/main.go
go.mod
go.sum
pkg/kn/commands/revision.go
pkg/kn/commands/revision_list.go
pkg/kn/commands/root.go
pkg/kn/commands/service.go
pkg/kn/commands/service_list.go
pkg/kn/commands/service_list_test.go

* Make commands take a params object
* Provide params for capturing output
* Provide params for mocking serving api
* Write tests with captured output and mocked serving api

Refactor to allow testing; write first tests.

---

.gitignore

Add more .gitignore

---

README.md

Adds documentation on how to build the project.

Add building documentaiton

---

pkg/kn/commands/service.go
pkg/kn/commands/service_describe.go
pkg/kn/commands/service_describe_test.go

Fixes #14
Thanks @nimakaviani for working with me on this 🙂

Add service describe

---

go.mod
go.sum
test/presubmit-tests.sh

go.mod and go.sum updates to point to knative/test-infra

go.mod and go.sum updates

---

README.md

Work towards fixing https://github.com/knative/docs/issues/1038

Update links to docs repo

---

CONTRIBUTING.md
DEVELOPMENT.md
README.md

Fixes #26 
Also adds CONTRIBUTING.md which points to knative/docs and links the development guide from README.md.

Adds DEVELOPMENT.md

---

.gitignore
hack/build-binaries.sh
hack/build.sh
pkg/kn/commands/root.go
pkg/kn/commands/service_describe_test.go
pkg/kn/commands/version.go
pkg/serving/config_changes_test.go

adding hack/build* to make life easy and added version command

---

pkg/kn/commands/namespaced.go
pkg/kn/commands/namespaced_test.go

Fix returning the namespace for listing resources

---

DEVELOPMENT.md
README.md

Just to make it a little easier for folks.

Add a Makefile

---

docs/workflows.md

* checked each command and add any ouput
* removes all `service list` since that's no longer a command
* adds `service get` and output

Updates docs/workflows.md

---

pkg/kn/commands/configuration_edit_flags.go
pkg/kn/commands/service_create.go
pkg/kn/commands/service_update.go
pkg/kn/commands/service_update_test.go

Checks if --image is given before applying image to config

---

pkg/kn/commands/completion.go

Adds missing license to completion.go

---

go.mod
go.sum
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/library.sh
vendor/modules.txt

update test-infra in vendor

---

go.mod
go.sum
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/library.sh
vendor/modules.txt

Fixing the forbidden images in the nightly release. 
Part of https://github.com/knative/test-infra/issues/844

Update test-infra to the latest version

---

test/e2e-tests.sh

fix(e2e): Use build.sh for compiling

---

docs/README.md
docs/cmd/kn_revision.md
docs/cmd/kn_revision_list.md
pkg/kn/commands/revision/human_readable_flags.go
pkg/kn/commands/revision/revision.go
pkg/kn/commands/revision/revision_list.go
pkg/kn/commands/revision/revision_list_flags.go
pkg/kn/commands/revision/revision_list_test.go

Renames revision 'get' to 'list'

---

pkg/kn/commands/revision/human_readable_flags.go
pkg/kn/commands/revision/revision_list.go
pkg/kn/commands/revision/revision_list_test.go

Exchange SERVICE and NAME column in kn revision list output

---

docs/README.md

Added link to OpenShift kubeconfig creation docs

---

.github/ISSUE_TEMPLATE/ask-question.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/pull-request-template.md

Adds Github issue and pull request templates

---

hack/build.sh

Rearranged script a bit to make easier to understand the various run modes.
Added a `--test` mode which will only run the tests

chore(build): Refactor to simplify and add dedicated test mode

---

test/e2e/service_options_test.go

/lint
* updates the validation of concurrency limits/targets with upcoming change to `service describe` output, uses `service list` with `jsonpath` output format
* validation commands now return specific field in output than returning complete output

improves(e2e): Update concurrency tests

---

OWNERS

Unanimous vote from current approvers on 07/30/2019
Congrats Navid!
* navidshaikh added to approvers list of OWNERS
```release-note
```

Adds Navid (@navidshaikh) to approvers list

---

DEVELOPMENT.md

Just noticed some missing things while installing on a new system

Update dev docs for some missing bits

---

pkg/kn/commands/service/service_create.go

Add 'creator' annotation on create --force

---

hack/build.sh

I believe this should be the behavior, based on https://github.com/knative/client/blob/master/DEVELOPMENT.md

Only test in watch mode if passed test flag

---

pkg/kn/flags/bool.go
pkg/kn/flags/bool_test.go

Code cleanup; quotes in error messages.

Clean up bool flags a little

---

pkg/kn/commands/namespaced_test.go
pkg/kn/commands/plugin/plugin_handler_test.go
pkg/kn/commands/plugin/plugin_list_test.go
pkg/kn/commands/plugin/plugin_verifier.go
pkg/kn/commands/plugin/plugin_verifier_windows.go
pkg/kn/commands/service/service_create_test.go
pkg/kn/commands/service/service_describe.go
pkg/kn/commands/service/service_update.go
pkg/kn/commands/types.go
pkg/kn/commands/types_test.go
pkg/kn/core/root.go
pkg/kn/traffic/compute.go
pkg/serving/schema_handling.go
pkg/util/parsing_helper.go
test/e2e/common.go
test/e2e/service_test.go
test/e2e/traffic_split_test.go

Fixes #
no issues
fix lints based on
* misspell
* ineffassign
* golint
https://goreportcard.com/report/github.com/knative/client
```release-note
-
```

fix lint errors

---

pkg/kn/commands/service/update_test.go
pkg/kn/commands/testing_helper.go
pkg/kn/commands/types_test.go
pkg/printers/tablegenerator.go
pkg/serving/config_changes.go
pkg/serving/v1alpha1/client_test.go

Fixes # no issues
* remove unused codes (structcheck)(varcheck)
* add error handling (errcheck)(ineffassign)
* fix lint errors (golint)

fix analyzer warnings

---

hack/build.sh

- Added `go mod tidy` before `go mod vendor` command

Runs go mod tidy part of updating dependencies in hack/build.sh

---

CHANGELOG.adoc

Added missing PRs with some substantial change, sorted list from newer to older PRs.

chore: Update changelog in prep for 0.8.0

---

pkg/kn/commands/service/describe.go
pkg/kn/commands/service/describe_test.go
test/e2e/basic_workflow_test.go

fix(service describe): Clarify URL labels

---

CHANGELOG.adoc

chore: Prep for v0.10.0 release

---

docs/workflows/basic.md

- Updated to reflect the service create/update/describe/delete output

chore(docs): Updates basic workflow doc

---

test/presubmit-integration-tests-latest-release.sh

- This changeset updates serving version for pull-knative-client-integration-tests-latest-release
- Serving nightly release is tested in prow job pull-knative-client-integration-tests

chore(e2e): Run e2e against latest released serving version v0.10.0

---

test/e2e/e2e_flags.go

as said
part of: https://github.com/knative/test-infra/pull/1558

Remove explicit flag parsing so that it works with go1.13

---

.gitignore
pkg/kn/commands/revision/delete.go
pkg/kn/commands/revision/describe.go
pkg/kn/commands/revision/list.go
pkg/kn/commands/route/describe.go
pkg/kn/commands/route/list.go
pkg/kn/commands/service/create.go
pkg/kn/commands/service/delete.go
pkg/kn/commands/service/describe.go
pkg/kn/commands/service/list.go
pkg/kn/commands/service/service_test.go
pkg/kn/commands/service/update.go
pkg/kn/commands/testing_helper.go
pkg/kn/commands/types.go

/lint
- Renames NewClient to NewServingClient, since now we're adding more clients
- Add cover.html to gitignore

Explicit name for serving client

---

pkg/kn/commands/service/create_mock_test.go
pkg/kn/commands/service/delete_mock_test.go
pkg/kn/commands/service/describe_test.go
pkg/kn/commands/service/list_mock_test.go
pkg/kn/commands/service/service_update_mock_test.go
pkg/serving/v1alpha1/client_mock.go
pkg/serving/v1alpha1/client_mock_test.go
pkg/util/mock/mock_helper.go

This makes it easier for other components (like eventing) to introduce an own
mock for their tests.

chore: Refactor mock testing

---

test/e2e/source_apiserver_test.go

* Add e2e test for source apiserver create and delete

Add source apiserver create/delete e2e test

---

docs/cmd/kn_source_apiserver_create.md
docs/cmd/kn_source_apiserver_update.md
pkg/eventing/v1alpha1/client.go
pkg/eventing/v1alpha1/client_mock.go
pkg/eventing/v1alpha1/client_test.go
pkg/kn/commands/source/apiserver/create.go
pkg/kn/commands/source/apiserver/create_flag_test.go
pkg/kn/commands/source/apiserver/create_test.go
pkg/kn/commands/source/apiserver/flags.go
pkg/kn/commands/source/apiserver/update.go
pkg/kn/commands/source/cronjob/create.go
pkg/kn/commands/source/cronjob/delete.go
pkg/kn/commands/trigger/create.go
pkg/kn/commands/trigger/create_test.go
pkg/kn/commands/trigger/trigger_test.go
pkg/kn/commands/trigger/update.go
pkg/kn/commands/trigger/update_flags.go
pkg/kn/commands/version/version.go
pkg/kn/commands/version/version_test.go
test/e2e/source_apiserver_test.go

so that no objevt is returned + introduced a builder

chore(trigger): Cleanup Trigger create API

---

CHANGELOG.adoc

Fix link in CHANGELOG

---

test/README.md

* fix for review comments in  [pr555](https://github.com/knative/client/pull/555#discussion_r358082251)

review comments for pr 555

---

pkg/kn/commands/service/human_readable_flags.go
pkg/kn/commands/service/list.go
pkg/kn/commands/service/list_mock_test.go
pkg/kn/commands/service/list_test.go

refactor(service list): Removed special "default" namespace handling

---

go.mod
go.sum
vendor/knative.dev/test-infra/scripts/library.sh
vendor/modules.txt

Update test-infra: Eventing nightly release YAML rename
per https://github.com/knative/test-infra/commit/d5990f0e5a05d5819a40ad3b4de6227406850b48

Update test-infra: Eventing nightly release YAML rename

---

test/e2e/service_options_test.go

Follow-up to PR #635
* Add E2E test for `--cmd` and `--arg` flags

Add e2e test for cmd and arg options

---

docs/README.md
test/presubmit-tests.sh

sets `DISABLE_MD_LINK_CHECK=1` and `PRESUBMIT_TEST_FAIL_FAST=1`

Disable markdown link check and enable presubmit test fail fast

---

test/e2e/trigger_test.go

* Remove labels and triggers before ending the e2e test

Fix for the failure of trigger e2e test

---

go.mod
go.sum
test/presubmit-tests.sh
vendor/knative.dev/test-infra/scripts/README.md
vendor/knative.dev/test-infra/scripts/e2e-tests.sh
vendor/knative.dev/test-infra/scripts/library.sh
vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
vendor/knative.dev/test-infra/scripts/release.sh
vendor/modules.txt

* Re-enable markdown link check as https://github.com/raviqqe/liche/issues/33 is now fixed,
see https://github.com/knative/test-infra/pull/1764/
* Update test-infra to latest

Re-enable markdown link check

---

hack/update-deps.sh

See: https://github.com/knative/client/pull/704#discussion_r389242726
/assign @rhuss @maximilien

Follow up on Roland's review comment.

---

hack/generate-docs.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party)`
/assign maximilien rhuss
/cc maximilien rhuss

golang format tools

---

pkg/dynamic/client_test.go
pkg/dynamic/fake/fake.go
pkg/kn/commands/source/apiserver/apiserver_test.go
pkg/kn/commands/source/binding/describe.go
pkg/kn/commands/source/ping/ping_test.go

Produced via:
`github.com/client9/misspell`
/assign maximilien rhuss
/cc maximilien rhuss

Fix spelling errors

---

.github/pull-request-template.md

Fix a typo in pull request template
* Fix a typo in markdown file `.github/pull-request-template.md`

chore: fix a typo in pull request template

---

.github/ISSUE_TEMPLATE/feature-request.md

typo `s/suhc/such/` in `feature-request.md` file
* `s/suhc/such/`

fix: typo in issue template feature-request.md file

---

docs/cmd/kn_service_create.md
docs/cmd/kn_service_update.md
pkg/kn/commands/service/configuration_edit_flags.go

missing paren

---

pkg/eventing/v1alpha1/client.go
pkg/kn/commands/describe.go
pkg/sources/v1alpha2/binding_client.go

found this from newly added CI check https://lgtm.com/projects/g/knative/client/alerts/?mode=list

Remove unused variables and unreachable code

---

conventions/cli.md

Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)`
/assign maximilien rhuss
/cc maximilien rhuss

[master] Format markdown

---

docs/cmd/kn_service_create.md
docs/operations/management.md
pkg/kn/commands/service/create.go

Fixes #673
- uses image: `knativesamples/helloworld`

docs: Update kn service create examples with real image

---

pkg/kn/commands/source/human_readable_flags.go

for output of `kn source list-types`

Add description for ContainerSource

---

CHANGELOG.adoc

Sorry I forgot to add changelog update in my previous PR.
@rhuss 
@navidshaikh

chore: Add broker management feature to changelog

---

hack/update-deps.sh

Pin to knative.dev/{pkg,eventing,serving}@release-16

---

CHANGELOG.adoc
pkg/serving/config_changes.go

Fix error message for port validation
* Fix error message for port validation
* Add changelog for port spec changes
/assign @navidshaikh

Update CHANGELOG and error for port flag parsing

---

README.md

fix(docs): Fix tekton task link

---

CHANGELOG.adoc
pkg/kn/commands/source/human_readable_flags.go
pkg/kn/commands/source/list_test.go

Fix for Missing NAMESPACE column header for 'kn source list -A'
Fixes #946

Fix missing NAMESPACE column header

---

test/e2e/tekton_test.go

This PR changes the address for Tekton tasks, to point to the new structure. This should be done to assure we're supporting the newest definitions from Tekton catalog.
* Use Tekton Catalog GA structure for tasks
Fixes #965

Use Tekton Catalog GA structure for tasks

---

CHANGELOG.adoc
README.md
lib/test/revision.go
pkg/dynamic/client.go
pkg/dynamic/client_test.go
pkg/dynamic/lib.go
pkg/dynamic/lib_test.go
pkg/errors/errors.go
pkg/errors/factory.go
pkg/errors/factory_test.go
pkg/kn/commands/revision/delete.go
pkg/kn/commands/revision/delete_test.go
pkg/kn/commands/revision/revision_test.go
pkg/kn/commands/service/delete.go
pkg/kn/commands/service/delete_mock_test.go
pkg/kn/commands/source/human_readable_flags.go
pkg/kn/commands/source/list.go
pkg/kn/commands/source/list_test.go
pkg/kn/commands/source/list_types.go
pkg/serving/config_changes.go
pkg/serving/config_changes_test.go
pkg/sources/v1alpha2/apiserver_client.go
pkg/sources/v1alpha2/client.go
pkg/sources/v1alpha2/client_test.go
test/e2e/service_test.go
test/e2e/source_list_test.go
test/e2e/tekton_test.go

Client v0.16.1 release backports for bug fixes.
- Update CHANGELOG
- Cherry pick:
- #980 
- #975 
- #971 
- #966 
- #963 
- #951 
- #948 
- #934

v0.16.1 release backports

---

CHANGELOG.adoc
docs/plugins/README.md
go.sum
lib/test/broker.go
pkg/kn/config/config.go
pkg/kn/plugin/manager.go
pkg/kn/plugin/manager_test.go

Plugin inlining (backport)

---

CHANGELOG.adoc

* CHANGELOG entry for #990 
Fixes #

CHANGELOG entry for PR #990

---

test/e2e/tekton_test.go

It often happens that the tests fail and there's no error message. This is very helpful when analyzing the failures.
*
*
*
Fixes #

Print logs from PipelineRun pods when Tekton tests fail

---

go.mod
go.sum
scripts/test-infra/presubmit-tests.sh
vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
vendor/modules.txt

Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc rhuss maximilien
/assign rhuss maximilien

[Automated] Upgrade to latest dependencies

---

go.mod
go.sum
hack/update-deps.sh
vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
vendor/modules.txt

/assign @mattmoor 
/assign @n3wscott

Pin serving and eventing to release-0.18

---

test/presubmit-integration-tests-latest-release.sh

chore(e2e): Run e2e against serving/eventing v0.18.0

---

pkg/kn/commands/service/configuration_edit_flags.go
pkg/kn/commands/service/create_mock_test.go

Update error message when autoscaling annotation used in service
/lint

Update error message when autoscaling annotation used in service

---

CHANGELOG.adoc

Carry CHANGELOG from v0.17.1 patch release

---

CHANGELOG.adoc
lib/test/subscription.go
pkg/kn/commands/service/configuration_edit_flags.go

- Backport:
- #1044 
- #1010 
- Update CHANGELOG

[0.17] Backport 1044 and 10101

---

go.mod
go.sum
scripts/test-infra/library.sh
scripts/test-infra/performance-tests.sh
vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
vendor/modules.txt

Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc rhuss maximilien
/assign rhuss maximilien

[master] Upgrade to latest dependencies

---

CHANGELOG.adoc
pkg/kn/commands/channel/channel_test.go
pkg/kn/commands/channel/create.go
pkg/kn/commands/channel/create_test.go
pkg/kn/commands/channel/describe_test.go
pkg/kn/commands/channel/list_test.go
pkg/messaging/v1beta1/channels_client.go

Backport PR for release-v0.18.3 with
- #1117 
- Updated CHANGELOG

[release-0.18] Backport of #1117

---

CHANGELOG.adoc
pkg/kn/commands/channel/channel_test.go
pkg/kn/commands/channel/create.go
pkg/kn/commands/channel/create_test.go
pkg/kn/commands/channel/describe_test.go
pkg/kn/commands/channel/list_test.go
pkg/messaging/v1beta1/channels_client.go

Backport PR for release-v0.17.4 with
- #1117
- Updated CHANGELOG

[release-0.17] Backport of #1117

---

test/presubmit-integration-tests-latest-release.sh

chore(e2e): Run latest release e2e job against v0.19.x

---

CHANGELOG.adoc
hack/build.sh
hack/release.sh
pkg/eventing/v1beta1/client.go
pkg/kn/commands/channel/channel_test.go
pkg/kn/commands/channel/create.go
pkg/kn/commands/channel/create_test.go
pkg/kn/commands/channel/describe_test.go
pkg/kn/commands/channel/list_test.go
pkg/messaging/v1beta1/channels_client.go
pkg/serving/v1/client.go
pkg/wait/wait_for_ready.go
pkg/wait/wait_for_ready_test.go

Backport PR for release-v0.19.1 with
- #1117
- #1083 
- #1113 
- Updated CHANGELOG

[release-0.19] Backport #1117 #1083 #1113

---

CHANGELOG.adoc
hack/release.sh

- no arm build for this release
- update date in changelog for kn v0.18.4

[release-0.18] Update hack/release.sh

---

CHANGELOG.adoc

Carry changelogs from patch releases to main branch

---

test/e2e-tests.sh

since the ping source update issue is now fixed
see https://github.com/knative/eventing/pull/4597
https://github.com/knative/eventing/issues/4584

Run e2e-tests against eventing nightly

---

CHANGELOG.adoc
docs/cmd/kn_source_ping_describe.md
pkg/kn/commands/source/ping/describe.go
pkg/kn/commands/source/ping/describe_test.go
pkg/sources/v1alpha2/ping_client.go

*Add machine readable output (-o flag) to kn source ping describe
Fixes #1098

Add machine readable output (-o flag) to kn source ping describe

---

hack/update-codegen.sh
vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/namesystems.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
vendor/knative.dev/pkg/hack/generate-knative.sh
vendor/knative.dev/pkg/hack/tools.go
vendor/knative.dev/pkg/hack/update-codegen.sh
vendor/knative.dev/pkg/hack/update-deps.sh
vendor/knative.dev/pkg/hack/update-k8s-deps.sh
vendor/knative.dev/pkg/hack/verify-codegen.sh
vendor/modules.txt

- Use GOPATH hacks to codegen anywhere.

Integrate the gopath hacks to allow for codegen anywhere.

---

docs/README.md

It's not automatically updated with every release (#400)

Include homebrew install instructions in user guide

---

docs/DEVELOPMENT.md

Update link to contribution guidelines

---

test/presubmit-integration-tests-latest-release.sh

Post release version update.
* Bump Serving & Eventing version to `0.21.0`

chore: Update E2E setup to latest release

---

OWNERS

Thanks David for sustain and excellent contributions
/assign @rhuss 
* add @dsimansk to reviewers: section

Adding dsimansk to reviewers:

---

CHANGELOG.adoc

change log for PR #1212 
cc @dsimansk

add changelog for 1212

---

test/README.md

List the two e2e prow jobs being run in the CI.

docs: About e2e prow jobs

---

OWNERS

David meets all criteria for an approver:
* https://github.com/knative/client/pull/1246
* https://github.com/knative/client/pull/1194
* https://github.com/knative/client/pull/738
* https://github.com/knative/client/pull/832
* https://github.com/knative/client/pull/1016
* https://github.com/knative/client/pull/877
* https://github.com/knative/client/pull/667
* https://github.com/knative/client/pull/697
* https://github.com/knative/client/pull/1212
* https://github.com/knative/client/pull/835
Congrats David ! Thanks a lot for your awesome work & contributions.

Add David as approver

---

test/common.sh
test/e2e-tests.sh

This PR changes Istio setup to version provided from Knative's net-istio repository instead of GKE addon.
/hold

Use net-istio provided version in E2E setup

---

test/common.sh

A bit of cleanup per title.
* Remove standalone sugar controller setup in favour of common one

Use common Eventing setup from hack library

---

CHANGELOG.adoc
go.mod
go.sum
pkg/kn/commands/version/version.go
vendor/modules.txt

Prepare for release 0.22.0

---

docs/cmd/kn_domain_describe.md
docs/cmd/kn_domain_list.md
pkg/kn/commands/domain/describe.go
pkg/kn/commands/domain/list.go

Some fixes in `kn domain` help messages

---

test/presubmit-integration-tests-latest-release.sh

Per subject bump Serving & Eventing to `0.22.0`.

chore(ci): Update E2E latest release versions for Serving & Eventing

---

CHANGELOG.adoc

* Update changelog for release v0.23.0

Update changelog for release v0.23.0

---

CHANGELOG.adoc
pkg/eventing/v1/client.go
pkg/eventing/v1/client_test.go
pkg/serving/v1/client.go
pkg/serving/v1/client_test.go
pkg/wait/poll_watcher.go
pkg/wait/wait_for_ready.go
pkg/wait/wait_for_ready_test.go

Per subject revert PR#1301
/assign @rhuss

Revert "Refactor waiting loop to use resourceVersion

---

test/presubmit-integration-tests-latest-release.sh

Releasing client 0.23 so updating presubmit for it.
* Update presubmit to version 0.23 for the release.
*
*
Fixes #

bump presubmit to .23

---

CHANGELOG.adoc

Update changelog entries for the next release.
/cc @rhuss @maximilien @navidshaikh

Update changelog for 0.24.0 release

---

pkg/wait/poll_watcher_test.go
pkg/wait/wait_for_ready_test.go

Adding tests/changing existing tests to increase code coverage
* Added new test case TestNewWatcherWithVersion
* Added new test case TestSimpleMessageCallback
Related to #1322

Adding tests for wait pkg

---

pkg/kn/commands/flags/listprint_test.go
pkg/kn/commands/flags/sink_test.go
pkg/kn/commands/flags/traffic_test.go
pkg/kn/commands/human_readable_flags_test.go

Adding test cases for flag pkg
* Added new test cases for some of the functions
* Modified existing test cases to increase coverage
Fixes #1322

Adding tests for commands/flag pkg

---

pkg/kn/commands/describe_test.go
pkg/kn/commands/namespaced_test.go
pkg/kn/commands/types_test.go

Adding test cases for commands package
* Added a few new test cases for some files
* Modified existing cases to increase coverage
Fixes #1322

Adding tests for commands package

---

pkg/serving/config_changes_test.go
pkg/serving/revision_template_test.go
pkg/serving/v1/apply_test.go
pkg/serving/v1/client_test.go
pkg/serving/v1/gitops_test.go

Adding test cases for serving pkg
* Added new test cases
* Modified existing test cases for more coverage
Related to #1322

Adding test cases for serving pkg

---

pkg/kn/commands/namespaced_test.go

Executing unit tests inside the K8s pod may result in false positive failures due to in-cluster kubeconfig taking precedence over mocked one.
* Fix unit tests to use NAMESPACE value in k8s cluster env 
/cc @rhuss

Fix unit tests to use NAMESPACE value in OpenShift CI env

---

test/presubmit-integration-tests-latest-release.sh

update versions to 0.25

---

CHANGELOG.adoc

* Update & format changelog for the next release

Update changelog for 0.26 release

---

hack/build.sh
test/e2e/plugins_test.go

Added a few windows specific changes so the tests work on the OS
* Changed the kn binary extension to exe on windows
* Added OS specific path separators
* Added batch code for plugin tests on windows
Fixes #

Fix windows e2e plugin tests

---

CHANGELOG.adoc

Updates change log to point to correct PR number

Fix changelog reference for pull request 1433

---

docs/cmd/kn_container_add.md
docs/cmd/kn_service_apply.md
docs/cmd/kn_service_create.md
docs/cmd/kn_service_update.md
docs/cmd/kn_source_container_create.md
docs/cmd/kn_source_container_update.md
pkg/kn/commands/container/add.go
pkg/kn/commands/container/add_test.go
pkg/kn/flags/podspec.go
pkg/kn/flags/podspec_test.go
test/e2e/extra_containers_test.go

and make `--extra-containers deprecated`

Rename `--extra-containers` to `--containers`

---

test/common.sh

Fix fetching of Istio latest release

---

CHANGELOG.adoc

* Add missing changelog entries
* Order entries
* TBD: `--lookup-path` PR link
Fixes #

Update changelog for 1.0 release

---

test/presubmit-integration-tests-latest-release.sh

Release prep step: https://github.com/knative/release/#knativeclient
* Update Serving and Eventing versions in E2E tests
/cc @rhuss

Update Serving and Eventing versions in E2E tests

---

test/common.sh

Per TODO properly fix the version fetch.
* Fix fetching of Istion latest release
Fixes #

Fix fetching of Istion latest release

---

docs/cmd/kn_broker_create.md
pkg/kn/commands/broker/create.go

Fix `kn broker create` example docs.
* Change `--broker` to `--class`
Fixes #1540

docs: Fix broker class in create command

---

CHANGELOG.adoc

Changelog update for release tomorrow.
* Update changelog for 1.2 release
/cc @vyasgun @rhuss @navidshaikh @maximilien

Update changelog for 1.2 release

---

CHANGELOG.adoc

* Update changelog for 1.3 release

Update changelog for 1.3 release

---

test/common.sh

We're run into case where Serving latest release is `1.3.1`, but Net-Istio is still `1.3.0`.
If it works, `*-latest-release` tests will pass.
* Fix latest release CI setup
/cc @vyasgun

Fix latest release CI setup

---

.codecov.yaml

* Align codecov config with rest of the org
/cc @vyasgun

Align codecov config with rest of the org

---

.ko.yaml
hack/build-flags.sh
hack/release.sh

* Fix display version in OCI image
Fixes #257 

Fix display version in OCI image

---

test/tekton-tests.sh

I've missed that in previous PR.
* Fix Tekton e2e script
/cc @vyasgun

Fix Tekton e2e script

---

tools/knb/README.md
tools/knb/pkg/plugin/distro.go
tools/knb/pkg/plugin/plugin.go

Update `knb` to recognize drop-in replacement for a certain plugin. Update readme. And make sure everything is updated with `hack/update-deps.sh`.
/cc @vyasgun @rhuss 
* Update knb to recognize drop-in module replace
Fixes #
```release-note
NONE
```

Update knb to recognize drop-in module replace

---

pkg/kn/commands/namespaced_test.go

Fix unit test when run in release jobs.
/cc @nak3 @lionelvillard @rhuss @vyasgun 
* Fix namespaced unit test
Fixes #
```release-note
NONE
```

Fix namespaced unit test

---

go.mod
go.sum
vendor/modules.txt

And one more please. This's a cosmetic fix to have a pretty display version of Serving when `kn version` is invoked.
/cc @rhuss @vyasgun @lionelvillard @nak3 
* Resolve Serving version to released tag
Fixes #
```release-note
```

Resolve Serving version to released tag

---

test/test_images/helloworld/Dockerfile

Prevents error such as the following when the Pod security context has `"runAsNonRoot": true:`:
```
"container has runAsNonRoot and image will run as root (pod: \"hello-00001-deployment-65676fb5b5-29mlc_tkn-kn0(930c61ec-28cf-46b8-8dad-d6d54e896b06)\", container: user-container)"
```
* Dockerfile for helloworld runs as USER 65532
*
*
Fixes #
```release-note
```

Helloworld image running with non root user

---

go.mod
pkg/kn/commands/eventtype/list.go

It's blocking auto-update job to update deps actually.
* Remove toolchain directive
Fixes #
```release-note
NONE
```

Remove toolchain directive

---

go.mod
go.sum
go.work.sum
pkg/go.mod
pkg/go.sum
pkg/plugin/manager.go

* Remove dependency on deprecated client-pkg
Fixes #
```release-note
Remove dependency on deprecated client-pkg
```
/cc @cardil

Remove dependency on deprecated client-pkg

---

DEVELOPMENT.md

This PR refactors `client/DEVELOPMENT.md` to remove/update broken links.
* remove link for `The pull request workflow`
* update link for `Set up Knative`
* update link for `go mod`
Please see [issue 2004](https://github.com/knative/client/issues/2004)

Update broken links on `client/DEVELOPMENT.md`
