- pkg/kn/commands/revision.go
- pkg/kn/commands/root.go
- pkg/kn/commands/service.go
s/blokcs/blocks
and removes few unneeded dots (.)
> Fixes typo in the kn help command

- pkg/kn/commands/root.go
Use `$KUBECONFIG` env variable as config path if set,  #17
> Pickup config path from KUBECONFIG

- README.md
- pkg/kn/commands/completion.go
- pkg/kn/commands/root.go
This patch adds subcommand to generate completion script for bash.
As an knative user, we would like to complete subcommands and
options rather than typing them.
Usage Example:
```
$ source <(kn completion)
$ kn <TAB>
completion  revision    service
$ kn service list --<TAB>
--allow-missing-template-keys  --kubeconfig=                  --output=
--config=                      --namespace=                   --template=
```
> Support generating bash completion

- cmd/kn/main.go
- pkg/kn/commands/root.go
This patch adds flag.Parse() to avoid `logging before flag.Parse` error.
c.f. -  other repository also solved the issue by calling `flag.Parse()` first.
https://github.com/knative/eventing/blob/8ba0b39f5150f8fae7184ab189f4086cbc98bf42/contrib/gcppubsub/pkg/dispatcher/cmd/main.go#L46
Fixes https://github.com/knative/client/issues/37
> Fix flag parse error by calling flag.Parse first

- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/service.go
This implements `kn service create` supporting only the `--image` and `--env` flags.
It also provides a structure for collecting flags that will be in common between `create`, `update`, and `replace`, and using them to modify a Configuration (so they can also be reused for `configuration create` etc later)
> `service create` beginning implementation

- hack/update-deps.sh
- hack/verify-codegen.sh
Yes, the file is called verify-codegen.sh, and yes in the other
Knative projects it both verifies generated code and verifies vendored
dependencies are up-to-date. For client, it just verifies vendored
dependencies don't drift.
The test-infra scripts specifically look for a file with this name. If
we'd prefer to call this something else, we'll also need to update
test-infra to look for that something else.
> Add hack/verify-codegen.sh so CI verifies vendor/ doesn't drift

- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
Although `service create` command always requires and specify `--image` to run,
there are no validation atm.
This patch changes:
- Add validation check if image is empty or not.
- Add image to `MarkFlagRequired()`.
- to add `--image IMAGE` in help message
> Make image flag mandatory for service create command

- pkg/kn/commands/service_create.go
Fixes #61
Adds two examples to service create command as below
```
Examples:
kn service create mysvc --image dev.local/ns/image:latest
kn service create mysvc --env KEY1=VALUE1 --env KEY2=VALUE2 --image dev.local/ns/image:latest
```
> Adds example usage in service create command

- go.mod
- pkg/kn/commands/namespaced.go
- pkg/kn/commands/revision.go
- pkg/kn/commands/revision_describe.go
- pkg/kn/commands/revision_list.go
- pkg/kn/commands/root.go
- pkg/kn/commands/service.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_describe.go
- pkg/kn/commands/service_list.go
Currently `kn {service, revision} list` does not have the all-namespaces
options. Although it is possible to list them by `kn service list -n
""`(empty string), it is difficult to find such secret trick.
Hence, this patch adds `--all-namespaces` option.
> Support --all-namespaces option for service and revision list

- pkg/kn/commands/service.go
- pkg/kn/commands/service_delete.go
This chageset adds `service delete` command, able to delete a service
at a time.
Fixes #49
```
kn service delete --help
Delete a service
Usage:
kn service delete <SERVICE_NAME> [flags]
Aliases:
delete, del, d
Examples:
kn service delete svc1
kn service delete svc2 -n ns1
```
> Adds service delete command

- pkg/kn/commands/service_delete.go
This patch uses GetNamespace() utils in service delete command.
Fixes https://github.com/knative/client/issues/72
> Call GetNamespace to get namespace

- pkg/kn/commands/service.go
- pkg/kn/commands/service_update.go
- pkg/kn/commands/service_update_test.go
Note that this only tests updating the image, since updating the env vars but _not_ the image is likely to want in the future the client convention of locking it to the image-by-digest currently running. That's for a future PR though.  This version of update is dead simple — fetch, modify, put. Rely on resourceVersion to keep us from clobbering someone else's edit.
> Basic service update & a test for it.

- go.mod
- go.sum
- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
- pkg/serving/config_changes.go
- vendor/modules.txt
Examples:
* `kn service create mysvc --image dev.local/ns/image:latest --request-cpu 100m --requests-memory 64Mi`
* `kn service create mysvc --image dev.local/ns/image:latest --limits-cpu 1000m --limits-memory 1024Mi`
You can also include and/or omit the requests and limits. So the following should also work:
`kn service create mysvc --image dev.local/ns/image:latest  --request-cpu 1000m --limits-memory 1024Mi`
> Added support for limits and requests of CPU and memory

- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
- pkg/kn/commands/service_update.go
- pkg/kn/commands/service_update_test.go
* added tests for service update with variations of --requests/limits-cpu --requests/limits-memory
* made image optional on service update since that was not the case and image should be optional
> added tests to `$kn service update ...` with --requests/limits-cpu/memory and removed required --image

- pkg/kn/commands/root.go
> Set `SilenceErrors: true` on `rootCmd` so that we can deal with errors ourselves

- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
- pkg/kn/commands/service_delete.go
> Adds info message after service create and delete operations

- docs/workflows.md
* deploy a function (list, update, curl, describe, and delete)
Completes more of issue #51
> Adds basic workflow

- hack/build-binaries.sh
Previously, we were running into errors on computers without cross-compilation C
headers. For simplicity of building, and because we don't need superperformant
net libs, disable cgo.
> Disable cgo extensions in build-binaries.sh

- test/e2e-tests.sh
It's now `get`, not `list` anymore.
> Fix command for "kn service" smoke test

- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
Fixes #13 
Note the `--force` flag
```
Examples:
kn service create mysvc --image dev.local/ns/image:latest
kn service create mysvc --env KEY1=VALUE1 --env KEY2=VALUE2 --image dev.local/ns/image:latest
kn service create --force s1 --image dev.local/ns/image:v2
kn service create --force s1 --env KEY1=NEW_VALUE1 --env NEW_KEY2=NEW_VALUE2 --image dev.local/ns/image:v1
kn service create --force s1 --image dev.local/ns/image:v1
```
> Adds --force flag to service create command (service replace)

- go.mod
- go.sum
- hack/release.sh
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
- vendor/modules.txt
This requires updating test-infra to deal with a repo that has no releases yet.
Also use hash and dates from the helper, to keep the binary and the GCS dirs in sync.
> Fix auto releases of Knative Client

- hack/build-flags.sh
- hack/build.sh
- hack/release.sh
so that it can be shared between build.sh and release.sh
Fixes #120
> fix(build.sh): Reintroduced build-flags.sh

- README.md
- docs/README.md
- docs/cmd/kn_revision_get.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_get.md
- docs/workflows.md
Also move things less relevant to user guiding into project README rather than user guide.
> Copy-edit documentation, and make user guide start with installation.

- test/e2e-tests.sh
> Tests running simple workflow in e2e

- docs/cmd/kn_revision_describe.md
- docs/cmd/kn_revision_get.md
- docs/cmd/kn_service_describe.md
- docs/cmd/kn_service_get.md
- go.mod
- go.sum
- vendor/k8s.io/cli-runtime/pkg/genericclioptions/jsonpath_flags.go
- vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go
- vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/jsonpath.go
- vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/builder.go
- vendor/k8s.io/cli-runtime/pkg/genericclioptions/template_flags.go
- vendor/modules.txt
The update to kubernetes-1.13.5 for cli-runtime introduces a fix for #135 (i.e. sorting the keys for the options)
> fix: Update cli-runtime to include fix for cli options help

- DEVELOPMENT.md
- hack/build.sh
* Added running unit tests to the script
* Added options to support different development flows (see help message below)
* Allow symlinking to /usr/local/bin so that the script can be called from anywhere
Usage message:
```
Knative Client Build Script
Usage: hack/build.sh [... options ...]
with the following options:
-f  --fast                    Only build (without formatting, testing, code generation)
-t  --test                    Run tests even when used with --fast
-u  --update                  Update dependencies
-h  --help                    Display this help message
--verbose                 Verbose script output (set -x)
You can add a symbolic link to this build script into your PATH so that it can be
called from everywhere. E.g.:
ln -s .../hack/build.sh /usr/local/bin/kn_build.sh …
```
> feat(build.sh): Adding options and running tests

- pkg/kn/commands/configuration_edit_flags.go
- pkg/kn/commands/service_create.go
- pkg/kn/commands/service_create_test.go
- pkg/kn/commands/service_update.go
- pkg/kn/commands/service_update_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/service.go
This reflects the lemonade process step1. Tests have been adapted to
verify this behaviours.
The only situation when we update field coming from the server is for
"kn service update" for envs, image and requests/limits.
All other operation are either create (here, we always have to send the
old fields), or read (get/describe).
Fixes #144.
> fix(service update): Only update fields which have been sent by server.

- config/release.yaml
- hack/release.sh
> Add the support to build container image for kn

- DEVELOPMENT.md
- hack/build.sh
This features uses and requires https://github.com/AgentCosmic/xnotify
and should work on any platform
Use it with
* Watch & compile: build.sh --watch
* Watch, compile, test: build.sh --watch --test
* Watch, compile, test & verbose output: build.sh --watch --test --verbose
(shortcuts -w && -t can be used, too)
> feat(build.sh): Add a watch mode for automatic recompilation

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/service_create_test.go
- pkg/kn/commands/service/service_update_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- vendor/modules.txt
Autoscaler annotations are added to the revision template if
--min-scale / --max-scale / --target are provided to `kn service create` or
`kn service update`
Fixes #151
~This PR builds on top of #156 but can be back-ported on master if desired.
For review I recommend to look at commit efb23b778cf2104337fc6e4dc7d7e2b67d084465 first, which contains the delta.~
The PR is now based on upstream master only.
> feat(service create/update): Add support of minScale/maxScale/target

- DEVELOPMENT.md
- README.md
* Link to >1 install doc, depending on situation
* Link to official site for knative-wide developer info
> Improve links in development docs

- pkg/kn/commands/test_helper.go
- pkg/kn/commands/types.go
This patch removes unused `CfgFile` value from codes.
Related to https://github.com/knative/client/pull/139
> Remove unused value CfgFile

- hack/build.sh
While working with `build.sh --watch` it turned out the underlying
tool xnotify is not matured enough:
* It doesn't work when IntelliJ IDEA changes a file
* It can't deal with ignoring newly generated temp files (like .swp for vi)
This commit exchanges xnotify with fswatch which is much more matured.
> fix(build.sh): Change from xnotify to fswatch for watching source code

- hack/build-flags.sh
- hack/build.sh
We could decide to make that optional, too, if this is coming into the way.
> feat(build.sh) - Add mandatory license check

- DEVELOPMENT.md
- README.md
I was reading your docs, I found some mistakes. Hope you find them useful!
> Chore: Fix typos in docs

- docs/cmd/kn_revision_list.md
- pkg/kn/commands/revision/revision_list.go
- pkg/kn/commands/revision/revision_list_flags.go
- pkg/kn/commands/revision/revision_list_test.go
- test/e2e/basic_workflow_test.go
- vendor/modules.txt
Fixes #127 
```
kn revision list
SERVICE   NAME          AGE     CONDITIONS   READY   REASON
hello     hello-dfc7p   109m    4 OK / 5     True    
hello     hello-h9qdr   20h     4 OK / 5     True    
svc1      svc1-ksds5    7m11s   4 OK / 5     True    
kn revision list -s svc1
SERVICE   NAME         AGE     CONDITIONS   READY   REASON
svc1      svc1-ksds5   7m15s   4 OK / 5     True    
kn revision list -s hello
SERVICE   NAME          AGE    CONDITIONS   READY   REASON
hello     hello-dfc7p   109m   4 OK / 5     True    
hello     hello-h9qdr   20h    4 OK / 5     True    
```
> List revisions for a given service

- cmd/kn/main.go
- pkg/kn/commands/namespaced.go
- pkg/kn/commands/namespaced_test.go
- pkg/kn/commands/revision/revision_describe.go
- pkg/kn/commands/revision/revision_list.go
- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/service_create_test.go
- pkg/kn/commands/service/service_delete.go
- pkg/kn/commands/service/service_describe.go
- pkg/kn/commands/service/service_list.go
- pkg/kn/commands/service/service_list_test.go
- pkg/kn/commands/service/service_update.go
- pkg/kn/commands/test_helper.go
- pkg/kn/commands/types.go
- pkg/kn/core/root.go
`kn` command does not pick up namespace from kubeconfig but hardcorded
`default` namespace.
This patch fixes to get namespace from kubeconfig.
Fixes https://github.com/knative/client/issues/7
> Set current namespace from kubeconfig by default

- test/e2e-smoke-tests.sh
This should allow a set of small e2e tests that only use `kn` and do not depends on the e2e Golang code and other dependencies that it might create.
> Restores the bash e2e tests as a smoke test

- hack/build.sh
Iterm has an issue with rendering multi byte unicode chars. This
commit adds an extra space to certain emojis on iterm only.
This fixes current rendering issues on Linux term because that extra
space was added previously unconditionally.
> fix(build.sh): Cosmetic spacing fix

- OWNERS
Top two committers in the last while who also participate in WG meetings regularly.
> Add rhuss and maximilien to OWNERS to increase approver speed.

- go.mod
- go.sum
- test/e2e/e2e_flags.go
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/modules.txt
See https://testgrid.knative.dev/client#continuous.
/cc @adrcunha
> Fix the periodic CI flow error in client

- go.mod
- go.sum
- hack/build.sh
- pkg/kn/commands/namespaced_test.go
- pkg/kn/commands/revision/revision_list.go
- pkg/printers/tableprinter.go
- pkg/serving/config_changes_test.go
Much like 'go fmt' for cleaning up go source, 'goimports' can help
in properly formatting and grouping imports. See https://goinbigdata.com/goimports-vs-gofmt/
for a quick overview.
This commit also cleansup imports on existing files.
> feat(build.sh): Enable goimports + cleanup imports in source files

- docs/cmd/kn_revision.md
- docs/cmd/kn_revision_delete.md
- hack/generate-docs.go
- pkg/kn/commands/revision/delete.go
- pkg/kn/commands/revision/delete_test.go
- pkg/kn/commands/revision/revision.go
- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/wait_args.go
- pkg/kn/commands/test_helper.go
- pkg/kn/commands/wait_flags.go
- pkg/kn/commands/wait_flags_test.go
- pkg/wait/wait_for_ready.go
- test/e2e/revision_workflow_test.go
Fixes #203 
```
➜  client git:(fix-203)  ./kn revision list
SERVICE   NAME          AGE     CONDITIONS   READY     REASON
hello     hello-2krsg   4s      1 OK / 5     Unknown   Deploying
hello     hello-7w8z7   47m     4 OK / 5     True      
kn1       kn1-kcwt7     9m23s   4 OK / 5     True      
svc1      svc1-j7hqr    23h     4 OK / 5     True      
➜  client git:(fix-203)  ./kn revision delete hello-7w8z7
Revision 'hello-7w8z7' successfully deleted in namespace 'default'.
➜  client git:(fix-203)  ./kn revision list              
SERVICE   NAME          AGE     CONDITIONS   READY   REASON
hello     hello-2krsg   16s     5 OK / 5     True    
kn1       kn1-kcwt7     9m35s   4 OK / 5     True    
svc1      svc1-j7hqr    23h     4 OK / 5     True    
```
> Add kn revision delete command

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/service_update.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- test/e2e/basic_workflow_test.go
Issue: https://github.com/knative/client/issues/142
Description:
When someone writes application which listens on port other than 8080(default port in knative-serving) then deploy using **cli(kn)** then there is no way to specify the port.
**Current:** 
Supported flags are
```
Flags:
--concurrency-limit int    Hard Limit of concurrent requests to be processed by a single replica.
--concurrency-target int   Recommendation for when to scale up based on the concurrent number of incoming request. Defaults to --concurrency-limit when given.
-e, --env stringArray          Environment variable to set. NAME=value; you may provide this flag any number of times to set multiple environment variables.
--force                    Create service forcefully, replaces existing service if any.
-h, --help …
```
> Added changes to support container port information while creating/updating service

- test/e2e-tests.sh
- test/presubmit-integration-tests-latest-release.sh
- test/presubmit-tests.sh
This PR adds an environment variable $KNATIVE_VERSION for both e2e-tests.sh and presubmit-tests.sh, in order to specify the version of Knative serving to be installed.
Closes: #168
> Add the support to test against specified release of Knative serving

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
Erroneously showed ‘CPU’ for ‘memory’ in description strings
> Fixes `limits-memory` and `requests-memory` descriptions

- test/e2e-smoke-tests.sh
Removes time.Sleep as by default service create waits for it to
become ready. Also adds a command to create service in --async mode.
Update:
Checks if service created in async mode is ready,
also describes the async mode service and finally deletes it.
> Removes pausing between e2e smoke tests

- docs/cmd/kn.md
- docs/cmd/kn_route.md
- docs/cmd/kn_route_list.md
- pkg/kn/commands/route/human_readable_flags.go
- pkg/kn/commands/route/list.go
- pkg/kn/commands/route/list_flags.go
- pkg/kn/commands/route/list_flags_test.go
- pkg/kn/commands/route/list_test.go
- pkg/kn/commands/route/route.go
- pkg/kn/core/root.go
- test/e2e-smoke-tests.sh
- test/e2e/basic_workflow_test.go
- vendor/modules.txt
Fixes #201 
Example:
```
kn route list
NAME    URL                                     AGE   CONDITIONS   TRAFFIC
hello   http://hello.default.apps-crc.testing   13m   1 OK / 3     100% -> hello-7w8z7
kn1     http://kn1.default.apps-crc.testing     22h   3 OK / 3     100% -> kn1-pf6jr
rt1     http://rt1.default.apps-crc.testing     22h   3 OK / 3     20% -> svc1-j7hqr, 80% -> svc1-j7hqr
```
Help section
```
kn route list --help           
List available routes.
Usage:
kn route list NAME [flags]
Examples:
kn route list
kn route list web -n dev
kn route list -o yaml
Flags:
--all-namespaces                If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even if specified with --namespace.
--allow-missing-template-keys   If true, ignore …
```
> Add kn route list command

- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/service_create_test.go
Now a more meaningful error is returned when the user tries to create
a service that already exists. Until know the service is tried
to be created even if the client already knows that it exists.
Also some broken (broken in the sense that the test was nonsense) tests has been fixed.
> fix(serving): Fix logic 'service create --force' and some bogus tests

- docs/cmd/kn_revision.md
- docs/cmd/kn_service.md
- go.mod
- go.sum
- pkg/kn/core/root.go
- pkg/kn/core/root_test.go
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
- vendor/github.com/pkg/errors/.gitignore
- vendor/github.com/pkg/errors/.travis.yml
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/gotest.tools/LICENSE
- vendor/gotest.tools/assert/assert.go
- vendor/gotest.tools/assert/cmp/compare.go
- vendor/gotest.tools/assert/cmp/result.go
- vendor/gotest.tools/assert/result.go
- vendor/gotest.tools/internal/difflib/LICENSE
- vendor/gotest.tools/internal/difflib/difflib.go
- vendor/gotest.tools/internal/format/diff.go
- vendor/gotest.tools/internal/format/format.go
- vendor/gotest.tools/internal/source/defers.go
- vendor/gotest.tools/internal/source/source.go
- vendor/modules.txt
BFS exploration of all sub-commands from `rootCmd` and adds a `RunE` for all commands that are command groups with child sub-commands and without a `RunE`.
The added `RunE` will return the correct errors when the command is called with empty sub-command or with an unknown sub-command. It will also print the command help message first.
----
I did not add a test for this since the we need to decide on #185 and #214 and #134. Once we do I will add the gotest.tools or Ginkgo test for it.
> fix(core): generic solution for issue #111 for all command groups

- hack/release.sh
The argument to build_flags.sh must point to the basedirectory where
go.mod is located.
Fixes #212
> fix(release.sh): Point to proper directory to extract the serving version

- docs/cmd/kn_route.md
- pkg/kn/commands/compare_utils.go
- pkg/kn/commands/revision/delete_test.go
- pkg/kn/commands/revision/revision_list_test.go
- pkg/kn/commands/route/list_test.go
- pkg/kn/commands/service/service_list_test.go
- pkg/kn/commands/test_helper.go
- pkg/util/compare.go
- pkg/util/compare_test.go
- test/e2e/revision_workflow_test.go
- vendor/modules.txt
This changeset introduces custom comparison for checking if a target
string has given multiple substrings, namely `ContainsMultipleSubstrings`.
Also removes `commands.TestContains` function and replaces all references
of `commands.TestContains` with `gotest.tools/assert.Check` function and
uses `ContainsMultipleSubstrings` as comparison function.
> Add custom comparison for checking multiple substrings

- hack/build.sh
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
-  Adds step to simplify code along with goimports
-  Runs goimports on all packages except vendor dir and filter on only *.go files
-  Runs gofmt on all dirs except vendor and filters on *.go files, also writes the results instead of printing diff
- Fixes typo s/insteat/insead
- Adds the changes after adding simply code step in hack/build.sh
> Add gofmt simplify code option in hack/build.sh

- docs/cmd/kn.md
- pkg/kn/commands/service/service_create.go
- pkg/serving/v1alpha1/client.go
- pkg/serving/v1alpha1/client_test.go
- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
This puts all the console output to the command, where it belongs too.
One could add a ProgressHandler for more fine granular feedback (like suggested in #234) but for now this is not needed.
> refactor(service): Removed io.writer from of KnClient.WaitForService()

- docs/cmd/kn_revision_list.md
- docs/cmd/kn_service_list.md
- pkg/kn/commands/revision/revision_list.go
- pkg/kn/commands/revision/revision_list_test.go
- pkg/kn/commands/service/service_list.go
- pkg/kn/commands/service/service_list_test.go
https://github.com/knative/client/issues/143
**current:**
```
kn service list -n test autoscale-go
NAME           DOMAIN                          GENERATION   AGE    CONDITIONS   READY     REASON
autoscale-go   autoscale-go.test.example.com   1            125m   0 OK / 3     Unknown   RevisionMissing : Configuration "autoscale-go" is waiting for a Revision to become ready.
test1          test1.test.example.com          1            119m   0 OK / 3     False     RevisionMissing : Configuration "test1" does not have any ready Revision.
```
**Expected:** Should list only that perticular service.
something like below
```
kn service list -n test autoscale-go
NAME           DOMAIN                          GENERATION   AGE    CONDITIONS   READY     REASON
autoscale-go …
```
> get a particular service and revision based on name parameter

- CHANGELOG.adoc
- pkg/kn/commands/service/human_readable_flags.go
- pkg/kn/commands/service/service_list_test.go
Starting with 0.7.0 old fields are not populated anymore. Let's switch to the new fields then.
This fix should work with 0.6.0, too as the new fields already have been populated back then.
So we can unconditionally pick status.address.url which is accordance with
our policy to support the latest release and the release before.
Fixes #246.
> fix(service): Show URL (external) instead of Address (internal) when listing service

- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/service_update.go
Is related to #224 and should fix one flake.
> fix(service update): Retry an update in case of a conflict.

- docs/cmd/kn_service_create.md
- pkg/kn/commands/wait_flags.go
- test/e2e-smoke-tests.sh
* Increase wait timeout to 240s (to avoid test failures like in https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_client/244/pull-knative-client-integration-tests-latest-release/1148472118510358531/build-log.txt)
* Fixed duplicate default help message for `kn service create --help`
> chore(wait): Fixes for Smoke Tests + help messages

- docs/cmd/kn_route.md
- docs/cmd/kn_route_describe.md
- pkg/kn/commands/route/route.go
- pkg/kn/commands/route/route_describe.go
- pkg/kn/commands/route/route_describe_test.go
- pkg/serving/v1alpha1/client.go
- pkg/serving/v1alpha1/client_test.go
1, Implement kn route describe command with required parameters:
```
✔ $ go run cmd/kn/main.go route describe --help
Describe available route.
Usage:
kn route describe NAME [flags]
Flags:
--allow-missing-template-keys   If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats. (default true)
-h, --help                          help for describe
-n, --namespace string              List the requested object(s) in given namespace.
-o, --output string                 Output format. One of: json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file. (default "yaml")
--template string               Template string or path to template file to use when -o=go-template, …
```
> Fix issue #205 to add route describe feature and test

- pkg/kn/commands/completion.go
* Hide the presence of the `kn completion` command so that users mostly see the active command surface.
```release-note
`kn completion` is no longer suggested by `kn help`. The command still exists
to enable command-line completion, but it should not be advertised in normal
usage.
```
> Hide completion command from help.

- test/e2e/basic_workflow_test.go
- test/e2e/revision_workflow_test.go
- test/e2e/service_options_test.go
- test/e2e/version_test.go
This is a follow-up PR of #256 . We should use assert package (and utils) for testing the output string to keep consistency between unit and e2e tests.
> Clean up e2e test assertion

- pkg/kn/commands/namespaced.go
- pkg/kn/commands/types.go
- pkg/kn/commands/types_test.go
Fixed: #196 
```
./kn service list --kubeconfig=$KUBECONFIG
the server could not find the requested resource (get services.serving.knative.dev)
```
> Support multi config files

- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/service_create_test.go
- pkg/kn/commands/service/service_update_test.go
- pkg/serving/config_changes.go
- pkg/serving/revision_template.go
- pkg/serving/service.go
Previously, the method on client were named like `GetRevision` and these accessor methods were named like `GetRevisionTemplate`. 
I was writing some code that mixed both kinds of methods, and it was getting confusing. So this renames the accessors to look different, so I can tell what I'm doing when I'm writing code that uses both.
> Rename lemonade-aware accessors to be less like methods that get from the server

- conventions/cli.md
Mostly copied from  https://docs.google.com/document/d/1Or3f51EIrdyuwlJ9IfhQdoe7F7WrjsUPEPa0Ijsv2go/edit#
... updated a little, too.
Codifies CLI naming and structure conventions.
> Command conventions doc

- pkg/kn/commands/revision/revision_list_test.go
This showed up in the test run as single log message so removing it
> chore(revision): Remove unwanted log message in test

- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/revision_template.go
- pkg/serving/v1alpha1/client_test.go
- test/e2e/service_options_test.go
- vendor/modules.txt
I would like to do more contributions on knative/client but currently some large PRs are under reviewing. Therefore, I decided to read and refactor current code bases without bothering core contributors. If it's too much troubles, just let me know!
* Validate the scale and container concurrency options and returns error when invalid value is found.
* Add unit/e2e tests for handling invalid user inputs
* Use GetContainer method for extracting container spec from revision template
* Use constant values for annotation keys
* Add missing unit test for TestUpdateContainerImage method
```release-note
None
```
> Validate scale and container concurrency options when updating configuration resource

- conventions/client.md
This moves client_conventions.md from knative/serving/doc to here. After this is merged I expect to make a PR over in Serving to change that doc to a link back over here.
I also did a pass to account for bring-your-own revision names, as they're more convenient and to-the-point than nonces.
> Move client conventions doc from Serving

- test/e2e/basic_workflow_test.go
- test/e2e/revision_workflow_test.go
* service, revision, route describe and describe with print flags
* route list with print flags
* service create for a duplicate service
Fixes #
* increase test coverage via new E2E tests
```release-note
```
> Add E2E tests for Service, Revision, Route

- pkg/kn/commands/namespaced.go
When no current namespace is set in the config file, then using `kn` without -n fails:
```
invalid configuration: no configuration has been provided
```
Instead of failing in this case, assume the default namespace "namespace"
> fix: Fix error when no current namespace is set

- conventions/cli.md
Add documentation that boolean flags should be specified by flag presence. 
This is mutally exclusive with https://github.com/knative/client/pull/284 . 
Vote by thumbs up reaction emoji. Winner gets merged.
> Document boolean flags by presence

- test/e2e/basic_workflow_test.go
- test/e2e/common.go
- test/e2e/revision_test.go
- test/e2e/route_test.go
- test/e2e/service_options_test.go
- test/e2e/service_test.go
- test/e2e/version_test.go
* move out more tests from the basic workflow and put them in separate
files, including tests for routes
* rename revision_workflow_test.go to revision_test.go
Fixes #https://github.com/knative/client/issues/301
I've also excluded things related to routes from the basic workflow. IMO, it is not required to touch routes in the basic workflow. We get information about the route from "service describe". OTOH, I included `revision describe` in the basic workflow because I think that will be a common operation to get information about the given revision.
Moving test files into sub-folders such as revision, service, etc. is currently not possible with the current way we run tests. There are two problems:
1) When running `go test command` for all tests we'd have to list multiple/many directories …
> Restructure E2E test suite

- pkg/kn/commands/service/service_create_mock_test.go
- pkg/kn/commands/testing_helper.go
- pkg/serving/v1alpha1/client_mock.go
- pkg/serving/v1alpha1/client_mock_test.go
- pkg/wait/test_wait_helper.go
Commands must only use the `KnClient` API and their unit tests should also
only use a mock implementation for this interface.
This commit introduces such a Mock implementation and works like in
the example below for creating a simple service in a synchronous
way
```golang
// New mock client
client := knclient.NewMockKnClient(t)
// Recording:
r := client.Recorder()
// Check for existing service --> no
r.GetService("foo", nil, errors.NewNotFound(v1alpha1.Resource("service"), "foo"))
// Create service (don't validate given service --> "Any()" arg is allowed)
r.CreateService(knclient.Any(), nil)
// Wait for service to become ready
r.WaitForService("foo", knclient.Any(), nil)
// Get for showing the URL
r.GetService("foo", getServiceWithUrl("foo", "http://foo.example.com"), nil)
// Testing: …
```
> feature(testing): Introduce a mock implementation for KnClient

- pkg/kn/commands/service/service_update.go
- pkg/kn/commands/service/service_update_test.go
For now if no flag(s) set, service update will still try to do an update as below, it should return an error instead.
```
$ ./kn service update hello
Waiting for service 'hello' to become ready ... OK
Service 'hello' updated in namespace 'default'.
```
Fixes [issue 286](https://github.com/knative/client/issues/286)
* Return an error if no flag(s) set in service update
```release-note
```
> Report an error if no flag(s) set in service update

- pkg/kn/core/root.go
```bash
➜  client git:(issue309) ✗ ./kn lol
Manage your Knative building blocks:
* Serving: Manage your services and release new software to them.
* Eventing: Manage event subscriptions and channels. Connect up event sources.
Usage:
...
Use "kn [command] --help" for more information about a command.
unknown sub-command or plugin "lol" for "kn"
```
Fixes #309
* add better message if `kn` is called with unknown command or plugin
```release-note
NONE
```
> fix(bug) correct response for unknown command or plugin fixes(#309)

- test/e2e/common.go
> fix(test): Give the namespace some time setup to fix 'no serviceaccount default' flake

- CHANGELOG.adoc
- pkg/kn/commands/service/service_list.go
- pkg/kn/commands/service/service_list_test.go
Fixes #324 
* `kn service list` lists services sorted by alphabetical order.
> List services sorted by alphabetical order

- docs/cmd/kn_revision_list.md
- docs/cmd/kn_route_list.md
- docs/cmd/kn_service_list.md
- pkg/kn/commands/namespaced.go
- pkg/kn/commands/namespaced_test.go
-A is my newest favorite kubectl flag, it's so much easier/faster to type
than --all-namespaces. kn users should benefit from it too!
/lint
```release-note
The kubectl `-A` variant of the `--all-namespaces` flag is now supported.
```
> Add support for -A variant of --all-namespaces

- DEVELOPMENT.md
Fixes #353
As we require minimum 1.12.7 for building  kn
> docs: References golang 1.12.7 or later in docs

- pkg/kn/core/root.go
Fixed:
```
$ ./kn plugin list --lookup-plugins-in-path
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/knative/client/pkg/kn/core.extractKnPluginFlags(0xc00003c0c0, 0x4, 0x4, 0xc0002be280, 0xc000000180, 0xc0002ba180, 0xc0000de670, 0xc000117f68)
/root/go/src/knative.dev/client/pkg/kn/core/root.go:222 +0x666
github.com/knative/client/pkg/kn/core.NewDefaultKnCommand(0xc000000000)
/root/go/src/knative.dev/client/pkg/kn/core/root.go:46 +0x79
main.main()
/root/go/src/knative.dev/client/cmd/kn/main.go:33 +0x46
```
While in there I fixed it so that we only look for --flag at the start
of the arg, and handle the --flag, --flag=, and --flag=xxx cases.
If there's --flagX we skip it because it's some other flag and not one
of interest to us.
Also, fixed some error …
> Fix index out of range error

- pkg/kn/core/root.go
- pkg/kn/flags/bool.go
- pkg/kn/flags/bool_test.go
Adds a library to add and understand paired boolean flags in the format we agreed upon by voting. Uses it for `--log-http`, for now.
> Bool flags in the paired `--foo` and `--no-foo` format

- CHANGELOG.adoc
- cmd/kn/main.go
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/service_update_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/service.go
- pkg/serving/service_test.go
Fixes #277 #276 
* `--revision-name` flag allows setting revision names in service update. If you don't provide the service name as a prefix, it'll get auto-added for you.
* `--generate-revision-name` flag (default TRUE) makes revision names client side by default.
Whether to include the generation is up for discussion. Otherwise this is substantially similar to the server-side generateName(), up to and including our lack of vowels.
```release-note
```
> Specify names on service update and generate names client-side.

- CHANGELOG.adoc
- docs/cmd/kn_service_update.md
- pkg/kn/commands/flags/traffic.go
- pkg/kn/commands/service/service_update.go
- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e-tests.sh
- test/e2e/common.go
- test/e2e/env.go
- test/e2e/traffic_split_test.go
- vendor/modules.txt
Fix #210 
Introduced 3 flags for working with traffic: `--traffic`, `--tag`,  `--untag`.
Use `@latest` identifier to reference latest revision for `--traffic` and `--tag` flags.
Added first cut, please give it a try by building the client from this PR,
see if there are use cases you need and not covered here.
PR is WIP and requires following to be complete:
- ~~Add check to verify if given revision exists~~ (open https://github.com/knative/serving/issues/5094)
> feature(service): Implements traffic splitting and tagging targets

- pkg/kn/commands/plugin/plugin_verifier.go
- pkg/kn/commands/plugin/plugin_verifier_windows.go
Fixes #365
The code used for checking whether plugin is executable or not in plugin verifier
does not build for Windows. Builds Windows and non-Windows platform plugin verifier separately
> Portable plugin executable check for Windows platform

- pkg/kn/commands/service/service_create.go
- pkg/kn/commands/service/service_create_mock_test.go
- pkg/kn/commands/service/service_create_test.go
- pkg/kn/commands/service/service_test.go
This is the version of the pull request where we don't make a flag to determine whether we want to use the "old format" or the "new lemonadey v1beta1 format", we just create new services in the new format.
This will DROP SUPPORT for 0.5
We could also have a flag, but this PR is quicker and easier to make, so I'm making it and we can discuss.
> Always create in new format rather than old

- docs/README.md
Working on various plugins docs. This is first of three PRs.
Fixes #320 (partly)
* Small section to introduce plugins and refer to other docs
```release-note
Plugin documentation to README.md
```
> Add reference to plugin in README.md

- CHANGELOG.adoc
- pkg/kn/commands/version.go
- pkg/kn/commands/version_test.go
/lint
Fixes #369
- Replace `Dependencies:` with `Support:`
- Add list of supported Serving versions kn can work with
- Add list of supported Serving APIs kn can work with
```
✗ ./kn version
Version:      v20190816-local-e36089f-dirty
Build Date:   2019-08-16 13:08:26
Git Revision: e36089f
Support:
- Serving: v0.8.0  v0.7.1
- API(s):  v1alpha1
```
```release-note
kn version command shows supported Serving and API versions
```
> kn version command to list supported serving versions and APIs

- test/e2e/traffic_split_test.go
This is just a small change that should make a helper function in the tests reliably return the latest revision name even when traffic doesn't have anything set to latest. No change to the actual running of the tests.
> Fix json path to latest revision in e2e tests to something reliable

- pkg/errors/factory.go
Fixes nil pointer error in case `apiStatus.Status().Details` is `nil`.
* Adds a nil check of `apiStatus.Status().Details` in errors package
* Returns the original error if it is nil
```release-note
```
> check if status detail is nil

- pkg/util/logging_http_transport.go
- pkg/util/logging_http_transport_test.go
- vendor/modules.txt
Fixes #377
* Retain the request body when logging HTTP.
```release-note
--log-http now works for requests with a body.
```
> Retain the request body when logging HTTP.

- test/e2e-tests-local.sh
This allows us to pass `-run TestTrafficSplit` or whatever.
> Pass on args to e2e tests for local script

- hack/build.sh
* Use `./hack/build.sh -x` or `./hack/build.sh --build-cross`
* Doesn't touch any of the existing flow, providing these options will build binaries and exit
> Adds option in hack/build.sh to build cross platform binaries

- CHANGELOG.adoc
- pkg/kn/commands/human_readable_flags.go
- pkg/kn/commands/revision/human_readable_flags.go
- pkg/kn/commands/route/human_readable_flags.go
- pkg/kn/commands/service/human_readable_flags.go
- pkg/kn/commands/service/service_list.go
- pkg/kn/commands/service/service_list_flags.go
- pkg/kn/commands/service/service_list_mock_test.go
- pkg/kn/commands/service/service_list_test.go
- pkg/printers/interface.go
- pkg/printers/tableprinter.go
/lint
`kn service list` should print NAMESPACE column when specifying `--all-namespaces` option, which follows the [kubectl convention](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#output-conventions).
> NAMESPACE should be displayed as the first column when --all-namespaces is specified
I know we can find a namespace we deployed our service by inspecting an URL column. It tells us a namespace by default because its FQDN is composed of `{{.Name}}.{{.Namespace}}.{{.Domain}}`. However, we can easily change this FQDN template by modifying `domainTemplate` field in [config-network.yaml](https://github.com/knative/serving/blob/d37bd91a9355ea602819de1bf2a25fcf2294c06c/config/config-network.yaml#L116). In this case, we have no idea to see …
> feature(service list): Print NAMESPACE column as the first column when --all-namespaces is specified

- pkg/kn/commands/plugin/plugin_list.go
- pkg/kn/commands/plugin/plugin_list_test.go
- pkg/kn/commands/route/list.go
- pkg/kn/commands/route/list_test.go
- pkg/kn/commands/service/service_list.go
- pkg/kn/commands/service/service_list_test.go
- test/e2e/basic_workflow_test.go
For the sake of consistency with out own service commands and for kubectl,
`kn plugin list` should print:
```
No plugins found.
```
`kn service list` should print:
```
No services found.
```
and not `No resources found.` like it does now.
Same for `kn routes list`.
> chore(plugins, services, routes): Aligned "Not found" messages

- pkg/kn/commands/service/service_create.go
`namespace` arg is not used In `serviceExists`.
So I think that it should be removed.
```release-note
NONE
```
> Remove namespace from args

- docs/cmd/kn_revision_list.md
- docs/cmd/kn_route_list.md
- docs/cmd/kn_service_list.md
- pkg/kn/commands/human_readable_flags.go
- pkg/kn/commands/revision/revision_list_test.go
- pkg/kn/commands/route/list_test.go
- pkg/kn/commands/service/service_list_flags.go
- pkg/kn/commands/service/service_list_test.go
- pkg/printers/interface.go
- pkg/printers/tableprinter.go
- pkg/util/compare.go
- pkg/util/compare_test.go
Adds support for a "--no-headers" flag for resource listing commands that prints the default table output with column headers removed
Fixes #233 
```
--no-headers flag for resource listing
```
> feature: --no-headers flag for resource listing

- CHANGELOG.adoc
- docs/traffic_splitting.md
* Adds Reference doc for traffic splitting operations via `kn service update` single entry point
* Defines the operation precedence of the flags involved
* Adds multiple examples with different combinations of operations
Following table shows quick summary for traffic splitting flags, their value formats, operation to perform and *Repetition* column denotes if repeating the particular value of flag is allowed in a `kn service update` command.
Flag | Value(s) | Operation | Repetition
:--- | :---: | :--- | :---:
`--traffic` | `RevisionName=Percent` | Give `Percent` traffic to `RevisionName` | :heavy_check_mark:
`--traffic` | `Tag=Percent` | Give `Percent` traffic to the Revision having `Tag` | :heavy_check_mark:
`--traffic` | `@latest=Percent` | Give `Percent` traffic to the latest ready …
> docs: Adds documentation for traffic splitting support in kn

- pkg/kn/commands/route/list_flags_test.go
- pkg/kn/commands/service/service_delete_test.go
- pkg/kn/commands/service/service_list_flags_test.go
To get the test pass for https://github.com/knative/client/pull/245,
need to fill up test cases for files with low code coverage
Fixes #
test failure in https://github.com/knative/client/pull/245
* Added test cases
```release-note
```
> Fill up test cases for files with low code coverage

- .github/pull-request-template.md
We often ask the contributors to update CHANGELOG.adoc manually in PR comment, but shouldn't we write up the instruction in PR template?
* Remove unused release note section in PR template and add instruction for updating CHANGELOG.
Related to #176
> chore(template): Update release note section in PR template

- pkg/serving/config_changes.go
- vendor/modules.txt
This is a follow up PR of #389.
* Insert updated env vars into [sets.String](https://godoc.org/k8s.io/apimachinery/pkg/util/sets#String) and use it for selecting which items are appended to the original slice of env vars.
/lint
> chore (service): Use sets utility for holding updated env vars

- pkg/kn/commands/plugin/handler.go
- pkg/kn/commands/plugin/list.go
- pkg/kn/commands/revision/list.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/list.go
- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/service_test.go
- pkg/kn/commands/testing_helper.go
- pkg/kn/commands/types.go
- pkg/serving/v1alpha1/client.go
- pkg/serving/v1alpha1/client_test.go
- pkg/util/schema_handling.go
- pkg/util/schema_handling_test.go
- vendor/modules.txt
This is in preparation of introducting eventing and makes sense anyway.
Also, the GVK update handling has been moved to "util" so that it then
can be also reused by eventing.
> refactor(knclient): Moved KnClient -> KnServingClient

- docs/cmd/kn_revision_delete.md
- docs/cmd/kn_revision_describe.md
- docs/cmd/kn_revision_list.md
- docs/cmd/kn_route_describe.md
- docs/cmd/kn_route_list.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_delete.md
- docs/cmd/kn_service_describe.md
- docs/cmd/kn_service_list.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/namespaced.go
- pkg/kn/commands/plugin/handler.go
- pkg/kn/commands/plugin/list.go
Fixes #418
* Change the description of flag `namespace` because it will serve for other actions besides `list`, e.g. create, update and etc.
> Update the description of flag namespace

- docs/cmd/kn.md
- docs/cmd/kn_plugin.md
- docs/cmd/kn_plugin_list.md
- pkg/kn/commands/plugin/list.go
- pkg/kn/commands/plugin/list_test.go
- pkg/kn/commands/plugin/plugin.go
- pkg/kn/commands/plugin/plugin_test.go
- pkg/kn/commands/testing_helper.go
- pkg/kn/commands/types.go
- pkg/kn/core/root_test.go
Fixes #414
* adopts a new format for config keys and thereby bypassing the need for case sensitivity in Viper
* changed `lookupPluginsInPath` key to `lookup-plugins` and also same for the persistent flag. The PATH part is implied and can be read from help.
Release Note:
- 🧽 cleans up config keys to match persistent flags
> fixes(#414): change plugins config keys to use - instead of camel case

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/service_update_mock_test.go
- pkg/kn/commands/service/update.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- test/e2e/service_options_test.go
Fixes #327 
- Adds specified annotations to service object meta and revision template meta
- Adds `--annotation` / `-a` flag to service create and update options
- User can specify '-' at the end of the annotation key to remove an annotation
- Adds unit and e2e tests
- Updates docs accordingly
/lint
> feat(annotations): Adds annotation flag for service create and update

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/list_mock_test.go
- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/commands/testing_helper.go
- pkg/serving/v1alpha1/client.go
- pkg/serving/v1alpha1/client_mock.go
- pkg/serving/v1alpha1/client_mock_test.go
- pkg/serving/v1alpha1/client_test.go
- pkg/wait/test_wait_helper.go
- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
- test/e2e/basic_workflow_test.go
- test/e2e/service_options_test.go
- test/e2e/traffic_split_test.go
* Increased default timeout to 600s. This timeout will be triggered
only when the Ready condition stays in UNKNOWN for that long. If its
True or False then the command will return anyway sooner.
So it makes sense to go for a much longer timeout than 60s
* Enhanced output to indicate the progress
This change needs some updates to the API and introduces a 'MessageCallback'
type which is calle for each intermediate event with the "Ready" condition message.
Example of the UX:
[![asciicast](https://asciinema.org/a/5MwD9j3HJpLdBgosJFbFsDBdB.svg)](https://asciinema.org/a/5MwD9j3HJpLdBgosJFbFsDBdB)
> chore(service): Improvements for waiting on service readiness

- go.mod
- go.sum
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/modules.txt
As per title, just to make sure we're not vulnerable to CVE-2019-11253.
See kubernetes/kubernetes#83253.
> Updates YAML transitive dependency to v2.2.4

- .gitignore
- hack/verify-codegen.sh
* `build.sh` accepts `-c` option for code generation, not `-u`.
* Add `.DS_Store` to `.gitignore`
> Fix a small error in verify-codegen.sh

- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/wait_flags.go
Also, added accidentally removed seperator lines during create/update
> fix(service): Set default timeout for update to the same value as for create

- test/e2e/traffic_split_test.go
Fixes #434
/lint
- The error message now prints the expected/actual length of traffic targets
- Also prints the actual traffic targets
> fix(e2e): Improves the error message upon mismatch of traffic targets

- hack/build-flags.sh
- pkg/kn/commands/version/version.go
- pkg/kn/commands/version/version_test.go
- pkg/kn/core/root.go
- test/e2e/traffic_split_test.go
Fixes #404
/lint
- Add the API versions and component version vendored
- Moves the version command under its package version
-  Removes ServingVersion feeding from ldflags
```
./kn version
Version:      v20191017-local-6328a73-dirty
Build Date:   2019-10-17 09:55:55
Git Revision: 6328a73
Supported APIs:
- serving.knative.dev/v1alpha1 (knative-serving v0.8.0)
```
> fix(version): Displays supported APIs and version

- pkg/kn/commands/route/human_readable_flags.go
- pkg/kn/commands/route/list_test.go
- test/e2e/route_test.go
Fixes #
[issue 350](https://github.com/knative/client/issues/350)
* Show tag for revisionName if any 
* Make the traffic column shorter
With this PR, output of route list will be
```
$ ./kn route list
NAME          URL                                                                                AGE    CONDITIONS   TRAFFIC
gracecanary   http://gracecanary.default.zhanggbj-knative.us-south.containers.appdomain.cloud   5d1h   3 OK / 3     (current)gracecanary-blue=90, gracecanary-green=10
helloworld    http://helloworld.default.zhanggbj-knative.us-south.containers.appdomain.cloud    27d    3 OK / 3     (old)helloworld-kp2pk=50, (new)helloworld-fw5zj=50
```
```release-note
```
> Refine route list output

- pkg/kn/commands/completion.go
- pkg/kn/commands/completion_test.go
Fixes #426
* removes zsh completion as it the code it generates does not work
- 🧽 Update or clean up current behaviour
> removes zsh completion since it does not work (fixes #426)

- pkg/kn/commands/service/human_readable_flags.go
- pkg/kn/commands/service/list_mock_test.go
- pkg/kn/commands/service/list_test.go
Fixes #360
* Add revision `LATESTCREATED` and `LATESTREADY` to the output of `kn service list`
* Remove `Generation` from the output of `kn service list`
> Add revision information to service list

- pkg/kn/commands/describe.go
- pkg/kn/commands/describe_test.go
- pkg/kn/commands/service/describe.go
- pkg/printers/prefixwriter.go
- pkg/printers/prefixwriter_test.go
This is the first PR in a chain that will implement revision describe. It moves a lot of logic that wants to be shared by describe commands into:
* The printer, to keep track of indentation level and columns (so it needn't be done statically), and write attributes
* A new file in the shared commands package, which has useful methods to write metadata and do some other Kn-specific formatting.
> Refactor describe: printing levels and shared kn code

- pkg/kn/commands/plugin/verifier.go
- pkg/kn/commands/plugin/verifier_windows.go
Fixes an English typo
* changes plugins code WARNING message "... a equally" to "... an equally"
> fix English typo: 'an equally' instead of 'a equally'

- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
Fixes #413 
* Add service account info to `service describe` if present.
Release Note:
- 🧽 Add service account info to `service describe` if present.
> Add service account info into service describe

- docs/cmd/kn_revision_describe.md
- pkg/kn/commands/describe.go
- pkg/kn/commands/describe_test.go
- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/revision/describe_test.go
- pkg/kn/commands/service/describe.go
- pkg/printers/prefixwriter.go
- pkg/serving/revision_template.go
- pkg/serving/revision_template_test.go
- test/e2e/basic_workflow_test.go
- vendor/modules.txt
Revision describe based on new format for service describe. 
Non-verbose:
```
$ ./kn revision describe bar-bhndh-34 
Name:         bar-bhndh-34
Namespace:    default
Annotations:  autoscaling.knative.dev/target=-1
Age:          32d
Image:        gcr.io/knative-samples/helloworld-nodejs:latest (pinned to ae8c74)
Env:          ASDF=tame, BAZ=quux
Concurrency:  
Limit:      1
Target:     -1
CPU:          400m
Service:      bar
Conditions:  
OK TYPE                  AGE REASON
++ Ready                 32d 
++ BuildSucceeded        32d 
++ ContainerHealthy      32d 
++ ResourcesAvailable    32d 
I Active                32d NoTraffic
```
Verbose (note the extra info about service):
```
$ ./kn revision describe bar-bhndh-34 -v
Name:              bar-bhndh-34
Namespace:         default
Labels: …
```
> Human-readable revision describe

- pkg/kn/commands/service/configuration_edit_flags.go
While testing I specified this on the `kn` command line:
```
./kn service create echo --concurrency-limit=1 --concurrency-target=1 --env foo=bar --limits-cpu=1000m --limits-memory=1024m --max-scale=1 --min-scale=1 --port=9999 --requests-cpu=250m --requests-memory=64mi --image duglin/echo
```
and it returned:
```
unable to parse quantity's suffix
```
I had no idea which value it didn't like. So this PR makes it so the output
is now this:
```
Error parsing "64mi": unable to parse quantity's suffix
```
Still not perfect since I still had to think way too hard to realize that it
didn't like the lower-case `m`, but that's a different issue.
/lint
> Improve error message

- pkg/kn/commands/plugin/handler_test.go
- pkg/kn/commands/plugin/plugin.go
- pkg/kn/core/root.go
Removes remaining references to 'lookup-plugins-in-path' which is now renamed to the simpler 'lookup-plugins'
* change references of 'lookup-plugins-in-path' to 'lookup-plugins' (new name for flag)
> removes remaining references to 'lookup-plugins-in-path'

- docs/cmd/kn.md
- docs/cmd/kn_completion.md
- pkg/kn/commands/completion/completion.go
> Add completion to help message

- hack/build.sh
- `./hack/build.sh` performs usual flow of codegen, build and test
- `./hack/build.sh -x` only compiles cross platform
> Separates cross compile in hack/build.sh from default flow

- CHANGELOG.adoc
- pkg/kn/commands/service/delete.go
- pkg/kn/commands/service/delete_test.go
- test/e2e/service_test.go
Partially address #317
* Support multiple NAMEs on `kn service delete`
Release Note:
In the following cases, add a short description of PR to the unreleased section in CHANGELOG.adoc:
- 🧽 Support multiple NAMEs on `kn service delete`
> Support multiple NAMEs on service delete

- test/e2e/traffic_split_test.go
Fixes #500 
* Uses BYO revision names for traffic splitting e2e tests
* Avoid getting the revision name after service create/update using LCR or LRR from service status
* Pauses 3 seconds before verifying actual vs expected traffic targets ( Check the comment on https://github.com/knative/client/issues/500#issuecomment-554355688)
/lint
> Uses BYO revision names for traffic splitting e2e tests

- pkg/util/logging_http_transport.go
- pkg/util/logging_http_transport_test.go
Fixes #391
* display `--log-http` Authorization as `********`
> Shorten the --log-http Authorization mask value

- pkg/kn/commands/version/version.go
- pkg/kn/commands/version/version_test.go
Adding sources.eventing.knative.dev to version info (the only eventing API)
for now as this will be the first one used.
> chore: Add version information of eventing

- test/e2e/traffic_split_test.go
- Verify service status LCR=LCR before verifying traffic targets
- Retry 5 times with 2 seconds delay, else fail the tests
> Verify service status before verifying traffic targets

- test/e2e/traffic_split_test.go
Related to #500
/lint
- The fix for serving#6060 merged (serving#6069), removing the workaround
at client side e2e tests for additional LCR=LRR check after service update return.
- Now we expect service status to have LCR=LRR if the service's conditions turned True after last update.
> fix(e2e): Removes workaround for ensuring LCR=LRR at client side

- test/presubmit-tests.sh
- Uses custom `unit_tests` function in presubmit-tests.sh to run unit tests
- Custom function adds a flag `-mod=vendor` in addition to default unit tests runner
- The deps are already downloaded part of the source repo, mentioned flag uses it (vendor dir)
and avoids downloading the deps afresh
- This prevents(in unit tests) the flake we see 'go: error loading module requirements' which occurs
due to download error
> tests: Avoid downloading deps in unit tests

- test/e2e-smoke-tests.sh
Fixes #507
- removes `--wait-timeout` flag, was set to 240 seconds which is lesser than the default timeout (600 seconds)
- removes duplication of namespace flag in another smoke test command
> fix(e2e): Removes explicit timeout flag in smoke tests

- go.mod
- go.sum
- test/e2e-common.sh
- test/e2e-smoke-tests.sh
- test/e2e-tests.sh
- test/presubmit-integration-tests-latest-release.sh
- test/presubmit-tests.sh
- vendor/knative.dev/test-infra/scripts/library.sh
- vendor/modules.txt
- Update test-infra
- Use library functions for setting up released and latest Eventing
- Set up Eventing 0.10.2 and nightly release in `latest-release` and default e2e tests CI job respectively
> Eventing setup in CI

- test/e2e/e2e_flags.go
Fixes https://github.com/knative/test-infra/issues/1568
The `--emit-metrics` can be safely removed now as the relevant job has been deprecated.
/cc @adrcunha 
/cc @chaodaiG
> Remove unused emit-metrics flag for e2e tests

- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
- test/e2e/basic_workflow_test.go
Fixes #482 
* Show cluster url only in verbose request in service describe command
> service describe command : Move Cluster URL to --verbose from default output

- docs/cmd/kn.md
- docs/cmd/kn_source.md
- docs/cmd/kn_source_apiserver.md
- docs/cmd/kn_source_apiserver_create.md
- docs/cmd/kn_source_apiserver_delete.md
- pkg/eventing/sources/v1alpha1/client.go
- pkg/eventing/sources/v1alpha1/client_test.go
- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/source/apiserver/apiserver.go
- pkg/kn/commands/source/apiserver/create.go
- pkg/kn/commands/source/apiserver/create_flag.go
- pkg/kn/commands/source/apiserver/create_flag_test.go
- pkg/kn/commands/source/apiserver/create_test.go
- pkg/kn/commands/source/apiserver/delete.go
- pkg/kn/commands/source/apiserver/delete_test.go
- pkg/kn/commands/source/source.go
- pkg/kn/commands/testing_helper.go
- pkg/kn/core/root.go
- vendor/modules.txt
This is a second builtin-typed source as described in [specification](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.d382ob8kwx0f), in addition to the cron-job source ib #357  
Partially address #499
* Add command to create ApiServerSource
* Add command delete ApiServerSource
> kn source apiserver create/delete  (as typed-builtin source)

- test/e2e-tests-local.sh
- test/e2e/basic_workflow_test.go
- test/e2e/revision_test.go
- test/e2e/route_test.go
- test/e2e/service_options_test.go
- test/e2e/service_test.go
- test/e2e/source_list_types_test.go
- test/e2e/traffic_split_test.go
- Run only serving specific e2e tests locally
```
E2E_TAGS="serving" ./test/e2e-tests-local.sh
```
- Run only eventing specific e2e tests locally
```
E2E_TAGS="eventing" ./test/e2e-tests-local.sh
```
- Run all e2e tests locally
```
./test/e2e-tests-local.sh
```
> Selectively run e2e tests for serving, eventing

- DEVELOPMENT.md
- test/README.md
Fixes #554 
* Add Readme file for tests
* Steps include, how to unit test and e2e locally
> Add readme for tests (#554)

- docs/cmd/kn_trigger.md
- docs/cmd/kn_trigger_update.md
- pkg/eventing/v1alpha1/client.go
- pkg/eventing/v1alpha1/client_mock.go
- pkg/eventing/v1alpha1/client_mock_test.go
- pkg/eventing/v1alpha1/client_test.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/create_test.go
- pkg/kn/commands/trigger/trigger.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/commands/trigger/update_flags.go
- pkg/kn/commands/trigger/update_flags_test.go
- pkg/kn/commands/trigger/update_test.go
> Add trigger update command

- docs/cmd/kn_source_apiserver.md
- docs/cmd/kn_source_apiserver_create.md
- docs/cmd/kn_source_apiserver_list.md
- docs/cmd/kn_source_apiserver_update.md
- docs/cmd/kn_source_cronjob.md
- docs/cmd/kn_source_cronjob_list.md
- pkg/eventing/sources/v1alpha1/apiserver_client.go
- pkg/eventing/sources/v1alpha1/apiserver_client_mock.go
- pkg/eventing/sources/v1alpha1/apiserver_client_test.go
- pkg/eventing/sources/v1alpha1/cronjob_client.go
- pkg/eventing/sources/v1alpha1/cronjob_client_mock.go
- pkg/eventing/sources/v1alpha1/cronjob_client_test.go
- pkg/kn/commands/source/apiserver/apiserver.go
- pkg/kn/commands/source/apiserver/flags.go
- pkg/kn/commands/source/apiserver/list.go
- pkg/kn/commands/source/apiserver/list_test.go
- pkg/kn/commands/source/cronjob/cronjob.go
- pkg/kn/commands/source/cronjob/flags.go
- pkg/kn/commands/source/cronjob/list.go
- pkg/kn/commands/source/cronjob/list_test.go
/lint
```
kn source cronjob list
NAME              SCHEDULE      SINK        CONDITIONS   READY   REASON
my-cron-trigger   * * * * */1   svc:mysvc   6 OK / 6     True    
```
> Add cronjob and apiserver source list commands

- pkg/kn/commands/trigger/update_flags.go
- pkg/kn/commands/trigger/update_flags_test.go
Fixes #569
*Return error if user set duplicate key in `--filter` option. For example, `kn trigger create --filter type=bla --filter type=blub test`.
> Retrurn error if exist duplicate key in filter option

- pkg/dynamic/client.go
- pkg/dynamic/client_test.go
- pkg/dynamic/fake/fake.go
- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/flags/sink_test.go
- pkg/kn/commands/source/apiserver/apiserver_test.go
- pkg/kn/commands/source/apiserver/create.go
- pkg/kn/commands/source/apiserver/create_test.go
- pkg/kn/commands/source/apiserver/update.go
- pkg/kn/commands/source/apiserver/update_test.go
- pkg/kn/commands/source/cronjob/create.go
- pkg/kn/commands/source/cronjob/create_test.go
- pkg/kn/commands/source/cronjob/cronjob_test.go
- pkg/kn/commands/source/cronjob/update.go
- pkg/kn/commands/source/cronjob/update_test.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/create_test.go
- pkg/kn/commands/trigger/list_test.go
- pkg/kn/commands/trigger/trigger_test.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/commands/trigger/update_test.go
Refactors sink code to use a dynamic client to validate the sink, so we don't keep having to write the same parallel code. Paves the way for arbitrary user-configured sinks.
Fixes #570 
Also fixes most of #563 : missing arbitrary ns for sinks, but now has the sink as being in the same ns as the object being created.
> Allow for http and broker sinks

- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/trigger/update_flags.go
- pkg/kn/commands/trigger/update_flags_test.go
- pkg/util/parsing_helper.go
- pkg/util/parsing_helper_test.go
From the description of #577:
The behaviour should be (using --env as an example):
--env a1=b1 --env a2=b2 should add both env variables
--env a1 should set a1 to empty string
--env a1- should remove the environment variable for update and an error for create
--env a1=b1 --env a1=b2 should be an error as the same key can not be specified on the same command line
Implements all the cases mentioned in #577, except one being discussed.
> Handle map-like options consistently

- test/e2e/common.go
- test/e2e/source_apiserver_test.go
- test/e2e/tekton_test.go
Fixes #576
* Delete k8s cluster resource: `clusterrole`, `clusterrolebinding` after e2e test finish.
> Delete k8s cluster resource in e2e test

- test/e2e/common.go
- test/e2e/cronjob_test.go
Related to #566
* Add e2e test for CronJob source.
> Add E2E tests for CronJob source

- test/e2e/tekton_test.go
* tear down only if the test passes, we want to keep the pods otherwise
so that the dump will show their errors
Currently, the teardown happens twice and the tests fail because the second teardown cannot find the namespace.
Fixes #
*
*
*
> Remove redundant cleanup in Tekton tests

- test/e2e/common.go
- test/e2e/plugins_test.go
Fixes #308
* adds `test/e2e/plugins_test.go`
* adds a new option to `e2eTest` to prevent namespace creation (since some test might not need ns)
Release Note:
- 🧽 backfill e2e tests for plugins
> fixes(#308): adds e2e tests for plugins

- test/e2e/tekton_test.go
- test/resources/tekton/buildah.yaml
- test/resources/tekton/kn-pipeline-run.yaml
- test/resources/tekton/kn-pipeline.yaml
- test/tekton-tests.sh
- test/test_images/helloworld/Dockerfile
- test/test_images/helloworld/go.mod
- test/test_images/helloworld/helloworld.go
Fixes #601
- Update tektoncd/pipeline setup to version to 0.9.2 for tekton e2e tests
- Also replace deprecated `serviceAccount` with `serviceAccountName`
- Sync helloworld test image code from https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-go
- Use local version of buildah task instead of one from catalog, adding `--format=docker` in `buildah bud` command
- to build and push the image to registry in docker format to match the manifestype `application/vnd.docker.distribution.manifest.v2+json`
- Update pipeline to add parameter BUILDER_IMAGE and sets it to quay.io/buildah/stable:latest
> chore(e2e): Update tektoncd pipeline release to v0.9.2

- pkg/kn/commands/revision/human_readable_flags.go
- pkg/kn/commands/revision/list.go
- pkg/kn/commands/revision/list_flags.go
- pkg/kn/commands/revision/list_test.go
Fixes #580
* adds traffic information of revision as an annotation in revision list
* adds tags information of revision as an annotation in revision list
* show traffic and tags when listing revisions
With this change, invocation of `kn revision list` will look like:
```bash
➜  client git:(issue580) ✗ ./kn revision list
Using kn config file: /Users/maximilien/.kn/config.yaml
NAME                  SERVICE       GENERATION   AGE   CONDITIONS   READY   TRAFFIC   TAGS    REASON
twitter-fn-ycybl-1    twitter-fn    26           28d   3 OK / 4     True    100%
summary-fn-hwkll-31   summary-fn    20           23d   3 OK / 4     True    50%       async
summary-fn-qwfdb-1    summary-fn    19           23d   3 OK / 4     True    50%       sync
watson-fn-wxpyf-15    watson-fn     15           28d   3 …
```
> feature(#580): adds traffic and tags information to revision list

- test/e2e/source_apiserver_test.go
Completes #576
- For ApiServer source: ClusteRole and ClusterRoleBinding name(s)
are now test-namespace specific. They are cleared in test's tearDown method.
- Use constant prefix as:
clusterRolePrefix        = "apiserver-role-"
clusterRoleBindingPrefix = "apiserver-binding-"
- Use constant ServiceAccountName as:
testServiceAccount = "apiserver-sa"
- Rename methods and cleanup.
/lint
> chore(e2e): Namespace specific k8s resources for tests

- pkg/kn/commands/service/service.go
Fixes #586
* splits final service update to user to make clear what changed and what has not
```bash
➜  client git:(master) ✗ ./kn service update summary-fn --untag sync1
Using kn config file: /Users/maximilien/.kn/config.yaml
Updating Service 'summary-fn' in namespace 'default':
0.089s Ready to serve.
Service 'summary-fn' with latest revision 'summary-fn-nxqwb-41' (unchanged) is available at URL:
http://summary-fn-default.kndemo-267179.sjc03.containers.appdomain.cloud
```
This is a case when service is updated with tags and revision remained unchanged.
```bash
➜  client git:(master) ✗ ./kn service update summary-fn --image docker.io/drmax/summary-fn:latest
Using kn config file: /Users/maximilien/.kn/config.yaml
Updating Service 'summary-fn' in namespace 'default':
0.091s The …
```
> fixes(#586): simplifies service update message to user

- docs/cmd/kn_trigger_create.md
- docs/cmd/kn_trigger_update.md
- pkg/eventing/v1alpha1/client.go
- pkg/eventing/v1alpha1/client_test.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/create_test.go
- pkg/kn/commands/trigger/trigger_test.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/commands/trigger/update_flags.go
- pkg/kn/commands/trigger/update_flags_test.go
- pkg/util/parsing_helper.go
- pkg/util/parsing_helper_test.go
* Make trigger filter to be optional
* Handle filter flag in a same way as other string array flags
* use Builder to create a trigger in the creation command
> Enable trigger filter to be optional

- cmd/kn/main.go
Fixes #612
* Remove printing err when running `kn` root command
`Fix subcommand is required error from showing when running kn by itself`
> Remove Printing Err When Running Root Command

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/revision_template.go
- test/e2e/service_options_test.go
> feature(serving): Add --autoscale-window

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
Fixes #616
- Add --pull-secret flag for service create/update operations
- Setting empty string to flag clears the pull secrets
- List `Image Pull Secret` in `service describe` default output
/lint
> Add --pull-secret flag

- CHANGELOG.adoc
- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/revision/describe_test.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
Fixes #626
* Show envFrom when running describe revison. The result like:
`EnvFrom:    ConfigMap:(testConfig), Secret:(testSecret)`
Release Note:
- 🐛 Fix bug #626 by showing envFrom when running describe revision.
> Show envFrom when running describe service or revision

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
Fixes #604 
* Add new flags `--cmd` and `--arg` 
* `--cmd` accepts a single `string` input
* `--arg` can be used multiple times to provide as many as neeed
* Examples:
* --cmd /app/start
* --cmd /app/start --arg myArg
* --arg myArg1 --arg --myArg2 --arg myArg3=3.
Even though `podSpec.Command` accepts `stringArray` and arguments can be passed directly to this field. Per discussion on #604  I've decided to follow more verbose and strict approach to make a clear distinction to improve usability and user-exp.
/assign @rhuss 
/assign @navidshaikh
> Add support for command and args in service create

- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
A default error window of 2 seconds (not sure if this should be made configurable
as it is hard to explain/document) cause return an error during
sync operations only, if a ReadyCondition == false stays for that
long in false. This is needed to compensate situation where the
condition is false when a race between revision and route creation
occurse during a service creation.
This should fix the flakes we have in our E2E tests as described in #544.
> fix(serving): Add an error window for ReadyCondition

- CHANGELOG.adoc
- docs/cmd/kn_source_binding_create.md
- pkg/kn/commands/source/binding/create.go
- test/e2e/source_binding_test.go
Fixes #631
* Add E2E test for "kn source binding" commands.
* Fix typo.
Release Note:
- 🎁 Add new feature
Add E2E test for "kn source binding" commands.
> Add E2E test for "kn source binding" commands

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/service_update_mock_test.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/commands/wait_flags.go
- pkg/kn/commands/wait_flags_test.go
- test/e2e-smoke-tests.sh
Fixes #438
* Add `--no-wait` flag with same behaviour as `--async`
* Mark `--async` as deprecated in documentation and display warning message when used
Example of deprecation warning:
```bash
➜  client git:(issue-438) kn service create svc-test --image gcr.io/knative-samples/helloworld-go --async  
DEPRECATED WARNING: flag --async is going to be removed in future release, please use --no-wait instead.
Service 'svc-test' created in namespace 'default'.
➜  client git:(issue-438) kn service update svc-test --image gcr.io/knative-samples/helloworld-go --async
DEPRECATED WARNING: flag --async is going to be removed in future release, please use --no-wait instead.
Service 'svc-test' updated in namespace 'default'.
➜  client git:(issue-438) kn service update svc-test --image …
```
> Rename --async to --no-wait and deprecate it

- CHANGELOG.adoc
- docs/cmd/kn_revision.md
- docs/cmd/kn_revision_describe.md
- docs/cmd/kn_route.md
- docs/cmd/kn_route_describe.md
- docs/cmd/kn_service.md
- docs/cmd/kn_service_describe.md
- docs/cmd/kn_source_apiserver.md
- docs/cmd/kn_source_apiserver_describe.md
- docs/cmd/kn_source_binding.md
- docs/cmd/kn_source_binding_describe.md
- docs/cmd/kn_source_cronjob.md
- docs/cmd/kn_source_cronjob_describe.md
- docs/cmd/kn_trigger.md
- docs/cmd/kn_trigger_describe.md
- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/revision/describe_test.go
- pkg/kn/commands/route/describe.go
- pkg/kn/commands/route/describe_test.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/binding/describe.go
- pkg/kn/commands/source/cronjob/describe.go
- pkg/kn/commands/trigger/describe.go
- pkg/printers/prefixwriter.go
- test/e2e/route_test.go
/lint
Fixes #205 
- Keeps the machine readable output
- Align the command description text, check for single argument, reported error messages and unit tests in service, revision, route, source binding describe commands
Default output:
```
➜  client git:(pr/describe-route) ./kn route describe foo
Name:       foo
Namespace:  default
Age:        2m
URL:        http://foo.default.apps.ci-ln-dr6jjit-d5d6b.origin-ci-int-aws.dev.rhcloud.com
Service:    foo
Traffic Targets:  
40%  foo-zxjzw-1 #v1
URL:  http://v1-foo.default.apps.ci-ln-dr6jjit-d5d6b.origin-ci-int-aws.dev.rhcloud.com
60%  foo-bhjrx-2 #v2
URL:  http://v2-foo.default.apps.ci-ln-dr6jjit-d5d6b.origin-ci-int-aws.dev.rhcloud.com
Conditions:  
OK TYPE                  AGE REASON
++ Ready                 13s 
++ AllTrafficAssigned     2m …
```
> Implement human readable output for kn route describe

- CHANGELOG.adoc
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
Fixes #632 
* infer the `sync` param from `fakeServiceUpdate` and `fakeServiceCreate` by the
parameter `--no-wait`.
* simplifies the UTs and also avoids a nasty NPE if the sync param was not (in sync :)
with the `--no-wait` flag.
> fix(#632): refactored UT to remove need of specifying sync twice

- CHANGELOG.adoc
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
Fixes #533 
* Introduce new type `singletonString` for flag values that only allow single value assignment, otherwise return error
* Fix `--image` flag with the new type.
Example:
```bash
➜  client git:(issue-533) kn service create svc-test --image gcr.io/knative-samples/helloworld-go --image gcr.io/foo/bar:barz --no-wait 
invalid argument "gcr.io/foo/bar:barz" for "--image" flag: value is already set
```
> Fix --image flag to only allow single occurence

- pkg/kn/commands/trigger/trigger.go
- pkg/kn/commands/trigger/update.go
- test/e2e/trigger_test.go
Fixes #568
* Add e2e tests for trigger
* Add retry mechanism in trigger update when meeting with conflicting error.
> Add E2E tests for trigger

- test/e2e/common.go
> e2e: Dump stdout and describe ksvc

- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/source/apiserver/flags.go
- pkg/kn/commands/source/apiserver/list_test.go
- pkg/kn/commands/source/binding/binding.go
- pkg/kn/commands/source/binding/flags.go
- pkg/kn/commands/source/binding/list_test.go
- pkg/kn/commands/source/cronjob/flags.go
- pkg/kn/commands/source/cronjob/list_test.go
- pkg/kn/commands/trigger/list_flags.go
- pkg/kn/commands/trigger/list_test.go
Fixes #567
* Change `SUBSCRIBER_URI` to `SINK` in trigger list
* Add `CONDITIONS` to trigger list
* Add `AGE` to trigger and source ( cronjob, apiserver, binding ) list
* Move `SinkToString` to package `flags` and reuse in trigger list
> Harmonize list headers for trigger and sources

- pkg/kn/commands/source/human_readable_flags.go
- also update the description for other source types
```
./kn source list-types 
TYPE              NAME                                            DESCRIPTION
ApiServerSource   apiserversources.sources.eventing.knative.dev   Watch and send Kubernetes API events to a sink
ApiServerSource   apiserversources.sources.knative.dev            Watch and send Kubernetes API events to a sink
ContainerSource   containersources.sources.eventing.knative.dev   Connect a custom container image to a sink
CronJobSource     cronjobsources.sources.eventing.knative.dev     Send periodically constant data to a sink
PingSource        pingsources.sources.knative.dev                 Send periodically ping events to a sink
SinkBinding       sinkbindings.sources.eventing.knative.dev       Binding for connecting a …
```
> Add description for PingSource for 'kn source list-types'

- pkg/kn/core/root.go
The default behaviour of Cobra library is to add default `help` cmd as late as possible to allow modifications. However, in case of `kn` initialization of help is superseded by [plugin parsing](https://github.com/knative/client/blob/7573a07a249cad63262903c722b2f914be340266/pkg/kn/core/root.go#L85) and fails with `unknown command` error.
```
➜  client git:(issue-533) kn help
Error: unknown command 'help' 
Run 'kn --help' for usage.
```
This change brings back `help` as a command and enables usage of both `kn help` and `kn help <sub-command>`.
* Add early initialization of default help command.
> fix(help): initialize default help cmd early

- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
The error window introduced with #644 had a wrong conditional. Fixed that and added a test which would have detected this.
Also, this should fix some issues which we tried to detect with #659.
> fix(service wait): Wrong check for error window

- CHANGELOG.adoc
- pkg/kn/commands/revision/delete.go
- pkg/kn/commands/revision/delete_test.go
- test/e2e/revision_test.go
Addresses #317 
Release note:
- 🧽 Support multiple revision names on `kn revision delete`
> Support multiple arguments on revision delete

- pkg/kn/commands/service/service_update_mock_test.go
- pkg/kn/commands/service/update.go
- pkg/serving/v1/client.go
- pkg/serving/v1/client_mock.go
Move the retry logic for retrying in case of a resource conflict into the KnClient.
This is wip (e.g. unit tests are not working yet), but demonstrate how to move the retry logic into the client. If we decided that its worth the effort, I will update the tests, too.
/hold
> feature(service update): Add generic mechanism to include retries on conflicts

- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
See: https://github.com/knative/serving/pull/6865
/lint
> Prevent service-specific labels from being put on the revision template

- docs/cmd/kn_revision_list.md
- docs/cmd/kn_route_list.md
- docs/cmd/kn_source_apiserver_list.md
- docs/cmd/kn_source_binding_list.md
- docs/cmd/kn_source_cronjob_list.md
- docs/cmd/kn_source_list-types.md
- pkg/kn/commands/revision/list.go
- pkg/kn/commands/route/list.go
- pkg/kn/commands/source/apiserver/list.go
- pkg/kn/commands/source/binding/list.go
- pkg/kn/commands/source/cronjob/list.go
- pkg/kn/commands/source/list_types.go
Update other list command examples as well.
> fix typo in source list-types examples

- test/e2e-tests.sh
Fixes #686
- changed from 30m to 45m
> chore(e2e): Increase e2e timeout to 45 minutes

- CHANGELOG.adoc
- docs/README.md
- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/types.go
- pkg/kn/core/root.go
- test/e2e/sinkprefix_test.go
Fixes #571
* Allow user to config customized sink prefix in kn config file, e.g. below lines in config.yaml defines two prefixes `test` and `hello`, which map to `broker` in  `eventing.knative.dev/v1alpha1` and `service` in `serving.knative.dev/v1` accordingly.
```
sink:
- prefix: test
group: eventing.knative.dev
resource: brokers
version: v1alpha1
- prefix: hello
group: serving.knative.dev
resource: services
version: v1
```
> Allow configuration sink prefixes

- test/e2e/service_options_test.go
Fixes #691 
* e2e Test for user flag
> add e2e for user flag

- test/e2e/revision_test.go
Fixes #695
- Re-order revision tests operations to avoid any race condition that
may occur.
> fix(e2e): Update revision e2e tests

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/free-form.md
- .github/pull-request-template.md
- CHANGELOG.adoc
I.e. removed the sponge icon with some star dust and added a refactoring icon.
Also the templates has been streamlined wrt/ to questions, and a
"free form" template has been added, without structure.
> chore: Cleanup templates and tuned icons

- CHANGELOG.adoc
- docs/cmd/kn_source_cronjob_create.md
- docs/cmd/kn_source_cronjob_update.md
- pkg/eventing/legacysources/v1alpha1/cronjob_client.go
- pkg/kn/commands/source/cronjob/create.go
- pkg/kn/commands/source/cronjob/create_test.go
- pkg/kn/commands/source/cronjob/cronjob_test.go
- pkg/kn/commands/source/cronjob/describe.go
- pkg/kn/commands/source/cronjob/describe_test.go
- pkg/kn/commands/source/cronjob/flags.go
- pkg/kn/commands/source/cronjob/list_test.go
- pkg/kn/commands/source/cronjob/update.go
- pkg/kn/commands/source/cronjob/update_test.go
- test/e2e/cronjob_test.go
Fixes #564
* Add flag `service-account` to cronjob commands to handle service account name
* Add flag `requests-cpu`,`requests-memory`,`limits-cpu` and `limits-memory` to cronjob commands to handle resources configuration
* Update `cronjob describe` to include the new flags
* Update unit tests and e2e test accordingly
> Add serviceaccount and resources config to cronjob source handling

- hack/update-deps.sh
This script is the hook that the bots key off of to float our dependencies forward via a PR each day that lets us determine whether things have broken via Prow.  In our other repos, this generally lets us know about breaking changes across repos within 1 business day, and has proven valuable.
Add a script to automatically float select dependencies forward via `./hack/update-deps.sh --upgrade`.
/lint
> Setup `./hack/update-deps.sh` so that we can auto-update CLI.

- docs/DEVELOPMENT.md
- test/README.md
- Setup Knative now points to https://knative.dev/docs/install/any-kubernetes-cluster/
- Corrects the local link to docs/DEVELOPMENT.md
> fix(docs): Fix links to knative install and relative reference

- CHANGELOG.adoc
- docs/cmd/kn_version.md
- pkg/kn/commands/version/version.go
- pkg/kn/commands/version/version_test.go
Fixes #513
Add -o flag to `kn version` command and support JSON/YAML formats.
Examples:
```
➜  client git:(pr/kn-version-json) kn version -ojson
{
"Version": "v20200309-local-1cbb94e2-dirty",
"BuildDate": "2020-03-09 13:35:39",
"GitRevision": "1cbb94e2",
"SupportedAPIs": {
"eventing": [
"sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)",
"sources.eventing.knative.dev/v1alpha2 (knative-eventing v0.13.1)",
"eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)"
],
"serving": [
"serving.knative.dev/v1 (knative-serving v0.13.0)"
]
}
}
```
and
```
➜  client git:(pr/kn-version-json) kn version -oyaml
BuildDate: "2020-03-09 13:35:39"
GitRevision: 1cbb94e2
SupportedAPIs:
eventing:
- sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)
- …
```
> feat(version): Add JSON/YAML output formats for version command

- CHANGELOG.adoc
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/errors/factory.go
- pkg/errors/factory_test.go
- pkg/kn/commands/types.go
- pkg/kn/commands/types_test.go
Fixes #315
- Improve error reporting if
- kubeconfig file is missing or
- there is no route to host
- i/o timeout
/lint
> Improve reporting for missing kubeconfig and error connecting to the cluster

- CHANGELOG.adoc
- docs/cmd/kn_trigger_create.md
- docs/cmd/kn_trigger_update.md
- pkg/eventing/v1alpha1/client.go
- pkg/eventing/v1alpha1/client_test.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/create_test.go
- pkg/kn/commands/trigger/trigger_test.go
- pkg/kn/commands/trigger/update_flags.go
- test/e2e/trigger_inject_broker_test.go
Allow user to add default broker when creating trigger.
* Add flag `--inject-broker` to trigger create commnad
> feat(trigger): add --inject-broker flag to trigger create command

- test/e2e/cli.go
- test/e2e/ping_test.go
Verify ping source created correctly by "source ping describe" after "source ping create"
* Verify ping source created correctly by 'source ping describe' command
Fixes #566
> Verify "source ping describe" in ping e2e test

- docs/cmd/kn_service.md
- docs/cmd/kn_service_export.md
- pkg/kn/commands/service/export.go
- pkg/kn/commands/service/export_test.go
- test/e2e/service_export_import_apply_test.go
Add e2e test for kn service export
* Add e2e test for 'kn service export'
* Refactor unit test for 'kn service export' 
* Drop the traffic information if only one revision is present in the traffic
> e2e for service export

- CHANGELOG.adoc
- docs/cmd/kn_trigger_create.md
- pkg/eventing/v1alpha1/client.go
- pkg/eventing/v1alpha1/client_test.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/describe.go
- test/e2e/trigger_test.go
Fix issue with `kn trigger create` that always required `--filter` flag.
* `TriggerBuilder` adds only empty Spec.Filter for empty or nil arrays
* The above should also allow builder to be used to clean up existing filters
* `kn trigger describe` doesn't print empty Filter
Fixes #744
> fix(trigger): Make --filter flag truly optional

- CHANGELOG.adoc
- pkg/eventing/v1alpha1/client.go
- test/e2e/trigger_test.go
Fix `TriggerBuilder.Filter` to actually replace map on update.
* Fix filter delete via `--filter key-` flag
Fixes #743
> fix(trigger): Fix filter delete for trigger update

- CHANGELOG.adoc
- docs/plugins/README.md
- pkg/kn/commands/plugin/handler.go
- pkg/kn/commands/plugin/handler_test.go
- pkg/kn/commands/plugin/plugin_test_helper.go
Fixes #737
* Use exec.Command instend of syscall.Exec for windows.
* Fix a bug in plugin handler test when running it on windows.
* Fix typo.
Release Note:
- 🐛 Bug fix
Using exec.Command instend of syscall.Exec for windows.
> Run plugin on Windows

- CHANGELOG.adoc
- pkg/kn/commands/types.go
Add function that returns default path based on OS.
* Add `newDefaultConfigPath` to return OS-based paths
> fix: Fix default config path on Windows

- pkg/kn/commands/revision/list.go
* The `clientservingv1alpha` has been deprecated.
> Replace alias `clientservingv1alpha` to `clientservingv1`

- CHANGELOG.adoc
- docs/cmd/kn_trigger_create.md
- docs/plugins/README.md
- pkg/eventing/v1alpha1/client.go
- pkg/eventing/v1alpha1/client_test.go
- pkg/kn/commands/plugin/handler.go
- pkg/kn/commands/plugin/handler_test.go
- pkg/kn/commands/plugin/plugin_test_helper.go
- pkg/kn/commands/trigger/create.go
- pkg/kn/commands/trigger/describe.go
- pkg/kn/commands/types.go
- test/e2e/trigger_test.go
Backport trigger filter fixes to `0.13.x` release.
* Cherry-pick 58ee9c4788bd9655cede37d710fa45762a9ef2fe
* Cherry-pick 1b0e7124d7706171bde34d2ffe0958a9954eaefe
* Cherry-pick 5e73d8dad37b955a06075c2a3b990eaa595f94f0
* Cherry-pick a0a762b87eb9a7ad4b19b5b1b37869c511faf3a8
**Note:** I've updated changelog to point to next `0.13.1` release, but I'm not quiet sure about PR ref. Should the URL point to original PR or this one?
> fix(trigger): Backport trigger filter fixes

- CHANGELOG.adoc
- lib/test/cli.go
- lib/test/integration.go
- lib/test/result_collector.go
- test/e2e/service_options_test.go
- test/e2e/source_apiserver_test.go
- test/e2e/traffic_split_test.go
Fixes various godoc comments that are not conforming as well as some /lint issues that came up
* correct signatures for some functions with with non-conforming names
* various corrections to Godoc comments for exported code in new lib/test
* fix CHANGELOG.doc for new location for common test code
Fixes #769
/lint
> fix(769): various issues with godoc documents

- CHANGELOG.adoc
- pkg/kn/commands/plugin/handler.go
* Change plugin lookup to try to match well-know file extensions
Fixes #767
> fix(plugin): Fix plugin lookup with file ext on Windows

- test/local-e2e-tests.sh
Use vendored deps while running e2e locally to avoid deps collision.
Also set GO111MODULE=on unconditionally
> Use vendored deps while running e2e locally

- docs/cmd/kn_revision_delete.md
- docs/cmd/kn_service_delete.md
- pkg/kn/commands/wait_flags.go
- pkg/kn/commands/wait_flags_test.go
- pkg/serving/v1/client.go
In it's current state it now takes me about 25 seconds for the `kn delete`
to complete. Before https://github.com/knative/client/pull/682 it used to be
almost immediate. This is because we now pass in the
`DeletePropagationBackground` flag. I believe this is a mistake, not only
because of the 20+ seconds of additional time to delete things, but IMO
the CLI should talk to the server in the same way regardless of the --wait
flag. That flag should just be a CLI thing to indicate if the user wants the CLI
to wait for the server to complete but not HOW the server should do the delete.
> Remove the delete propagation flag

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/describe_test.go
- pkg/kn/commands/service/update_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/revision_template.go
- test/e2e/service_options_test.go
Fixes: #https://github.com/knative/client/issues/768
* Support setting "autoscaling.knative.dev/targetUtilizationPercentage" annotation.
Release Note:
- 🎁 New feature
Add "--target-utilization" to manage "autoscaling.knative.dev/targetUtilizationPercentage" annotation.
> Add target-utilization option for `service create` and `service update`

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- test/e2e/service_options_test.go
I find that I'm using annotations more and more and since `-a`
wasn't being used I decided we should save people from typing too much
* add support for `-a` as an alias for `--annotation`
/lint
> Add -a flag as alias for --annotation

- pkg/kn/commands/flags/listprint.go
- pkg/kn/commands/flags/listprint_test.go
- pkg/kn/commands/service/list.go
- pkg/printers/tableprinter.go
- pkg/util/unstructured.go
- pkg/util/unstructured_test.go
- test/e2e/basic_workflow_test.go
Fix the error when calling `kn service list -o name`. Because the default name printer only supports `unstructured.UnstructuredList`, we have to convert `servingv1.ServiceList` to `unstructured.UnstructuredList` when output flag is set.
* Convert servingv1.ServiceList to unstructured.UnstructuredList when output flag is set in `kn service list -o name`
Fixes #754
> Fix error when output is set to name

- CHANGELOG.adoc
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
Fixes: #https://github.com/knative/client/issues/789
* The `kn service describe -v` command shows repetitive revisions, because
the revision would be covered by next one.
> Show all revisions when run `service describe -v`

- test/e2e/service_options_test.go
Add e2e test for different service and revision label
Fixes #718 
/assign @rhuss
> Add e2e test for different service and revision label

- pkg/kn/commands/revision/list.go
- pkg/kn/commands/route/list.go
- pkg/kn/commands/source/apiserver/list.go
- pkg/kn/commands/source/binding/list.go
- pkg/kn/commands/source/ping/list.go
- pkg/kn/commands/trigger/list.go
- test/e2e/ping_test.go
- test/e2e/revision_test.go
- test/e2e/route_test.go
- test/e2e/source_apiserver_test.go
- test/e2e/source_binding_test.go
- test/e2e/trigger_test.go
Follow up PR #775  to fix other resources `list -oname` issue.
* Fix errors of resource list command to support -oname flag
Fixes #798
> Fix resource listing with -oname flag

- docs/cmd/kn_revision_delete.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_delete.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/revision/delete.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/delete.go
- pkg/kn/commands/service/service_test.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/wait_flags.go
- pkg/kn/commands/wait_flags_test.go
- pkg/kn/flags/bool.go
- pkg/kn/flags/bool_test.go
Fixes #800
- Deprecated bool vars can be supported for CLI convention
- Bind --async flag value to --no-wait
```
➜  kn service create foo --image gcr.io/foo/bar --async --no-wait
only one of (DEPRECATED) --async, --wait and --no-wait may be specified
➜  kn service create foo --image gcr.io/foo/bar --async --wait   
only one of (DEPRECATED) --async, --wait and --no-wait may be specified
➜  kn service create foo --image gcr.io/foo/bar --async --no-wait --wait
only one of (DEPRECATED) --async, --wait and --no-wait may be specified
➜  kn service create foo --image gcr.io/foo/bar --async=false           
use --wait instead of providing "false" to --async
```
/lint
> Make wait, no-wait and async flags per bool var CLI convention

- test/e2e/basic_workflow_test.go
- test/e2e/revision_test.go
Since the default behavior is background deletion, add `--no-wait=false` to service/revision delete operations in e2e to avoid any race conditions and flakes
- Add `--no-wait=false` for service/revision delete operations in e2e.
/lint
> e2e: Foreground delete for revisions and services in e2e

- CHANGELOG.adoc
- pkg/kn/commands/service/update_test.go
- pkg/kn/commands/source/apiserver/update.go
- pkg/kn/commands/source/apiserver/update_test.go
- pkg/kn/commands/source/binding/update.go
- pkg/kn/commands/source/binding/update_test.go
- pkg/kn/commands/source/ping/update.go
- pkg/kn/commands/source/ping/update_test.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/commands/trigger/update_test.go
- pkg/serving/v1/client.go
Fixes: #786 
* Check DeleteTimestamp before updating resource. Include: service, apiserver source, sink binding, ping source, trigger.
Release Note:
- 🐛 Bug fix
Check DeleteTimestamp before updating resource.
> Check DeleteTimestamp before updating resource

- docs/cmd/kn_service_export.md
- pkg/kn/commands/service/export.go
- pkg/kn/commands/service/export_test.go
- test/e2e/service_export_import_apply_test.go
Changes made to export revisions directly with kn service export.
https://github.com/knative/client/issues/728#issuecomment-603928462 - This was the approach followed
* --with-revisions option will export service and revision list
* --with-revisions --kubernetes-resources will export a service list (kubectl friendly)
* add annotations to export
Fixes #728
> refactor kn service export to export revisions

- .github/pull-request-template.md
Correcting a minor typo in the pull request template: `belpow` -> `below`
> Correct Typo in Pull Request Template

- CHANGELOG.adoc
- pkg/kn/commands/plugin/list_test.go
- pkg/kn/commands/plugin/plugin.go
- pkg/kn/commands/plugin/plugin_test.go
- pkg/kn/commands/plugin/verifier.go
- pkg/kn/commands/plugin/verifier_test.go
- pkg/kn/core/root.go
In rare cases (e.g., `source`) an existing command group should be extensible via plugins. This PR addresses that. Source should be extensible since many of the eventing sources will be supported via plugins.
* introduce a list of command group that can be extended (currently only source)
* check if plugin main group is in that list and execute, otherwise fail
* add e2e test for both plugin that is allowed and not allowed to extend existing group
Fixes #814
/lint
> fixes(#814) allow plugins to extend the 'source' command group

- CHANGELOG.adoc
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
This pull request adds a check for if `LatestReadyRevisionName` is `""` with `kn service describe`, indicating the Revision is in a Pending or Unknown state. This will prevent `kn service describe` from returning an error message of `resource name may not be empty` due to `LatestReadyRevisionName` being an empty string when passed to the `GetRevision` function in ` completeWithLatestRevisions`.
Add a check for if `revisionName == ""` and continue to the next loop iteration if true. Also added a unit test for this case and edited helper functions. 
Open to any different interpretation of how to treat this case as far as whether the revisionName should be skipped or other details should be returned.
Fixes #823 
/lint
> Skip LatestReadyRevisionName if Revision is Pending or Unknown

- conventions/cli.md
This PR tries to add some more details about the CLI conventions that we have established for the kn client. This guideline should also apply for plugin development.
> chore: Reworked CLI conventions and include more details

- lib/test/revision.go
- lib/test/service.go
- lib/test/utils.go
- test/e2e/basic_workflow_test.go
- test/e2e/ping_test.go
- test/e2e/revision_test.go
- test/e2e/route_test.go
- test/e2e/service_export_import_apply_test.go
- test/e2e/service_options_test.go
- test/e2e/service_test.go
- test/e2e/sinkprefix_test.go
- test/e2e/source_apiserver_test.go
- test/e2e/source_binding_test.go
- test/e2e/traffic_split_test.go
- test/e2e/trigger_inject_broker_test.go
- test/e2e/trigger_test.go
brings commonly re-used utilities into lib/test so they can be resused
and e2e can be run selectively for eventing/serving.
Fixes #828
> fix(e2e): Refactor e2e utils and resource actions

- CHANGELOG.adoc
- docs/cmd/kn_service_delete.md
- pkg/kn/commands/service/delete.go
- pkg/kn/commands/service/delete_mock_test.go
- pkg/kn/commands/service/list_mock_test.go
- test/e2e/service_test.go
This pull request adds the ability to delete all Services in a namespace using `kn service delete --all`. Follows same behavior as `kubectl delete ksvc --all`.  
* Add `--all` flag to `kn service delete`. Boolean value that will delete all Services when specified. False by default. 
* Add `getServiceNames` function to retrieve all the names of Services in a namespace when `--all` flag is specified.
* Unit tests
* Minor reordering of test data in `list_test_data`
Fixes #792 
/lint
> Add kn service delete --all

- lib/test/integration.go
- lib/test/utils.go
- test/e2e-tests.sh
- test/e2e/plugins_test.go
- test/e2e/sinkprefix_test.go
- If a namespace (kne2etestsN) is being created to run e2e tests and it exists, e2e execution fails. This patch tries creating the next namespace (kne2etestsN+1) if earlier exists, retries cap at 20.
- Tags plugins tests to run into serving or eventing scope but only in e2e scope.
> fix(e2e): Create next namespace for e2e if one exists

- CHANGELOG.adoc
- test/e2e/service_test.go
Following up on some [pull request feedback](https://github.com/knative/client/pull/836#discussion_r425045139) from #836 to make the e2e test for `kn service delete --all` a bit easier to maintain.
* Use list of services names to iterate over names to check output from `kn service list` and `kn service delete --all`
* Use `strings.Contains` instead of string from `fmt.Sprintf` for delete output validation
* Code comments 
**Edit:**
Changed original proposal based on feedback:
* Check if `len(kn service list) > 0` to verify data is available to delete
* Run `kn service delete --all`
* Check output message from delete contains `successfully deleted`
* Check if `len(kn service list) == 0` returns `No services found` message verifying deletion of all services.
/lint
> Refactor kn service delete --all e2e test

- CHANGELOG.adoc
- pkg/kn/commands/source/ping/describe.go
- pkg/kn/commands/source/ping/describe_test.go
This pull request moves all `Sink.Ref` properties from being referenced for `kn source ping describe` until after it has been checked if `Sink.Ref` is nil due to using a URI instead of a Ref. 
It also fixes tests for `kn source ping describe`, which are not asserting whether command output is successfully returned or not. 
Fixes #847 
/lint
> Fix Panic for kn source ping describe with Sink URI

- CHANGELOG.adoc
- go.mod
- lib/test/cli.go
- lib/test/integration.go
- pkg/kn/commands/plugin/verifier.go
- pkg/kn/commands/plugin/verifier_windows.go
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/delete_test.go
- pkg/kn/commands/trigger/update_flags.go
- pkg/serving/v1/client.go
- test/e2e/source_apiserver_test.go
As per title. Since Golang 1.13, the stdlib has vastly improved regarding error wrapping etc. Make use of that.
* Replaced `errors.New` with the stdlib.
* Replaced `errors.Wrap(f)` with `fmt.Errorf`
> Replace pkg/errors with stdlib errors.

- cmd/kn/main.go
- pkg/kn/commands/plugin/handler.go
- pkg/kn/core/root.go
- pkg/kn/core/root_test.go
- test/e2e/basic_workflow_test.go
This pull request removes the use of `os.Exit(1)` from areas of `kn` with the exception of `main.go` and `generate-docs.go`. Instead of using `os.Exit(1)` an error is returned now and handled in `main.go`.
Can also work of removing from `generate-docs.go`, but my thought was the issue was meant to address this in `kn`.
Can wait for #834 and rebase if that is preferred.
Fixes #850 
/lint
> Remove Use of os.Exit() and Return Error Instead

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- lib/test/service.go
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/flags/resources.go
- pkg/kn/flags/resources_test.go
- pkg/serving/config_changes.go
- test/e2e/service_options_test.go
- Add `--requests` and `--limits` flags for service create and update
- Deprecate `--requests-cpu`, `--requests-memory`, `--limits-cpu` and `--limits-memory` flags
- Add `service create` example for using memory, CPU, GPU resources
- Add error message if new and deprecated, requests and limits flags are used together
- Add warning message if deprecated flags are used
- Add unit and e2e tests, update existing unit tests
Fixes #490
/lint
```
$ kn service create hello-gpu-2 --image docker.io/mvinkler/hellocuda-go --limits nvidia.com/gpu=1
Creating service 'hello-gpu-2' in namespace 'default':
5.175s Configuration "hello-gpu-2" is waiting for a Revision to become ready.
5.299s Ingress has not yet been reconciled.
5.635s Ready to serve.
Service 'hello-gpu-2' created to latest revision …
```
> Add --requests and --limits resource flags

- pkg/serving/v1/client.go
> Check deletionTimestamp for "kn revision delete"

- pkg/kn/commands/plugin/handler.go
- pkg/kn/commands/plugin/handler_test.go
- pkg/kn/core/root.go
- test/e2e/basic_workflow_test.go
This pull request adds a check for if `-h` or `--help` is specified with a plugin command. There should be no need to check for plugin executable availability if `--help` is specified and will avoid an error being returned that a command does not exist as documented in #845.
* Add check for if `-h` or `--help` is specified in `HandlePluginCommand`
* Add test
Fixes #845 
/lint
> Fix kn source -h

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update.go
- pkg/kn/flags/resources.go
- pkg/kn/flags/resources_test.go
- pkg/serving/config_changes.go
- test/e2e/service_options_test.go
- Use singular flag names and support comma separated or repeated flag values
- Update tests and docs
> Update flag names to --request and --limit

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update.go
- pkg/kn/flags/resources.go
- pkg/kn/flags/resources_test.go
- pkg/serving/config_changes.go
- test/e2e/service_options_test.go
Cherry-pick: c1ab4ae86338527cdc33bccedcc29a05b7273ae8
> release(0.15.1): Backport fix for resource flags names

- hack/build.sh
> Fix build.sh for macOs users

- CHANGELOG.adoc
- lib/test/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e/service_test.go
- test/e2e/traffic_split_test.go
This pull request returns an error message when using `kn service update serviceName --untag tagName --no-wait` on a tag that does not exist.
The error returned by `kn` will be as follows, but I am open to any change with regard to the message:
```
Error: tag tagName does not exist
```
In the event multiple nonexistent tags are specified, `kn` will return multiple errors:
```
kn service update serviceName --untag tagName --untag tagName2 --no-wait
Error: tag tagName does not exist
Error: tag tagName2 does not exist
```
If a tag that does exist is specified with a nonexistent tag, the error will be displayed and no update will be made. 
Please let me know if this should warrant an e2e test as well.
Fixes #874
/lint
> Return Error Message from Using --untag with Nonexistent Tag

- CHANGELOG.adoc
- go.mod
- hack/build.sh
- hack/verify-codegen.sh
- lib/test/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e/service_test.go
- test/e2e/traffic_split_test.go
- vendor/modules.txt
client v0.15.2 release backports with a bug fix and pinning go 1.14 in go.mod (inline with serving v0.15.x release).
* Backport from master:
-  #866 
-  #880 
-  #883
* CHANGELOG update
> v0.15.2 release backports

- lib/test/broker.go
- pkg/dynamic/fake/fake.go
- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/flags/sink_test.go
- test/e2e/sink_test.go
- test/e2e/trigger_test.go
- Broker is now moved to v1beta1 APIs, while we were referring it from `v1alpha1`
https://github.com/knative/client/blob/10b23b8802d59f0c0cecbe2d7f4ae8af944cbf68/pkg/kn/commands/flags/sink.go#L53
this wasnt caught in e2e because we dont have an e2e for referring broker using `--sink`.
- This PR refers broker from v1beta1 and add respective e2e tests to verify.
- Move broker injection namespace label, unlabel utilities to lib
- Refer broker from eventing v1beta1 APIs
- Add e2e test for refering default broker as sink
/lint
> Refer broker from v1beta1 APIs and add missing e2e tests

- CHANGELOG.adoc
- pkg/kn/commands/trigger/describe.go
- pkg/kn/commands/trigger/describe_test.go
This pull request moves all `Sink.Ref` properties from being referenced for `kn trigger describe` until after it has been checked if `Sink.Ref` is nil due to using a URI instead of a Ref. 
Fixes #899
/lint
> Fix Panic for kn trigger describe with Sink URI

- docs/cmd/kn.md
- docs/cmd/kn_broker.md
- docs/cmd/kn_broker_create.md
- docs/cmd/kn_broker_delete.md
- docs/cmd/kn_broker_describe.md
- docs/cmd/kn_broker_list.md
- pkg/eventing/v1beta1/client.go
- pkg/eventing/v1beta1/client_mock.go
- pkg/eventing/v1beta1/client_mock_test.go
- pkg/eventing/v1beta1/client_test.go
- pkg/kn/commands/broker/broker.go
- pkg/kn/commands/broker/broker_test.go
- pkg/kn/commands/broker/create.go
- pkg/kn/commands/broker/create_test.go
- pkg/kn/commands/broker/delete.go
- pkg/kn/commands/broker/delete_test.go
- pkg/kn/commands/broker/describe.go
- pkg/kn/commands/broker/describe_test.go
- pkg/kn/commands/broker/list.go
- pkg/kn/commands/broker/list_test.go
- pkg/kn/root/root.go
- test/e2e/broker_test.go
Since the Eventing `0.15` multitenant broker is the new default. MT Broker is easier to manage from user's namespace because there're no more requirements for additional permission as majority of broker deployment is installed in `knative-eventing` namespace. This PR adds commands to manage broker CR. 
* Add `broker create`, `broker delete`, `broker list` commands
Note 1: E2E are missing right now, I'm currently working on them.
Note 2: I haven't added `update` operation since the current impl only creates Broker CR with a name without additional specs.
Fixes #
> Add broker create, delete and list cmds

- CHANGELOG.adoc
- pkg/kn/commands/source/apiserver/apiserver_test.go
- pkg/kn/commands/source/apiserver/create_test.go
- pkg/kn/commands/source/apiserver/delete_test.go
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/apiserver/describe_test.go
- pkg/kn/commands/source/apiserver/list_test.go
- pkg/kn/commands/source/apiserver/update_test.go
- pkg/kn/commands/source/binding/binding_test.go
- pkg/kn/commands/source/binding/create_test.go
- pkg/kn/commands/source/binding/delete_test.go
- pkg/kn/commands/source/binding/describe.go
- pkg/kn/commands/source/binding/describe_test.go
- pkg/kn/commands/source/binding/list_test.go
- pkg/kn/commands/source/binding/update_test.go
Following up on #848 and #900, this pull request updates `kn source apiserver` and `kn source binding describe` to avoid a panic when using a Sink that has a URI instead of a Ref. 
This pull request also updates unit tests for `apiserver` and `binding` as some tests are not asserting whether output of commands is correct. 
/lint
> Fix Panic for kn source apiserver and kn source binding describe with Sink URI

- pkg/kn/commands/broker/create_test.go
- pkg/kn/commands/broker/delete_test.go
- pkg/kn/commands/source/ping/create_test.go
- pkg/kn/commands/source/ping/delete_test.go
- pkg/kn/commands/source/ping/list_test.go
- pkg/kn/commands/source/ping/update_test.go
- pkg/kn/commands/trigger/create_test.go
- pkg/kn/commands/trigger/delete_test.go
- pkg/kn/commands/trigger/update_test.go
This pull request adds assertions for unit tests for verifying command output. The commands missing these assertions in unit tests were `source ping`, `trigger`, and `broker`. 
It also updates unit tests for `source ping` since `Ping` is capitalized in command output for `delete` and `list`.
/lint
> Add Missing Assertions for Command Unit Tests

- lib/test/broker.go
Uses the broker injection key from eventing  and not hard code, as there is a change coming it in eventing v0.16 release with sugar controller.
see https://github.com/knative/eventing/pull/3459
> Use broker injection label key from trigger types

- test/common.sh
We'll need sugar controller for reconciling broker for tests
which labels namespace and annotates the triggers.
Currently, sugar controller is not part of the eventing nightly release setup
by test-infra libs. This changeset adds install of same for nightly
CI setup.
> Setup eventing extension: sugar controller

- CHANGELOG.adoc
- docs/cmd/kn_service_describe.md
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
* Added Support for service url display in `kn service describe` as output format
Fixes #907
> Add support for service url in svc describe output

- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
Fixed an error message in the create_test.go file
* Changed 1000 to 100 to match the value used in the test.
> Fixed the error message for min/max scale tests

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
Add provision to specify port name
* Change port field from int32 to string
*  Accept port field as portname:port
* Set the container port option accordingly
Fixes #912
> add port name

- docs/cmd/kn_service_create.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_test.go
- test/e2e/service_file_test.go
Allow users to create Services from provided YAML or JSON file.
There're couple of open questions:
- Is it necessary to keep `NAME` parameter for the create command?
- Should the `NAME` parameter take priority over file provided name?
- Should the multi-item (services separated by `---`) YAML be supported as well? 
* Add new flag `--filename` to `service create` command
Fixes #550
> feat: Add --filename flag to service create command

- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- docs/operations/autoscaling.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
- test/e2e/service_options_test.go
This allows a user to set --scale which will update MinScale and MaxScale to the same value. 
* add --scale as a CLI option
#822
> Added the option to use --scale for setting MinScale and MaxScale to the same value

- test/e2e/source_list_test.go
Add E2E test cases for "kn source list"
- Test cases for valid & Invalid filter option.
- Source list output in YAML format.
Fixes #722
> Add E2E test cases for "kn source list".

- CHANGELOG.adoc
- cmd/kn/main.go
- cmd/kn/main_test.go
- hack/build.sh
- hack/generate-docs.go
- pkg/kn/plugin/manager.go
- pkg/kn/plugin/manager_test.go
- pkg/kn/root/root.go
- pkg/kn/root/root_test.go
- pkg/templates/command_groups.go
- pkg/templates/command_groups_test.go
- pkg/templates/template_engine.go
- pkg/templates/template_engine_test.go
- pkg/templates/templates.go
- test/e2e/plugins_test.go
This works on all levels. Test needs to be expanded still.
Fixes #266
Fixes #904
> feat: Add plugin listing to "kn --help"

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_test.go
Add enhancement to the command `kn service create -f` to accept other options to modify the created service.
Per discussion in #923 we should decide how `name` is handled:
- Provided cmdline `name` overrides the name in the file
- Keep the current implementation that if `name` is provided on cmdline it must match the name in the file.
*  Add support to combine service create --filename with other options
Fixes #923
> feat: Add support to combine service create --filename with other options

- users.htpasswd
file `users.htpasswd` was mistakenly added in #932
> Remove unrelated file

- CHANGELOG.adoc
- lib/test/integration.go
- lib/test/service.go
- test/e2e-tests.sh
- test/e2e/service_export_test.go
- test/e2e/service_file_test.go
- test/e2e/service_options_test.go
- test/e2e/service_test.go
Allow the kn test image to be customized via environment variable.
* all references to KnDefaultTestImage were replaced with GetKnTestImage() function
* all hardcoded occuerences of "gcr.io/knative-samples/helloworld-go" were replaced with GetKnTestImage() function
> allow test image to be customized

- cmd/kn/main_test.go
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- docs/operations/autoscaling.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
- test/e2e/service_options_test.go
This PR updates --max-scale and --min-scale to --scale-max and --scale-min
* Updated --max-scale to --scale-max
* Updated --min-scale to --scale-min
https://github.com/knative/client/issues/822
> Deprecates --max-scale/--min-scale for more consistent naming

- pkg/dynamic/client.go
- pkg/dynamic/client_test.go
- pkg/dynamic/lib.go
- pkg/dynamic/lib_test.go
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/errors/factory.go
- pkg/errors/factory_test.go
- pkg/kn/commands/source/list.go
- pkg/kn/commands/source/list_test.go
- pkg/kn/commands/source/list_types.go
- pkg/sources/v1alpha2/apiserver_client.go
- pkg/sources/v1alpha2/client.go
- pkg/sources/v1alpha2/client_test.go
- Identify restricted access error
- If server returns restricted access error, fallback to listing
only eventing inbuilt sources using their GVKs.
- List every typed source and read the error
to know if eventing is installed for `kn source list-types`.
-  Add `isForbiddenError` in kn error factory
-  Add `ListSourcesUsingGVKs` to dynamic client
-  Add  `BuiltInSourcesGVKs` to `pkg/sources/v1alpha2/client.go` which returns inbuilt source GVKs
Fixes #947 
/lint
> List inbuilt sources if CRD access is restricted

- pkg/kn/commands/source/list.go
- test/e2e/source_list_test.go
fix `kn source list --all-namespaces` command output spelling error.
Fixes #962
> fix: `kn source list` command print spelling problems

- CHANGELOG.adoc
- pkg/dynamic/client_mock.go
- pkg/dynamic/client_mock_test.go
Adding mock test client for the dynamic client.
Added mock tests for Dynamic client.
Fixes #952
> Add mock tests for the dynamic client

- CHANGELOG.adoc
- pkg/dynamic/client.go
- pkg/dynamic/client_test.go
- Source list may contain different source types CO and machine readable output (using -o)
requires List object to have GVK set, since the list contains different types of source COs,
we set a custom client GVK on it.
- Use custom GVK {Group: client.knative.dev, Version: v1alpha1, Kind: SourceList}
Fixes #953
/lint
> Set client custom GVK for source list for machine readable output

- pkg/kn/commands/source/human_readable_flags.go
also update the description for other source types to refer 'addressable' instead of 'sink'
> Add kafka source desc for kn source list-types

- CHANGELOG.adoc
- docs/plugins/README.md
- go.sum
- lib/test/broker.go
- pkg/kn/config/config.go
- pkg/kn/plugin/manager.go
- pkg/kn/plugin/manager_test.go
This PR adds the possibility for internal plugins. This works by allowing code to add to a global plugin slice `plugins.InternalPlugins`. By default this slice is empty, but for a custom assembly process (outside of this project), this could be leverage to add plugins directly in the code.
The changes are minimal and well tested, but the PR was created a bit in a hurry so apologies for not having an associated issue yet (but I will create on tomorrow).
> Add support for internal plugins

- pkg/serving/v1/client.go
- pkg/serving/v1/client_mock.go
> fix: Make API parameter type public

- pkg/kn/commands/service/export.go
- test/e2e/service_export_test.go
There are 2 new annotations and 1 label added to Service metadata that currently break our E2E export tests.
Annotations:
- serving.knative.dev/routes
- serving.knative.dev/routingStateModified.
Labels:
-  serving.knative.dev/routingState
* Add `serving.knative.dev/routingStateModified` annotation to ignored export list
* Correct E2E expected values.
Fixes #1002
> fix: Fix service export annotations

- docs/cmd/kn_channel_create.md
- pkg/kn/commands/channel/create.go
use `imcv1beta1` alias reference in the example
> Fix channel create example with inbuilt alias for imcv1beta1

- CHANGELOG.adoc
- docs/cmd/kn_service_export.md
- pkg/kn/commands/service/export.go
Example of `service export` doesn't contain actual `--mode` parameters.
* Fix parameters in the `service export` example
Fixes #N/A
> fix: Fix service export example doc

- test/test_images/helloworld/Dockerfile
The go.mod file was removed in
https://github.com/knative/client/commit/4ea31c444a546dc8c455da9040ffac8b91b25aae
, and breaks building using Tekton.
The error is as follows:
STEP 3: COPY ./test/test_images/helloworld/ .
STEP 4: RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o server
build flag -mod=readonly only valid when using modules
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN CGO_ENABLED=0 GOOS=linux go build
-mod=readonly -v -o server": exit status 1
*
*
*
Fixes #
> Remove -mod=readonly from the helloworld's Dockerfile

- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/service_update_mock_test.go
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- test/e2e/service_options_test.go
This fix should mitigate usage of autoscaling annotations in Service's `metadata.Annotations` field.
Related to split annotation flag mentioned in https://github.com/knative/client/issues/1014.
* `UpdateAnnotations` can distinguish autoscaling annotations and add them to template only
* 
Fixes #1020
> fix: Fix autoscaling annotations in Service metadata

- CHANGELOG.adoc
- hack/build.sh
Produced via:
```shell
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```
/cc rhuss maximilien
/assign rhuss maximilien
> [Automated] Fix misspellings

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_mock_test.go
- test/e2e/service_options_test.go
Add "--annotation-service" and "--annotation-revision" flag to to kn service create and update providing ability to set specific annotations on service and revision 
* Add "--annotation-service" and "--annotation-revision" to kn service create/update
Fixes #1014
/lint
> adding annotation-service and annotation-revision to kn service create/update

- pkg/kn/commands/version/version.go
Mention serving/eventing vendor version v0.18.0
> chore: Update version command for release v0.18.0

- lib/test/subscription.go
sleep for 5 seconds after subscription create and update in e2e
> fix(e2e): Let the subscription and related resource reconcile

- test/e2e/service_export_test.go
- test/presubmit-integration-tests-latest-release.sh
see https://github.com/knative/eventing/issues/4165
see https://github.com/knative/serving/pull/9685
> fix(e2e): Run eventing e2e tests only against nightly and fix service export tests

- pkg/kn/commands/service/configuration_edit_flags.go
Adds back functionality for max-scale/min-scale options. I ended up swapping over naming but never added additional sections to update. 
* Adds back functionality for max-scale/min-scale
Fixes #1008
> Added back functionality to deprecated max-scale/min-scale

- CHANGELOG.adoc
- docs/cmd/kn_channel.md
- docs/cmd/kn_channel_list-types.md
- lib/test/channel.go
- pkg/dynamic/client.go
- pkg/dynamic/client_mock.go
- pkg/dynamic/client_mock_test.go
- pkg/dynamic/client_test.go
- pkg/dynamic/fake/fake.go
- pkg/kn/commands/channel/channel.go
- pkg/kn/commands/channel/flags.go
- pkg/kn/commands/channel/list_types.go
- pkg/kn/commands/channel/list_types_test.go
- pkg/messaging/v1beta1/client.go
- test/e2e/channels_test.go
List available channel types in the cluster which can be used for creating channels.
Add channel list-types
Fixes #979
> feat: List available channel types

- test/e2e/service_export_test.go
Hot fix to unblock 0.18 release.
/assign @rhuss 
If it isn't needed, feel free to close the PR.
> fix(e2e): Skip service export test

- CHANGELOG.adoc
- pkg/serving/v1/client.go
- pkg/serving/v1/client_mock_test.go
- pkg/serving/v1/client_test.go
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
Adding `WithLabel` list filter to serving client lib, which is missing currently. This allows to filter lists by labels.
Fixes #1053 
/lint
> Add WithLabel list filter to serving client lib

- CHANGELOG.adoc
- go.sum
- lib/test/result_collector.go
- pkg/serving/v1/client.go
- pkg/serving/v1/client_mock_test.go
- pkg/serving/v1/client_test.go
- pkg/wait/wait_for_ready.go
- Backports of
#1052 
#1054 
- Update CHANGELOG
> [release-0.17] Backport #1052 and #1054

- .github/workflows/knative-boilerplate.yaml
- .github/workflows/knative-donotsubmit.yaml
- .github/workflows/knative-go-build.yaml
- .github/workflows/knative-go-test.yaml
- .github/workflows/knative-security.yaml
- .github/workflows/knative-stale.yaml
- .github/workflows/knative-style.yaml
- .github/workflows/knative-verify.yaml
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc rhuss maximilien
/assign rhuss maximilien
> [Automated] Update actions

- test/e2e/service_export_test.go
Dont expect mentioned key on the revision labels in service
export tests now. The test is skipped for serving v0.18 release
and configured to only against current serving master.
see #https://github.com/knative/serving/pull/9710
/cc @nak3 @maximilien @rhuss
> fix(e2e): Remove "serving.knative.dev/route" revision label

- pkg/dynamic/client_test.go
- pkg/kn/commands/channel/list_types_test.go
- pkg/kn/commands/subscription/flags.go
- pkg/kn/flags/channel_types.go
- pkg/messaging/v1beta1/subscriptions_client_mock.go
The output of golangci-lint includes below errors:
```
$ golangci-lint run --out-format=github-actions
::error file=pkg/kn/commands/channel/list_types_test.go,line=156,col=2::ineffectual assignment to `output` (ineffassign)
::error file=pkg/kn/commands/channel/list_types_test.go,line=167,col=2::ineffectual assignment to `output` (ineffassign)
::error file=pkg/kn/commands/channel/list_types_test.go,line=181,col=2::ineffectual assignment to `output` (ineffassign)
::error file=pkg/kn/commands/subscription/flags.go,line=113,col=2::Consider preallocating `others` (prealloc)
::error file=pkg/messaging/v1beta1/subscriptions_client_mock.go,line=30,col=2::`namespace` is unused (structcheck)
::error file=pkg/dynamic/client_test.go,line=346,col=9::composites: …
```
> Fix golangci-lint errors

- test/e2e-tests.sh
- test/tekton-tests.sh
var `E2E_BASE_NAME` is no longer available
> fix(tekton e2e): Fix CONTAINER_REGISTRY name generation

- CHANGELOG.adoc
- lib/printing/describe.go
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/binding/describe.go
- pkg/kn/commands/source/ping/describe.go
- pkg/kn/commands/trigger/describe.go
There are multiple `writeSink` in source commands to print Sink object. And there is a utility `DescribeSink` in `lib/printing`. It's better to uniform them.
* Uniform multiple writeSink(s) to a single WriteSink
> Uniform multiple writeSink(s) to DescribeSink

- CHANGELOG.adoc
- docs/cmd/kn_broker_delete.md
- docs/cmd/kn_revision_delete.md
- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_delete.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/wait_flags.go
- pkg/kn/commands/wait_flags_test.go
- pkg/kn/flags/bool.go
- pkg/kn/flags/bool_test.go
Drop deprecated --async flag support  in the favor of --no-wait flag
* Drop --async flag
* Remove the respective test cases
* Add CHANGELONG
Fixes #1089
> Drop deprecated --async flag support

- CHANGELOG.adoc
- hack/build.sh
- hack/release.sh
Fixes https://github.com/knative/client/issues/1101
> feature: Add Linux arm64 builds to the release

- lib/test/service.go
I ran into the issue with E2E execution and `--imagetemplate`, when `TestServiceExport` fails comparing the wrong image value. I've found out that actual RevisionSpec used for the expected value is initialized with wrong value, hence the fix should mitigate that.
```bash
./test/local-e2e-tests.sh -run ^TestServiceExport$ --imagetemplate docker.io/dsimansk/{{.Name}}
...
- 								Image:   "/helloworld:latest",
+ 								Image:   "docker.io/dsimansk/helloworld",
```
* Add `BuildRevisionSpec` to lib/test/service.go to fix the issue
Fixes N/A
> fix: Fix var initialization in lib/service function

- CHANGELOG.adoc
- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/flags/podspec.go
- pkg/kn/flags/podspec_helper.go
This PR removes `--requests-cpu,--requests-memory,--limits-cpu,--limits-memory` that should be deprecated already per code comment:
```
// TODO: Flag marked deprecated in release v0.15.0, remove in release v0.18.0
```
@navidshaikh @rhuss @maximilien @daisy-ycguo @itsmurugappan 
If there's any reason or support concern that those flags might be still used/useful, please bring it up.
* Remove `--requests-cpu,--requests-memory,--limits-cpu,--limits-memory`
Fixes N/A
> chore: Remove deprecated requests/limits flags

- CHANGELOG.adoc
- pkg/kn/commands/channel/channel_test.go
- pkg/kn/commands/channel/create.go
- pkg/kn/commands/channel/create_test.go
- pkg/kn/commands/channel/describe_test.go
- pkg/kn/commands/channel/list_test.go
- pkg/messaging/v1beta1/channels_client.go
Embed the namespace in request body while creating channels
since on the eventing side, defaulting for channel isnt picking
the namespace from the context (see https://github.com/knative/eventing/issues/4514)
workaround for #1100
this changeset should be reverted when eventing#4514 is resolved
- Add namespace in the channel object meta while creating the channels
workaround for #1100 and https://github.com/knative/eventing/issues/4514
> Embed the namespace in request body while creating channels

- cmd/kn/main.go
- cmd/kn/main_test.go
- pkg/kn/commands/options/options.go
- pkg/kn/config/config.go
- pkg/kn/config/testing_test.go
- pkg/kn/traffic/compute.go
- pkg/serving/v1/client_test.go
- pkg/util/logging_http_transport_test.go
As per title.
- Flagging all whitespace occurrences with a TODO.
- Removing "dummy" and "sanity check".
> Fix a few more occurrences of divisive language

- CHANGELOG.adoc
- docs/cmd/kn_broker_describe.md
- docs/cmd/kn_channel_describe.md
- pkg/kn/commands/broker/describe.go
- pkg/kn/commands/broker/describe_test.go
- pkg/kn/commands/channel/channel_test.go
- pkg/kn/commands/channel/describe.go
- pkg/kn/commands/channel/describe_test.go
*Add -o url to describe of channel and broker resources
Fixes #1093
/lint
> Add url output for broker and channel

- CHANGELOG.adoc
- docs/cmd/kn_broker_describe.md
- pkg/eventing/v1beta1/client.go
- pkg/kn/commands/broker/describe.go
- pkg/kn/commands/broker/describe_test.go
Add machine readable output (-o flag) to `kn broker describe`
Fixes #1099
> Add machine-readable output for broker

- test/e2e-tests.sh
The ping source update for sink isnt working as expected.
see https://github.com/knative/eventing/issues/4584
> Run e2e CI job against eventing v0.19.1 since nightly is broken

- CHANGELOG.adoc
- docs/cmd/kn_trigger_describe.md
- pkg/eventing/v1beta1/client.go
- pkg/kn/commands/trigger/describe.go
- pkg/kn/commands/trigger/describe_test.go
*Add machine readable output (-o flag) to kn trigger describe
Fixes #1095 
/lint
> Add machine readable output for trigger

- hack/build.sh
- hack/release.sh
As part of the work to support the `knative` for the IBM Z system (`s390x` architecture), this PR is to make the `kn-linux-s390x` binary available in the `release`.
* Add an additional `go build` command with `GOOS=linux GOARCH=s390x` in `hack/build.sh` and `hack/release.sh`, respectively.
None
> Cross-compile the kn binary for linux/s390x

- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
Fixes #822
* adds --scale range option, #..#
Fixes #822 
Replaces previous PR where I had issues with a rebase - #1070 
Replaces previous PR where I had issues with a rebase - #986
> adds --scale range option

- CHANGELOG.adoc
- hack/build.sh
- hack/release.sh
- pkg/eventing/v1beta1/client.go
- pkg/serving/v1/client.go
- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
Backport PR for release-v0.18.4 with
- #1083
- #1113 
- Updated CHANGELOG
> [release-0.18] Backport #1083 #1113

- CHANGELOG.adoc
- docs/cmd/kn_source_apiserver_describe.md
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/apiserver/describe_test.go
- pkg/sources/v1alpha2/apiserver_client.go
*Add machine readable output (-o flag) to kn source apiserver describe
Fixes #1096
> Add machine readable output (-o flag) to kn source apiserver describe

- CHANGELOG.adoc
- docs/cmd/kn_source_binding_describe.md
- pkg/kn/commands/source/binding/describe.go
- pkg/kn/commands/source/binding/describe_test.go
- pkg/sources/v1alpha2/binding_client.go
Add machine readable output (-o flag) to kn source binding describe
Fixes #1097
> Add machine readable output (-o flag) to kn source binding describe

- CHANGELOG.adoc
- pkg/sources/v1alpha2/apiserver_client.go
- pkg/sources/v1alpha2/ping_client.go
Improve error handling in clients to capture server side errors
Fixes #
> Improve error handling in clients

- hack/build.sh
- hack/release.sh
As part of the work to enable knative for the IBM Power (ppc64le) architecture, this adds a `kn-linux-ppc64le` binary.  This is similar to the s390x enablement in #1083 .
Adds an additional `go build` command with `GOOS=linux GOARCH=ppc64le` in hack/build.sh and hack/release.sh, respectively.
> Build and release binaries for linux/ppc64le

- CHANGELOG.adoc
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/ping/describe.go
- pkg/kn/commands/trigger/describe.go
* Removes unnecessary help message introduced for machine readable outputs for commands which does not have `-o url` flag
Fixes #
> Remove unnecessary help message

- hack/release.sh
There're related commits on `release-0.19` branch, but it's missing on `master` branch. Let's fix that. 
* Bring the [fix](https://github.com/knative/client/commit/260970b054d9a577267ab9de6da2fe6c81c0ba77) to `master` branch 
Fixes N/A
/cc @navidshaikh @rhuss
> fix(release): Fix checksum quoting

- docs/cmd/kn_source.md
- docs/cmd/kn_source_container.md
- docs/cmd/kn_source_container_create.md
- docs/cmd/kn_source_container_delete.md
- docs/cmd/kn_source_container_describe.md
- docs/cmd/kn_source_container_list.md
- docs/cmd/kn_source_container_update.md
- pkg/kn/commands/source/container/container.go
- pkg/kn/commands/source/container/container_test.go
- pkg/kn/commands/source/container/create.go
- pkg/kn/commands/source/container/create_test.go
- pkg/kn/commands/source/container/delete.go
- pkg/kn/commands/source/container/delete_test.go
- pkg/kn/commands/source/container/describe.go
- pkg/kn/commands/source/container/describe_test.go
- pkg/kn/commands/source/container/human_readable_flags.go
- pkg/kn/commands/source/container/list.go
- pkg/kn/commands/source/container/list_test.go
- pkg/kn/commands/source/container/update.go
- pkg/kn/commands/source/container/update_test.go
- pkg/kn/commands/source/source.go
- pkg/kn/flags/podspec.go
- pkg/sources/v1alpha2/client.go
- pkg/sources/v1alpha2/container_client.go
- pkg/sources/v1alpha2/container_client_mock.go
- pkg/sources/v1alpha2/container_client_mock_test.go
- pkg/sources/v1alpha2/container_client_test.go
- test/e2e/source_container_test.go
Add command groups for container source, including
- create container source
- delete container source
- update container source
- list container source
- describe container source
Fixes #809
> Add command group for ContainerSource

- CHANGELOG.adoc
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_delete.md
- docs/cmd/kn_service_describe.md
- docs/cmd/kn_service_list.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/human_readable_flags.go
Per review comment in PR #1122.
* Add `--target` flag aka gitops feature to changelog entry
* Add `experimental` suffix to `--target` flag
/cc @rhuss @navidshaikh @itsmurugappan
> chore: Add gitops feature to changelog

- CHANGELOG.adoc
- cmd/kn/main.go
The error message contains pattern 'kn CMDs', thus send 'kn' string to match the pattern.
Sending `os.Args[0]` instead, may result in panics while compiling the regexp as it
may expand to the absolute path of the kn binary and the path may collide with regexp expressions.
Use `kn` string in regexp pattern as the error message always contains sub-string `'kn CMDs'`.
Fixes #1172
/lint
> fix: Parsing the kn commands from error message

- CHANGELOG.adoc
- pkg/kn/commands/service/export.go
- test/e2e/service_export_test.go
While exporting the service using `service export` command, ignore
the service labels with keys 'configUID' and `configUID`
* Strip the mentioned labels from service before export
see https://github.com/knative/serving/pull/10539 for further details
/lint
> Do not print serviceUID and configUID labels in service export result

- pkg/kn/commands/service/export.go
- test/e2e/service_export_test.go
Rename `configuUID` label to `ConfigurationUID`  followed up by https://github.com/knative/serving/pull/10579
- Rename the label to be removed from service export result; `configUID` --> `ConfigurationUID`
> Rename configUID label to ConfigurationUID 

- CHANGELOG.adoc
- pkg/kn/commands/source/binding/binding.go
- pkg/kn/commands/source/binding/create.go
- pkg/kn/commands/source/binding/describe_test.go
- pkg/kn/commands/source/binding/update.go
- pkg/util/parsing_helper.go
- pkg/util/parsing_helper_test.go
Moving a toReference to a public package, so that is it possible to invoke it, from kn plugins.
* Move `toReference` function to `knative.dev/client/pkg/util.ToTrackerReference`
* Move `parseSelector` function to `knative.dev/client/pkg/util.ParseSelector`
Fixes #1202
> Making a toReference public to enable reuse from kn-plugins

- pkg/kn/commands/revision/describe_test.go
This fix should unblock auto-upgrade PR that's changing `RevisionStatus.ServiceName` to `*.DeprecatedServiceName`. It seems to have no value in the affected unit test.
https://github.com/knative/client/pull/1207/files#diff-000f7df82089c9fe1ae3991339f7742aa78447291609f99bd15fc4ac3a71996fR122-R132
* Remove deprecated field from unit tests
Unblocks #1207
> fix: Fix deprecated ServiceName in revision describe test

- go.mod
- vendor/modules.txt
Latest Serving update will bring incompatible version, for more details see [the comment](https://github.com/knative/client/pull/1207#issuecomment-770866919).
* Pin `github.com/go-openapi/spec` version to `v0.19.3`
* The same version is used in `k8s.io/cli-runtime@v0.19.7 github.com/go-openapi/spec@v0.19.3`.
Unblocks #1207
> fix: Pin go-openapi/spec version to fix conflict

- cmd/kn/main.go
- go.mod
- pkg/kn/commands/completion/completion.go
- pkg/kn/commands/options/options.go
- pkg/kn/commands/plugin/list.go
- pkg/kn/commands/service/apply_mock_test.go
- pkg/kn/config/config.go
- pkg/kn/plugin/manager.go
- pkg/kn/root/root.go
- vendor/modules.txt
https://github.com/pkg/errors has been mostly subsumed into the stdlib, so there's no reason to use it anymore. Less dependencies, YAY!
/assign @rhuss
> Drop pkg/errors dependency and replace with stdlib usage

- .golangci.yaml
- cmd/kn/main.go
- pkg/dynamic/lib.go
- pkg/errors/factory.go
- pkg/kn/commands/options/options.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/source/duck/multisourcelist.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/config/config.go
- pkg/kn/plugin/manager.go
- pkg/kn/plugin/verify.go
- pkg/kn/root/root.go
- pkg/printers/tablegenerator.go
- pkg/serving/config_changes.go
- pkg/util/logging_http_transport.go
- pkg/util/logging_http_transport_test.go
This enables the `errorlint` linter, which is super helpful in catching "wrong" usages of errors (i.e. unsafe casts, ensuring errors are wrapped etc.)
* Enable the `errorlint` linter
* Make sure all errors that somehow contain a child error properly wrap the child
* Replace all comparisons and casts with deepchecks using `Is` and `As`
/assign @rhuss
> Enable errorlint and fix all issues

- .golangci.yaml
- pkg/kn/commands/revision/list.go
- pkg/kn/commands/service/update.go
- pkg/kn/flags/podspec_helper.go
- pkg/kn/traffic/compute.go
- pkg/printers/tableprinter.go
- pkg/wait/poll_watcher.go
- pkg/wait/wait_for_ready.go
Probably the linter that found the most bugs over in Serving. Think of it as a more aggressive deadcode linter, telling you about unused parameters and unused return types.
Tests are excluded as the noise ratio is much higher in them.
/assign @rhuss
> Enable unparam linter and fix issues

- .golangci.yaml
- pkg/dynamic/client.go
- pkg/kn/commands/broker/list.go
- pkg/kn/commands/channel/flags.go
- pkg/kn/commands/revision/human_readable_flags.go
- pkg/kn/commands/route/human_readable_flags.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/human_readable_flags.go
- pkg/kn/commands/source/apiserver/flags.go
- pkg/kn/commands/source/binding/flags.go
- pkg/kn/commands/source/container/human_readable_flags.go
- pkg/kn/commands/source/duck/multisourcelist.go
- pkg/kn/commands/source/human_readable_flags.go
- pkg/kn/commands/source/ping/flags.go
- pkg/kn/commands/subscription/flags.go
- pkg/kn/commands/trigger/list_flags.go
- pkg/kn/flags/podspec_helper.go
- pkg/kn/plugin/manager.go
- pkg/serving/service.go
- pkg/util/corev1_helper.go
As per title. I find this linter super useful in that it points out potential security issues and **at least** makes you think about them and document why it's not an issue (see the existing ones I fixed).
Also: Pointers to range variables are finnicky, see https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable. (These have been pointed out by gosec too)
* Comment on existing "security issues" to document why they are not an issue in this context.
* Remove all pointers to loop variables.
/assign @rhuss
> Enable gosec linter and fix existing issues

- OWNERS
- OWNERS_ALIASES
This update is for aligning with the other Knative projects so
that a group like the TOC list can be updated with less efforts
in the future.
Also I took the occasion to clean up a bit, so removed
@cppforlife and @sixolet as they are not active in the project since
at least one year. Happy to re-add both accounts again in the future.
Thanks a lot Naomi and Dmitriy for all your contribution and kicking off the client !
> Reorg OWNERS and introduced OWNERS_ALIASES

- OWNERS
Thanks to @itsmurugappan sustain and excellent work I would like to propose to add him to the reviewers list:
I am assuming the block is `reviewers:` (plural)
/assign @rhuss
* OWNERS file new section `reviewers:`
> Adding itsmurugappan to the `reviewers:` list

- CHANGELOG.adoc
- pkg/dynamic/client.go
- pkg/kn/commands/channel/list_types_test.go
- pkg/kn/commands/source/list_test.go
- test/e2e/source_list_test.go
The CRDs `v1beta1` version is deprecated since K8s 1.16 and will be removed in `1.22`. However, it may produce a warning on newer Kubernetes clusters already.
We should probably handle the warning as well and don't fail prematurely. 
* Update CRDs API version to `v1`
Fixes N/A
> chore: Update CRDs API version to v1

- pkg/kn/commands/service/export.go
- pkg/kn/commands/service/export_test.go
- test/e2e/service_export_test.go
Mode is ignored, when --with-revisions flag is not mentioned, this pr makes sure that mode is always honored.
* "replay" is the default mode
* replay without revisions will print ksvc
* replay with revisions will print ksvc list
* export mode with/without revisions will return knexport type
Fixes #1087 
cc @dsimansk
> kn export defect to honor mode

- CHANGELOG.adoc
- README.md
- docs/dev/developer-guide.md
- docs/plugins/README.md
- docs/workflows/basic.md
- pkg/serving/v1/gitops_test.go
- test/README.md
As per title, dropping all the refs to master that are now renamed to main. Also fixed a small occurrence in a test that seemed wrong anyway.
/assign @rhuss
> Drop master references to knative repos

- CHANGELOG.adoc
- docs/cmd/kn_revision_delete.md
- lib/test/revision.go
- pkg/kn/commands/revision/delete.go
- pkg/kn/commands/revision/delete_mock_test.go
- pkg/kn/commands/revision/delete_test.go
- test/e2e/revision_test.go
As per the review comment [#317 ](https://github.com/knative/client/issues/317#issuecomment-518628152)
- Add --prune option to remove all unreferenced revisions for a given service
- Add --prune-all option to remove all the unreferenced revisions
Fixes #317
> Add --prune & --prune-all options to delete the unreferenced revisions

- pkg/kn/plugin/manager_test.go
Since the GH actions've been updated to latest `golangci-lint` version. There's false-positive SA5011 error reported on every new PR, [for example](https://github.com/knative/client/pull/1264/checks?check_run_id=2115285161).
It seems as a false-positive report as the test code starts with not nil assert, but it seems to fall into corner case of staticcheck detection capabilities.
https://staticcheck.io/docs/checks#SA5011
* Fix SA5011 with not nil check
> Fix linting error SA5011

- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/revision/describe_test.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/describe_test.go
Currently the Status fields `ActualReplicas,DesiredReplicas` are set to `omitempty`. Therefore the current impl doesn't show any replica details if both values are `0`.
```
➜  client git:(main) ✗ kn service describe hello                 
Name:       hello
Namespace:  default
Age:        34s
URL:        http://hello.default.127.0.0.1.nip.io
Revisions:  
100%  @latest (hello-00001) [1] (34s)
Image:     docker.io/dsimansk/helloworld (pinned to 29f975)
Replicas:  1/1
Conditions:  
OK TYPE                   AGE REASON
++ Ready                  20s 
++ ConfigurationsReady    29s 
++ RoutesReady            20s 
```
* Add number of instances (`Replicas:`) to `kn service describe`
* Add number of instances (`Replicas:`) to `kn revision describe`
Fixes #842 
/assign @knative/client-reviewers
> Add number of instances to describe command

- pkg/kn/commands/domain/list.go
- pkg/kn/commands/domain/list_test.go
Follow-up PR to #1276. Fix `domain list` to output empty list in requested format.
> Fix domain list output

- CHANGELOG.adoc
- lib/test/integration.go
This PR intends to fix `serviceaccount "default" not found` flaky issue which is a race condition observed on some OCP4.x platforms.
`lib/test/integration.go` now waits for `default` serviceaccount to be ready before returning a new `KnTest` object when executing e2e tests.
> Fix for serviceaccounts "default" not found flaky issue

- pkg/eventing/v1/client.go
- pkg/eventing/v1/client_test.go
- pkg/serving/v1/client.go
- pkg/serving/v1/client_test.go
- pkg/wait/poll_watcher.go
- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
* Use `resourceVersion` in `*Delete` functions to get replay of events and prevent 
* Re-enable `retry` logic when watch channel is closed before timeout
Fixes #1287 
/cc @rhuss
> Refactor waiting loop to use resourceVersion

- test/common.sh
The current e2e test only runs over the network `istio`. It would be good to run the test over other network layers (e.g. `contour` and `kourier`) if the network is pre-installed and the environment variable `$INGRESS_CLASS` is set.
* Introduce an environment `$INGRESS_CLASS`
* Toggle off the `istio` installation when the `$INGRESS_CLASS` is set to a value other than `istio.ingress.networking.knative.dev` (e.g. `kourier` or `contour`)
* Set the `ingress.class` against the config map `config-network` in the e2e test
* Assume that the corresponding network should be installed in advance
Fixes #1337
> Make e2e test run over other networks

- hack/build.sh
Remove the force update hack introduced due to `prow-tests:stable` didn't contained the latest `go-licenses` binary. It should ok now, and tests should be passing.
* Remove force update of go-licenses binary
> Remove force update of go-licenses binary

- cmd/kn/main.go
- cmd/kn/main_test.go
Refactor `main` function to improve test coverage and testability of it as well.
* Refactor to minimal  `main()`
* Wrap `run` in `runWithExit()` to produce exit codes.
Related to #1322
> Improve test coverage of main package

- cmd/kn/main.go
- pkg/kn/commands/types.go
NOTE: it isn't crucial for the release. It can be reviewed afterwards.
The motivation is to have streamlined `main()` function. Therefore I've moved warning handler creation to more suitable place, that should serve as rest config entrypoint.
Seems to work fine :)
```
➜  client git:(pr/cleanup-main) kn service list           
Warning: Test warning
```
@markusthoemmes any objections to the change? :crossed_fingers: 
* Move warning handler from `main()` to `RestConfig()`
> Move warning handler from `main()` to `RestConfig()`

- pkg/printers/interface_test.go
- pkg/printers/tablegenerator_test.go
- pkg/printers/tableprinter_test.go
Current PR contains tests for tablegenerator.go
* Adding test case TestTableHandler for covering the TableHandler function
* Adding test case TestGenerateTable for covering the GenerateTable function 
* Using Service type for tests
Fixes #1322
> Adding tests for printer pkg

- test/e2e-tests.sh
- test/e2e/tekton_test.go
- test/tekton-tests.sh
Trying to fix the failures in nightly Tekton tests such as https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-client-tekton/1412758478874742784
Testgrid view: https://testgrid.k8s.io/r/knative-own-testgrid/client#tekton.
* Skip using Istio addon in Tekton tests
* Do not cleanup the test namespace when the test fails (for debugging purposes)
Fixes #
> Do not cleanup on failure in Tekton tests

- test/common.sh
Since `0.24` release `DomainMapping` CRDs and deployment resources are part of serving core yamls.
* Remove standalone DomainMapping setup
> Remove standalone DomainMapping setup

- CHANGELOG.adoc
- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- docs/cmd/kn_source_container_create.md
- docs/cmd/kn_source_container_update.md
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/flags/podspec.go
- pkg/kn/flags/podspec_helper.go
- pkg/kn/flags/podspec_helper_test.go
- pkg/kn/flags/podspec_test.go
make command as string array instead of string
Fixes #890
> make command as array instead of string

- lib/test/flags.go
- lib/test/integration.go
* allows for reusing test namespaces that were created in advance
(possibly by a cluster admininstrator)
Fixes one sub-issue from https://github.com/knative/client/issues/1352 which was originally tracked as https://github.com/knative/client/issues/1304
Introduce -reusenamespace flag which skips creating test namespaces. They're supposed to be created in advance by a user with sufficient privileges (cluster-admin).
This PR has a follow-up here: https://github.com/knative/client/pull/1384
*
Fixes #
> Introduce -reusenamespace test flag

- lib/test/broker.go
- test/README.md
- test/e2e/broker_test.go
- test/e2e/sink_test.go
- test/e2e/source_apiserver_test.go
- test/e2e/source_list_crd_test.go
- test/e2e/source_list_test.go
- test/e2e/trigger_test.go
This is a follow up to https://github.com/knative/client/pull/1383 (this PR depends on it) and fixes the remaining sub-issues from https://github.com/knative/client/issues/1304
As a result, it will be possible to run the test suite as a project admin (vs. cluster-admin).
* Create Broker explicitly rather than by labeling namespace
* Use Role instead of ClusterRole to work with Sources
* Separate SourceList test for cluster admin and regular user
* Instructions for running E2E as project admin
Fixes https://github.com/knative/client/issues/1352
> Run tests as project admin

- docs/cmd/kn_source_ping_create.md
- docs/cmd/kn_source_ping_update.md
- pkg/kn/commands/source/ping/create.go
- pkg/kn/commands/source/ping/create_test.go
- pkg/kn/commands/source/ping/describe_test.go
- pkg/kn/commands/source/ping/flags.go
- pkg/kn/commands/source/ping/list_test.go
- pkg/kn/commands/source/ping/ping_test.go
- pkg/kn/commands/source/ping/update_test.go
- pkg/sources/v1beta2/ping_client.go
Adding encoding option to specify base64 or text values. Adding support for base64 data through CLI
* Adding encoding option to specify the type of encoding of data.
* Adding code to identify automatically (without any encoding option specified) if given data is base64 encoded or not and setting the relevant field in PingSourceSpec.
* Adding a test case to cover these scenarios.
Fixes #1204
> Adding encoding flag and support for base64 data

- cmd/kn/main.go
- cmd/kn/main_test.go
There have been issues when a full Windows path has been inserted literally to create a regexp, since the backslashes used as path separators are confusing the regexp engine. This fix will quote any input coming from the outside.
> Fix issue with Windows pathes not being escaped when applying a regexp.

- pkg/wait/test_wait_helper.go
- pkg/wait/wait_for_ready.go
- pkg/wait/wait_for_ready_test.go
Allow using wait for ready with dynamic kube client, as before this change, an error was received on _Added_ event with unstructured object, which by default doesn't have `.status` field.
* 🐛 Bug fix of #1389 - Skipping on non-modified event while waiting for ready
Fixes #1389
> Skip non modified event first while waiting for ready

- test/e2e/source_apiserver_test.go
The resources are now namespaced-scoped so we should be using a kubectl with configured namespace
*
*
*
Fixes #
> Use namespaced kubectl for sa,role,rolebinding in tests

- docs/README.md
Fix default `directory` value
* change `~/.kn/plugins` to `~/.config/kn/plugins` 
- 🐛 Bug fix
> update plugin README

- CHANGELOG.adoc
- docs/cmd/kn_source_ping_create.md
- docs/cmd/kn_source_ping_update.md
- pkg/kn/commands/source/ping/create.go
- pkg/kn/commands/source/ping/describe.go
- pkg/kn/commands/source/ping/describe_test.go
- pkg/kn/commands/source/ping/flags.go
- pkg/kn/commands/source/ping/ping_test.go
- pkg/kn/commands/source/ping/update.go
- pkg/kn/commands/source/ping/update_test.go
- test/e2e/ping_test.go
Adding base64 data handling to ping update command. Handling comments from #1388 
* Adding a test case to test builder functions
* Handling base64 data in update command
* Modified usage/error strings for more clarity
Fixes #1204
> Adding base64 data handling to ping update command

- hack/build.sh
@rhuss per one of our discussion on PR review.
* Add `golangci-lint run` to default build flow
* Remove our `run_go_tool` in favour of `knative.dev/hack`
/cc @rhuss
> Add lint check to build.sh script

- pkg/kn/commands/namespaced_test.go
- pkg/kn/commands/revision/revision_test.go
- pkg/kn/commands/types_test.go
This PR is fixing several cases, when local/hosts `kubeconfig` might clash with actual tests. That should be handled by mocked or empty configs instead.
E.g.: having namespace point to `knative-serving` instead of `default` was causing test failures.
```
=== RUN   TestGetNamespaceSample
namespaced_test.go:53: assertion failed: default (string) != knative-serving (actualNamespace string) 
```
* Fix unit tests clash with local kubeconfig
> Fix unit tests clash with local kubeconfig

- CHANGELOG.adoc
- pkg/errors/factory.go
- pkg/errors/factory_test.go
In some cases, if an error  is from server but contains a substring that matches a client side error condition, the error returned by the server is being accompanied by the client side error message. This should not be the case.
* Moved the server error parsing case up so it gets processed before we breakdown the error string for client level message.
* Added test cases.
Fixes #1342
> Server errors should not be tainted by client error messages

- CHANGELOG.adoc
- docs/cmd/kn_broker_create.md
- lib/test/broker.go
- pkg/eventing/v1/client.go
- pkg/eventing/v1/client_test.go
- pkg/kn/commands/broker/broker_test.go
- pkg/kn/commands/broker/create.go
- pkg/kn/commands/broker/create_test.go
- test/e2e/broker_test.go
Adding --class option to broker create
* Added the flag to broker create command
* Added unit test 
* Added e2e test 
Fixes #1269
> Adding class option to broker create

- pkg/kn/plugin/manager.go
- pkg/kn/plugin/manager_test.go
Per discussion in [PR 1412](https://github.com/knative/client/pull/1412#issuecomment-892857273), found a bug where we fail to look up in path when there's slash in arguments. (This bug was also causing the service import test to fail). 
* fixing bug when looking up plugins on path with slash in argument
(changelog entry to follow)
/lint
> Fixing bug when looking up plugins on path with slash in argument

- pkg/kn/config/config.go
Look for knative plugins on the user's $PATH by default
* Set default value of `lookupPluginsInPath` to `true`
This results in the following behavior (copying from [Roland's comment](https://github.com/knative/client/issues/1399#issuecomment-888182293)):
* Lookup plugins from both, the path and `~/.config/kn/plugins`.
* Same named plugin in `~/.config/kn/plugins` take precedence over plugins found on the PATH.
This would also allow for system-wide plugins as installed by brew in `/usr/local/bin`, but allow individual users to override plugins in their `~/.config/kn/plugins` directory. Also, for people that currently collect their plugins in `~/.config/kn/plugins` nothing would change. It's just as if you would add this directory to the front of your $PATH.
Fixes #1399 
/lint
> Look up plugins on $PATH by default

- CHANGELOG.adoc
- docs/README.md
- docs/cmd/kn_plugin_list.md
- pkg/kn/commands/plugin/list.go
- pkg/kn/config/config.go
- pkg/kn/config/config_test.go
- pkg/kn/config/types.go
Lookup in path is now the default for all plugins.
This option will be removed eventually in a future version,
when path lookup is enabled uncoditinally and can't be turned of.
> Deprecate `lookup-path` option and updated relevant documentation

- CHANGELOG.adoc
- pkg/kn/commands/version/version.go
* Add missing entries to changelog
* Bump `version` strings to 0.25
/cc @rhuss 
FYI @knative/knative-release-leads, that's part of client release checklist, the remaining items are:
* Version bump in `go.mod`
* Update the version numbers of Serving and Eventing in test/presubmit-integration-tests-latest-release.sh so that the integration test is already running against the just released serving and eventing versions.
> Prepare changelog and version for 0.25 release

- hack/release.sh
* Fix release script to published darwin/arm64 bits 
We can probably upload the artifact manually to the release, but that'd require updated checksum file as well. Or we could probably release `0.25.1.` once we get a few more bugs to backport?
/cc @rhuss @maximilien
> Fix release script to published darwin/arm64 bits

- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/flags/sink_test.go
- pkg/kn/commands/source/duck/multisourcelist_test.go
- pkg/kn/commands/source/list_test.go
If the sink of the trigger is a normal service, the  `kn trigger list` command will show it as ksvc, which is incorrect
*
*
*
Fixes #
> fix kn trigger list command to show correct v1/service sink output

- test/e2e/service_export_test.go
- test/e2e/source_container_test.go
Images specified by digest are not set in user-image annotation. This PR corrects the test to work with image digest..
* Do not expect user-image annotation to contain the image if the image is specified by digest.
* Do not expect image name in the output of source list as it might not be available when images are passed as image digest.
Fixes #
> TestServiceExport works with images specified by digest

- test/e2e-tests.sh
- test/resources/tekton/kn-deployer-rbac-template.yaml
Make the tests compatible with Kube 1.22 which removes v1beta1
*
*
*
Fixes #
> Tekton - use ClusterRoleBinding v1

- hack/release.sh
Backport `release.sh` script fix #1427 from `main` branch.
* Fix release script to published darwin/arm64 bits
/cc @rhuss @maximilien @itsmurugappan
> [release-0.25] Fix release script to published darwin/arm64 bits

- CHANGELOG.adoc
- pkg/eventing/v1/client.go
- pkg/eventing/v1/client_mock.go
- pkg/eventing/v1/client_mock_test.go
- pkg/eventing/v1/client_test.go
- pkg/kn/commands/domain/update.go
- pkg/kn/commands/source/container/update.go
- pkg/kn/commands/source/ping/ping.go
- pkg/kn/commands/source/ping/update.go
- pkg/kn/commands/subscription/update.go
- pkg/kn/commands/trigger/update.go
- pkg/messaging/v1/subscriptions_client.go
- pkg/messaging/v1/subscriptions_client_mock.go
- pkg/serving/v1/client.go
- pkg/serving/v1alpha1/client.go
- pkg/serving/v1alpha1/client_mock.go
- pkg/serving/v1alpha1/client_mock_test.go
- pkg/serving/v1alpha1/client_test.go
- pkg/sources/v1/container_client.go
- pkg/sources/v1/container_client_mock.go
- pkg/sources/v1/container_client_mock_test.go
- pkg/sources/v1/container_client_test.go
- pkg/sources/v1beta2/ping_client.go
- pkg/sources/v1beta2/ping_client_mock.go
- pkg/sources/v1beta2/ping_client_mock_test.go
- pkg/sources/v1beta2/ping_client_test.go
Added retry loop from client go to service and source update commands.
* Added retry loop from client go to service update command.
* Added a retry updated method to ping source APIs.
Fixes #1102
> Adding retry loop to update

- pkg/kn/commands/revision/describe.go
- pkg/kn/commands/revision/describe_test.go
- pkg/kn/commands/service/describe_test.go
- pkg/kn/commands/service/update_test.go
Note to the reviewers: I'll open new issue to handle multi-container Revisions. Hence the PR uses only `ContainerStatus[0]` that should be equal to `DeprecatedImageDigest` by the following:
>// If multiple containers specified then DeprecatedImageDigest holds the digest
// for serving container.
https://github.com/knative/serving/blob/d2461492bea18cde5f9aa0419c8fee24570782aa/pkg/apis/serving/v1/revision_types.go#L139-L151
* 🐣 Remove `DeprecatedImageDigest` field
Fixes failing auto update PR #1452.
> Remove `DeprecatedImageDigest` field

- hack/build-flags.sh
- pkg/kn/commands/version/version.go
- pkg/kn/commands/version/version_test.go
for `kn version`. This is now directly extracted from go.mod and
saves one manual step when doing the release.
> Automatically set the proper version for the serving and eventing dependencies

- CODE-OF-CONDUCT.md
- Renaming COC doc to ALLCAPS as part of [GA](https://github.com/knative/community/issues/680)
/kind documentation
(using an updated COC from the [community repo](https://github.com/knative/community/blob/main/CODE-OF-CONDUCT.md), which substitutes the TOC for project maintainers in several spots)
/assign @rhuss  @omerbensaadon
> Renaming COC doc to ALLCAPS

- lib/test/service.go
It should prevent `--wait` being considered as name of ksvc in E2E dumps, e.g.:
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1463/pull-knative-client-integration-tests/1443231012153724928#1:build-log.txt%3A972
* Reorder `--wait` flag and `serviceName` in `serviceDelete` util function
> Fix sync serviceDelete in test utils

- pkg/config/defaults.go
- pkg/eventing/v1/client.go
- pkg/kn/commands/domain/update.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/service.go
- pkg/kn/commands/service/update.go
- pkg/kn/commands/source/container/update.go
- pkg/kn/commands/source/ping/ping.go
- pkg/kn/commands/source/ping/update.go
- pkg/kn/commands/subscription/update.go
- pkg/kn/commands/trigger/trigger.go
- pkg/kn/commands/trigger/update.go
- pkg/messaging/v1/subscriptions_client.go
- pkg/serving/v1/client.go
- pkg/serving/v1alpha1/client.go
- pkg/sources/v1/container_client.go
- pkg/sources/v1beta2/ping_client.go
- pkg/util/compare.go
Modifying default retry value for backoff during resource updates
* Changing the factor to 1.5 
* Changing MaxUpdateRetries to 5
Fixes #
> Changing the Default retry value

- pkg/kn/commands/source/ping/delete_test.go
Fixed the bug of `util.ContainsAll` of file https://github.com/knative/client/blob/main/pkg/kn/commands/source/ping/delete_test.go
/kind good-first-issue
/kind-bug
- Updating test case of TestDeleteWithError for covering the `util.ContainsAll` 
#1469
Test case has been changed to 
assert.Assert(t, util.ContainsAll(out, "Usage", "no such", "testsource"))
- 🐛 Bug fix
> Fix assertion in ping source unit tests

- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/update.go
- pkg/kn/commands/service/update_test.go
- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e/traffic_split_test.go
* Determine traffic split when N-1 revisions are specified
* In case `@latest` is specified, cannot determine the split unless it sums to 100
Fixes #
> Calculate traffic split when N-1 revisions are specified

- CHANGELOG.adoc
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/errors/factory.go
- pkg/errors/factory_test.go
- pkg/kn/commands/channel/list_types.go
- pkg/kn/commands/channel/list_types_test.go
- pkg/kn/commands/source/list_test.go
- pkg/kn/commands/source/list_types.go
Add a mention of client update to common missing API error message. In case of older client with newer backend with removed API, it might confusing why there's a failure.
* Reword missing API error to mention client update
Fixes #
> Reword missing API error to mention client update

- pkg/kn/config/config.go
- pkg/kn/config/config_test.go
~Add support to initialize kn config file or to skip it.~
Make a default config file with the newest settings if it doesn't exist.
* ~Add --init flag~
* ~Add --no-init flag~
* ~By default we read the config file and if it doesn't exist create it~
* Instead of `return null` if config file does not exist, create and populate it with default settings
* Set the default settings to what mentioned here: https://github.com/knative/client/blob/main/docs/README.md#options
*  Use viper to create the config file.
Related #1232
> Add support to (not) initialize kn config file

- test/e2e/domain_mapping_test.go
- test/e2e/sink_test.go
- test/e2e/trigger_test.go
* Add simple wait for URL to domain mapping E2E test
* Disable sync delete of brokers used in defer
> Fix the most common E2E flakes

- test/test_images/grpc-ping
- test/test_images/grpc-ping/release.yaml
The former setup seems to break builds on Golang 1.17 with missing go dependencies. 
And on pair with https://github.com/knative/client/blob/main/test/test_images/multicontainer/release.yaml
* Move away from grpc-ping test image as symlink
Fixes #
/cc @markusthoemmes
> Move away from grpc-ping test image as symlink

- CHANGELOG.adoc
- pkg/kn/commands/revision/describe.go
Fixed panic during `kn service describe`
* Added length check to prevent panic
Fixes #1528
> Fixed panic in kn service describe

- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- pkg/kn/commands/container/add.go
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/source/container/create.go
- pkg/kn/commands/source/container/update.go
- pkg/kn/flags/podspec.go
- pkg/kn/flags/podspec_test.go
Update descriptions to the following flags in `service create/update/apply`:
* env
* labels
* annotations
If you can not unset the label/annotation/env then don't mention it in the description of the flag.
Fixes #1449
> Fix env, annotation and labels flags in service create/update/apply

- docs/cmd/kn_service_create.md
- pkg/kn/commands/flags/traffic.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/update.go
- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e/traffic_split_test.go
Add `--tag` flag to service create and interpret just value arguments to the flag as `@latest=value`
When `@latest` is specified as argument to `--traffic` and sum < 100, calculate the remaining revision
* The arguments that don't follow `key=value` format and just `value` format will be treated as `@latest=value`
* `service create` will have a `--tag` flag so revision is created with a tag
* Updating traffic split for a service when `@latest` is specified and the total sum is less than 100 for a service with N revisions will work as follows:
* If the update leads to a new revision creation, total N `key=value` arguments need to be specified for `--traffic`
*  If the update does not create a new revision, total N-1 `key=value` arguments need to be specified for `--traffic`
Fixes #
> Add --tag flag to service create and allow traffic split <100 when @latest is specified

- CHANGELOG.adoc
- pkg/serving/config_changes.go
- pkg/serving/config_changes_test.go
- pkg/serving/revision_template.go
- pkg/serving/revision_template_test.go
Panic during updating traffic to a revision that is not ready
Before:
```
$ kn service update hello-example-3 --env TARGET="pqr" --traffic abcd=50,hello-example-3-00002=50
E1130 00:13:13.786017   76154 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x246a6a0, 0xc0006ac570})
/home/prow/go/src/knative.dev/client/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x5a0})
/home/prow/go/src/knative.dev/client/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x246a6a0, 0xc0006ac570})
/root/.gvm/gos/go1.17.2/src/runtime/panic.go:1038 +0x215 …
```
> Fixed panic when traffic split to unavailable revision

- hack/build-flags.sh
- hack/build.sh
- hack/build.sh.d/README.md
* 🎁 Allow overriding of `build.sh` for downstream projects
* ✨ Clean the scripts a bit, especially with [SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155) issue
Fixes #1543
> :gift: Allow overriding of `build.sh` for downstream projects

- pkg/kn/commands/completion_helper.go
- pkg/kn/commands/completion_helper_test.go
- pkg/kn/commands/namespaced.go
- pkg/kn/commands/service/delete.go
- pkg/kn/commands/service/describe.go
- pkg/kn/commands/service/update.go
Added ValidArgsFunc for autocompletion during `kn service describe` and `kn service update`
* Added ValidArgsFunc to `service describe` and `service update` commands
```
./kn service update hello-example<tab>
hello-example    hello-example-2  hello-example-3  hello-example-4
```
Fixes #1373
> Added autocompletion for service name

- pkg/kn/commands/broker/delete.go
- pkg/kn/commands/broker/describe.go
- pkg/kn/commands/completion_helper.go
- pkg/kn/commands/completion_helper_test.go
Added completion function for broker describe and delete
* Added completion function for broker resource
```
./kn broker describe<tab>
abc-broker   xyz-broker   xyza-broker
```
#1373
> Added autocompletion for broker

- CHANGELOG.adoc
- hack/generate-docs.go
Remove deprecated Hugo frontmatter generation for docs
The `generate-docs.go` command is used to build documentation pages for `kn` for display on knative.dev. Now that the website has fully deprecated Hugo, custom front-matter no longer needs to be added to those pages. This PR removes the front-matter function from the `generate-docs.go` job.
As per discussion [here](https://github.com/knative/docs/issues/4430#issuecomment-1008690021)
/lint
> Remove deprecated Hugo frontmatter generation for docs

- pkg/kn/commands/completion_helper.go
- pkg/kn/commands/completion_helper_test.go
- pkg/kn/commands/route/describe.go
Added completion function for autocompleting route name in `kn route describe` command
* Added completion function to `route describe` subcommand
* Added tests for the above
Fixes #1373
> Added completion for route name

- pkg/kn/commands/completion_helper.go
- pkg/kn/commands/completion_helper_test.go
- pkg/kn/commands/domain/delete.go
- pkg/kn/commands/domain/describe.go
- pkg/kn/commands/domain/update.go
Added auto completion function for domain command
* Added auto completion function for domain command
* Added unit tests for the above
> Added completion for domain command

- CHANGELOG.adoc
- pkg/kn/commands/channel/flags.go
`kn channel list` was panicking when a channel in the list didn't have `.Spec.ChannelTemplate` field set to a non-nil value.
* Added a nil check
Fixes #
> Fix for panic during channel list

- pkg/kn/commands/channel/delete.go
- pkg/kn/commands/channel/describe.go
- pkg/kn/commands/completion_helper.go
- pkg/kn/commands/completion_helper_test.go
- pkg/kn/commands/source/apiserver/delete.go
- pkg/kn/commands/source/apiserver/describe.go
- pkg/kn/commands/source/apiserver/update.go
- pkg/kn/commands/source/binding/delete.go
- pkg/kn/commands/source/binding/describe.go
- pkg/kn/commands/source/binding/update.go
- pkg/kn/commands/source/container/delete.go
- pkg/kn/commands/source/container/describe.go
- pkg/kn/commands/source/ping/delete.go
- pkg/kn/commands/source/ping/describe.go
- pkg/kn/commands/source/ping/update.go
- pkg/kn/commands/subscription/delete.go
- pkg/kn/commands/subscription/describe.go
- pkg/kn/commands/subscription/update.go
- pkg/kn/commands/trigger/delete.go
- pkg/kn/commands/trigger/describe.go
- pkg/kn/commands/trigger/update.go
- pkg/kn/commands/types.go
Context specific autocompletion for eventing resources
* Added the ValidArgs function for the following resources
* triggers
* source:
* ping
* sinkbinding
* apiserver
* container
* channel
* subscription  
Fixes #1373
> Adding completion for remaining Eventing resources

- test/e2e-tests.sh
It's affecting latest integrations tests with net-istio failing to deploy due too low cluster version.
E.g.: https://github.com/knative/client/pull/1571
* Remove k8s cluster version pin
> Remove k8s cluster version pin

- test/e2e/service_file_test.go
- test/e2e/service_import_test.go
Added file not found error check for windows specific message
* Added windows-specific string for non-existent file tests
Fixes #
> Fix for file not found error message discrepancy in windows

- test/presubmit-integration-tests-latest-release.sh
Updating the `presubmit-integration-tests-latest-release` test to Knative serving/eventing v1.2 as per https://github.com/knative/release#knativeclient
/hold
until serving/eventing are release on Jan 25
> Updates kn versions for presubmit integration test

- cmd/kn/main.go
- cmd/kn/main_test.go
- docs/cmd/kn.md
- hack/generate-docs.go
- pkg/kn/root/root.go
- pkg/kn/root/root_test.go
Removed hard-coded "kn" in usage/error messages
Fixes #1191
> remove hardcoded kn for usage and error

- hack/build-flags.sh
Change display versions for Serving and Eventing for major/minor updates.
```
$ TAG=v1.2.0 hack/build.sh
🚒 Update
=== Update Deps for Golang
--- Go mod tidy and vendor
--- Removing unwanted vendor files
--- Updating licenses
--- Removing broken symlinks
🔍 Lint
️ License
📖 Docs
🚧 Compile
Test
────────────────────────────────────────────
Version:      v1.2.0
Build Date:   2022-02-05 04:06:08
Git Revision: 6690a20e
Suppored APIs:
* Serving
- serving.knative.dev/v1 (knative-serving v1.2.0)
* Eventing
- sources.knative.dev/v1 (knative-eventing v1.2.0)
- eventing.knative.dev/v1 (knative-eventing v1.2.0)
```
* Add conditional statement in `hack/build-flags.sh` to check patch number to Serving and Eventing versions
* Displayed versions are depends on client's patch version
Fixes #1542
> change display versions

- pkg/kn/traffic/compute.go
- pkg/kn/traffic/compute_test.go
- test/e2e/traffic_split_test.go
* Automatic redirection of traffic should only take the active revisions into consideration
* Modified unit test according to the change
```
gvyas-mac:client gvyas$ ./kn revision list -s cloudevents-player
NAME                       SERVICE              TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
cloudevents-player-00005   cloudevents-player   100%             5            76m   3 OK / 4     True    
cloudevents-player-00004   cloudevents-player                    4            84m   3 OK / 4     True    
cloudevents-player-00003   cloudevents-player                    3            85m   3 OK / 4     True    
cloudevents-player-00002   cloudevents-player                    2            27d   3 OK / 4     True    
cloudevents-player-00001   cloudevents-player …
```
> Traffic split auto redirection should only consider the active revisions 

- go.mod
- pkg/kn/commands/version/version.go
- pkg/kn/commands/version/version_test.go
- third_party/VENDOR-LICENSE/golang.org/x/mod/semver/LICENSE
- vendor/modules.txt
For valid `Version` of kn take `MajorMinor + Patch` version of dependency, e.g for client's release `version=v1.3.0` + serving, eventing modules `v0.30.0`. The resulting displayed version should be also `v1.3.0`. Those versions should represent production releases tagged and published. Otherwise keep plain unmodified version from `go.mod`, that should cover local or nightly builds etc.
```
➜  client git:(pr/display-version) ./hack/build.sh -f
🚧 Compile
➜  client git:(pr/display-version) kn version
Version:      v20220308-local-9b0e1036
Build Date:   2022-03-08 15:40:19
Git Revision: 9b0e1036
Supported APIs:
* Serving
- serving.knative.dev/v1 (knative-serving v0.29.1-0.20220307224905-f428fa524adc)
* Eventing
- sources.knative.dev/v1 (knative-eventing v0.29.1-0.20220307200636-9590bc3a96a3) …
```
> Refactor version command to use go modules

- test/presubmit-integration-tests-latest-release.sh
Remove the need to update the tests with each release.
Grabs the list of remotes that start with `release-`, strip everything before `-` and sort from highest to lowest. Finally use the highest one as version.
NOTE: this returns `1.3` currently. Is the `1.3.0` needed?
> Grab latest version in presubmit

- test/common.sh
- test/presubmit-integration-tests-latest-release.sh
Follow-up on #1625 to introduce upper limit version inferred from current branch. The motivation is to get rid off a manual release step to update the version string, and also keep floating version limited to correct context.
* Infer versions for E2E tests from current branch
> Infer versions for E2E tests from current branch

- docs/cmd/kn_service_apply.md
- docs/cmd/kn_service_create.md
- docs/cmd/kn_service_update.md
- pkg/kn/commands/service/configuration_edit_flags.go
- pkg/kn/commands/service/create.go
- pkg/kn/commands/service/create_mock_test.go
- pkg/kn/commands/service/create_test.go
Add `--timeout` option which will set the field, `timeoutInSeconds` in service spec. 
* Added the flag
Fixes #1181
> Add timeout option to service create

- CHANGELOG.adoc
- pkg/kn/commands/completion_helper_test.go
- pkg/kn/commands/namespaced_test.go
- pkg/kn/commands/plugin/list_test.go
- pkg/kn/commands/service/create_test.go
- pkg/kn/commands/service/import_test.go
- pkg/kn/commands/types_test.go
- pkg/kn/config/config_test.go
- pkg/kn/flags/podspec_helper_test.go
- pkg/kn/flags/podspec_test.go
- pkg/kn/plugin/manager_test.go
- pkg/serving/v1/gitops_test.go
- test/e2e/channels_test.go
- test/e2e/extra_containers_test.go
- test/e2e/plugins_test.go
- test/e2e/service_file_test.go
- test/e2e/service_import_test.go
- test/e2e/sinkprefix_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer require.NoError(os.RemoveAll(tmpDir))
// now
tmpDir := t.TempDir()
}
```
* Replace `ioutil.TempDir` with `t.TempDir`
* Remove redundant `os.RemoveAll(tmpDir)` since the temporary directory will be removed automatically once the test complete.
/lint
> test: use `T.TempDir` to create temporary test directory

- docs/cmd/kn_trigger_create.md
- docs/cmd/kn_trigger_update.md
- pkg/kn/commands/trigger/update_flags.go
Per Eventing change in Sugar controller config, user need to enable the behavior.
@rhuss maybe we should considere adding label flag to trigger creation instread of hardcoded name. 
* Mark --inject-broker flag as deprecated
Fixes #1629 
```console
➜  client git:(pr/deprecate-inject-broker) kn trigger create broker-trigger --inject-broker --sink ksvc:broker-display --filter type=dev.knative.sources.ping
Flag --inject-broker has been deprecated, effective since 1.4 and will be removed in 1.6 release. 
Please refer to 'Automatic Broker Creation' section for configuration options, https://knative.dev/docs/eventing/sugar/#automatic-broker-creation.
```
> Mark --inject-broker flag as deprecated

- hack/build-flags.sh
- hack/build.sh
- hack/release.sh
* Fix OCI image build
Related to #257
/cc @rhuss
> Fix OCI image build

- test/tekton-tests.sh
There's temporary commit to enable Tekton tests. It should be removed once the change is verified.
* Bump Tekton pipeline version to latest by default
https://testgrid.k8s.io/r/knative-own-testgrid/client#tekton
> Bump Tekton pipeline version to latest by default

- test/common.sh
Since Knative >= 1.4 standalone Sugar controller is integrated into main Eventing one. Currently it's producing harmless 404 error during E2E tests setup, but it might be confusing or break in the future. 
Integrations tests should pass without issues.
* :broom: Cleanup sugear controller setups
> Cleanup sugar controller setup

- docs/cmd/kn_broker.md
- docs/cmd/kn_broker_create.md
- docs/cmd/kn_broker_update.md
- pkg/eventing/v1/client.go
- pkg/eventing/v1/client_mock.go
- pkg/eventing/v1/client_mock_test.go
- pkg/eventing/v1/client_test.go
- pkg/kn/commands/broker/broker.go
- pkg/kn/commands/broker/broker_test.go
- pkg/kn/commands/broker/create.go
- pkg/kn/commands/broker/create_test.go
- pkg/kn/commands/broker/delivery_option_flags.go
- pkg/kn/commands/broker/update.go
- pkg/kn/commands/broker/update_test.go
Added delivery options to `kn broker create`
* Added `--dl-sink`, `--timeout`, --`backoff-policy`, `backoff-delay`, `retry-after-max`, `--retry` flags
* Validation is on the server side for the values
* Added unit test cases
Fixes #1557
> Added delivery options to broker create

- test/presubmit-tests.sh
Addresses https://github.com/knative/hack/issues/200
Removes a dead variable in the presubmit tests related to markdown linting
> remove defunct markdown linting variable

- test/e2e/service_test.go
Not every cluster might be ready to fulfill PVC. 
* :broom: Add check for PVC status in E2E tests
Fixes #
```release-note
NONE
```
> Add check for PVC status in E2E tests

- pkg/kn/flags/podspec_helper.go
- test/e2e/service_test.go
When initializing volumes for flag usage like in E2E `--mount /mydir5=pvc:test-pvc`. We shouldn't probably enforce `readOnly: true` on the created volume PVC. We may end up with service stuck in initialization phase, because of underlying storage config, e.g. some volumes are being formatted first. 
Error from volume init:
```
Warning  FailedMount             1s (x4 over 7s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-1577f113-81c1-44f9-861f-5def40d13e8b" : cannot mount unformatted disk /dev/nvme2n1 as we are manipulating it in read-only mode
```
Former behavior:
```
volumes:
- name: mydir5-aa14be68
persistentVolumeClaim:
claimName: test-pvc
readOnly: true
```
/cc @vyasgun @rhuss @skonto 
* Fix volume creation for PVC
Fixes #
```release-note …
```
> Fix volume creation for PVC

- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/flags/sink_test.go
* The user can specify the sink with custom resource types
* Follows the format: `prefix:name:namespace` where prefix is the group version resource
Fixes #1704
```release-note
Add support for providing sink spec in GVR format
```
> Add support for providing sink spec in GVR format

- pkg/kn/commands/flags/sink.go
- pkg/kn/commands/flags/sink_test.go
Added gvr sink test cases and support to specify resource as singular/plural
* Added 2 tests for singular/plural forms of pingsource resource type
* Added a negative test for an absent resource
Fixes #1704 
Follow up for: https://github.com/knative/client/pull/1717
```release-note
Add singular/plural support to `--sink` flag
```
> Added gvr sink test cases and support to specify resource as singular/plural

- hack/release.sh
This should fix display version for release. IMO the `build_flags.sh` script was sourced too soon, before release values (especially `${TAG}`) were properly populated.
/cc @rhuss 
* Fix release script version calculation
Fixes #
```release-note
Fix release script version calculation
```
/kind bug
> Fix release script version calculation

- hack/release.sh
* fix: Fix image tag for nightly builds
That's a follow up to my previous PR that added check around "latest" tag. We need those on release branches only, nightly release for main should always be tagged latest.
Follow-up https://github.com/knative/client/pull/1792
```release-note
NONE
```
/cc @rhuss
> fix: Fix image tag for nightly builds

- pkg/kn/commands/trigger/describe.go
- pkg/kn/commands/trigger/describe_test.go
* 🎁  feat: Add cesql filter field to trigger describe cmd
Preview:
```shell
➜  client git:(pr/desc-cesql-filter) ✗ kn trigger describe broker-display
Name:         broker-display
Namespace:    default
Labels:       eventing.knative.dev/broker=mybroker
Annotations:  eventing.knative.dev/creator=kubernetes-admin, eventing.knative.dev/lastModifier=ku ...
Age:          12h
Broker:       mybroker
Filter:
type:       dev.knative.demo.event.processed
Filters (experimental):
CESQL:                 LOWER(type) = 'my-event-type'
Sink:
Name:      event-display
Resource:  Service (serving.knative.dev/v1)
Conditions:
OK TYPE    AGE REASON
``` 
Fixes #1785 
```release-note
Add experimental filters to `trigger describe` cmd
```
> feat: Add experimental filters to trigger describe cmd

- hack/build.sh
* ✨fix: Use go_run from common lib instead of deprecated `run_go_tool`
* Move bash flags up and expand to names
Fixes #
```release-note
NONE
```
/cc @rhuss
> fix: Use go_run from common lib

- lib/test/eventtype.go
This's changed on the Eventing end with latest nightly versions.
/cc @vyasgun @rhuss 
* Fix broker condition check
Fixes #
```release-note
NONE
```
> Fix broker condition check

- test/e2e/eventtype_test.go
- test/e2e/service_export_test.go
* Remove e2e skip flags after release
Per the PR reviews last week, removing unneeded skips.
/cc @rhuss 
```release-note
NONE
```
> Remove e2e skip flags after release

- docs/cmd/kn_trigger_update.md
- pkg/kn/commands/trigger/update_flags.go
- pkg/kn/commands/trigger/update_test.go
* Remove unusable `--broker` flag from `trigger update` cmd
Fixes #1813 
```release-note
Remove unusable `--broker` flag from `trigger update` cmd
```
> Remove unusable `--broker` flag from `trigger update` cmd

- .github/pull-request-template.md
* Update PR template not to mention changelog anymore
For a while now, we are fully on-boarded to automated Release Notes collection from PRs. This removes the leftover message that might be confusing. 
Fixes #
```release-note
NONE
```
> Update PR template not to mention changelog anymore

- hack/build.sh
* build.sh script
Fixes #1859 
```release-note
Fix shellcheck warnings in `hack/build.sh` script
```
> Fix shellcheck warnings in hack/build.sh script

- cmd/kn/main.go
- cmd/kn/main_test.go
- pkg/kn/commands/service/describe.go
- pkg/kn/config/config.go
- pkg/kn/config/config_test.go
- pkg/kn/config/testing.go
- pkg/kn/config/testing_test.go
- pkg/kn/config/types.go
- pkg/kn/plugin/context_sharing.go
- pkg/kn/plugin/context_sharing_test.go
- pkg/kn/plugin/context_types.go
- pkg/kn/plugin/manager.go
This's a bit simplified approach from original Feature Track proposal. I wonder if we should simply start with a few well known keys, that can be consumed in `kn` core + plugins
*
*
*
Fixes #
```release-note
TBD
```
/cc @rhuss
> Context Sharing POC

- README.md
Part of https://github.com/knative/community/issues/1403
Adds a link to the CLOTRIBUTOR page for Knative to the README
> add clotributor to readme

- test/e2e/domain_mapping_test.go
* Add trim to domain wait loop
There's an ongoing intermittent failure that causing flaked E2E tests. The wait loop doesn't seem to be very effective to prevent those. Trying to add simple string trim. Any other ideas are welcome. :)
/cc @rhuss 
Fixes #1873 
```release-note
Fix wait-loop in domain E2E test
```
> Fix wait-loop in domain E2E test

- docs/cmd/kn_completion.md
- pkg/kn/commands/completion/completion.go
- pkg/kn/commands/completion/completion_test.go
Enable the cobra based completion support for the fish and PowerShell shells.
* Add completion support for fish and powershell
Fixes #1928 
```release-note
Add completion support for fish and PowerShell shells
```
> Add completion support for fish and PowerShell shells

- pkg/kn/flags/podspec.go
- pkg/kn/flags/podspec_helper.go
- pkg/kn/flags/podspec_test.go
* Setting container's RunAsUser field based on the `--user` flag at the end so it does not reinitialize the security context
Fixes #1926 
```release-note
```
> Populate container.SecurityContext.RunAsUser when --user flag is used

- pkg/serving/v1/client.go
- pkg/serving/v1/client_test.go
* Fix `kn service wait` for already ready ksvc
Per the linked issue, the `wai`t cmd doesn't react properly in case of KSVC is already ready when wait-loop is started. It's caused by lack of any new events from cluster to wait upon.
/cc @rhuss 
Fixes #1922 
```release-note
```
> Fix `kn service wait` for already ready ksvc

- hack/build-flags.sh
* Fix package location for build flags
Fixes #
```release-note
Fix `version` command to dispaly proper version string
```
/cc @rhuss @cardil 
@cardil that's an overlooked issue from the client-pkg migration. 
Fixes  #1977
> Fix package location for build flags

- hack/build.sh
* Add target platform flag to build script
Fixes #
```release-note
Add target `--platform` flag to build script
```
> Add target platform flag to build script

- pkg/output/tui/spinner_test.go
By checking for smaller parts of the expected TUI, we can effectively fix the flakiness, which comes primarily from race condition.
* Checking parts of the message to combat flaky `output/tui.TestSpinner`
Fixes #1985
> Checking parts of the message to combat flaky tests
